### ISSUE TITLE
Описание человека липнет к имени

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/platform#1006]
## Проблема

Благодаря новым ролям у редакции всё выглядит чётко и красиво:

![image](https://user-images.githubusercontent.com/91747573/196245601-148d9734-efd5-4872-9416-6310512b6172.png)

А вот у тех, у кого ролей нет (у большинства), заголовок некрасиво налезает на первую строчку:

![image](https://user-images.githubusercontent.com/91747573/196245946-4822b594-8c55-456c-a9cc-3018e33d169d.png)

## Решение

Сделать отступ такой же как у роли — 20px.

![image](https://user-images.githubusercontent.com/91747573/196246390-616f82f7-0c19-4782-8b31-5ecd860a5508.png)

**Comment by igsekor** [comment]
Это и было так по дизайну. Новый PR на это никак не повлиял. @skorobaeus может пора изменить?

**Comment by StarHamster** [comment]
Как это не повлиял?.. повлиял! Теперь у редакции классные воздушные отступы 😁

**Comment by igsekor** [comment]
До изменений:

<img width="1438" alt="Screenshot 2022-10-18 at 11 40 01" src="https://user-images.githubusercontent.com/13916521/196382950-67255a6c-699a-4dc4-8460-32e812bd9940.png">

После изменений:

<img width="1440" alt="Screenshot 2022-10-18 at 11 44 44" src="https://user-images.githubusercontent.com/13916521/196383039-86829dcd-717e-4a06-80b1-0568a5625296.png">

**Comment by StarHamster** [comment]
Да я и не говорю, что что-то изменилось у обычных людей. Я говорю, что у редакции за счёт добавления ролей текст отлип от заголовка. Потому что у роли есть воздушный отступ в 20px. Я хочу, чтобы у тех, у кого нет роли, тоже появился такой воздушный отступ в 20px (а не 5px, как сейчас)

**Comment by StarHamster** [comment]
Я просто в пример привожу редакцию, мол, смотрите, как классно выглядит! Давайте сделаем так у всех

**Comment by igsekor** [comment]
В новом дизайне эта проблема решена. В ближайшее время внедрим.
