### ISSUE TITLE
Вложенность в список ломает разметку

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/platform#1014]
## Проблема

Если вложить что-нибудь в список с помощью отступов, то всё ломается: у вложенного контента не будет отступов, блоки кода съезжают и весь мир обращается в огонь.

## Пример

Вот как было:

````md
1. В именах классов используй только английские слова.

```html
<!-- Плохо -->
<p class="osnovnoy-text">
  Его экзистенциальная тоска выступает как побудительный мотив творчества,
  однако символизм начинает импрессионизм.
</p>

<!-- Хорошо -->
<p class="main-text">
  Его экзистенциальная тоска выступает как побудительный мотив творчества,
  однако символизм начинает импрессионизм.
</p>
```

Тестовый текст. Дока — суперская документация!

2. Имена классов пишутся маленькими буквами.
````

![изображение](https://user-images.githubusercontent.com/91747573/197328027-a4c838be-0f48-4fa9-9ba2-6f7c7575ebbe.png)

Но это не совсем правильно. Ведь такой текст прасится, как несколько списков с атрибутом `start`. Добавим отступы в 4 пробела, чтобы вложить блок кода и текст после него в список:

````md
При выборе имени класса следует придерживаться нескольких правил:

1. В именах классов используй только английские слова.

    ```html
    <!-- Плохо -->
    <p class="osnovnoy-text">
      Его экзистенциальная тоска выступает как побудительный мотив творчества,
      однако символизм начинает импрессионизм.
    </p>

    <!-- Хорошо -->
    <p class="main-text">
      Его экзистенциальная тоска выступает как побудительный мотив творчества,
      однако символизм начинает импрессионизм.
    </p>
    ```

    Тестовый текст. Дока — суперская документация!

2. Имена классов пишутся маленькими буквами.
````

И... всё ломается(

![изображение](https://user-images.githubusercontent.com/91747573/197328218-cb2ca50e-403a-4ac2-83f9-b968703b8d32.png)

## Примечания

Запускал локально через `npm start`.

У меня также есть опасения, что, если запушить такой код, линтер будет ругаться на количество пробелов. А ведь в markdown работают только отступы в 4 пробела, а в 2 — не работают.

**Comment by solarrust** [comment]
Выглядит как баг компилятора 11ty. 🤔
Можешь проверить на других md-центричных сайтах с этим фреймворком?

**Comment by TatianaFokina** [comment]
Я потестила в своём блоге на 11ty + md.

![Вложенный в нумерованный список код. Всё отображается правильно.](https://user-images.githubusercontent.com/17615202/197333663-eb6dc503-ba36-4478-a226-a82b2aab74a0.png)

**Comment by StarHamster** [comment]
Там точно одна из проблем — беда со стилями. Ведь у `Тестовый текст. Дока — суперская документация!` даже отступов не появляется при вложенности. А вот блоки кода реально странно парсятся, там уже не в стилях проблема, наверное 🤔

**Comment by TatianaFokina** [comment]
Кажется, что это не надо фиксить и в каком-то смысле это защита от неправильно оформленного списка. В правильном списке не может быть таких огромных пунктов с какой-то дикой вложенностью.

**Comment by StarHamster** [comment]
Йоу... почему... почему это неправильной оформленный список? Хотя бы один уровень вложенности точно должен быть. Ну вот взять тот же [мой пример](https://doka.guide/html/class/#kak-pishetsya). Блоки кода не вложены в список, а стоят особняком. У этого есть множество проблем:

1. Это неправильная верстка, кмк. У нас не один красивый список с наследниками, а множество чередований контента, который должен быть вложен, и списков с заданным значением старта нумерации. @TatianaFokina, мне кажется ты, как адепт a11y, должна понимать, что это может ввести в заблуждение людей.
2. Где заканчивается список и начинается другой контент? Опять же возвращаясь, к моему примеру, кмк, последний абзац после списка к самому списку не относится. Я бы сделал вот так:

    ````md
    8. Не используйте пробел для разделения слов внутри одного имени класса.

        В примере ниже `main` и `text` будут восприниматься браузером как два отдельных класса, а не один, состоящий из двух слов.

        ```html
        <p class="main text">
          Его экзистенциальная тоска выступает как побудительный мотив творчества,
          однако символизм начинает импрессионизм.
        </p>
        ```

    Есть несколько методологий именования классов. Самой популярной на сегодня является [БЭМ](https://ru.bem.info/methodology/). Методология призвана определить дополнительные правила именования классов и облегчить процесс придумывания имён.
    ````

    И парсилось бы это так:

    > 8. Не используйте пробел для разделения слов внутри одного имени класса.
    >
    >    В примере ниже `main` и `text` будут восприниматься браузером как два отдельных класса, а не один, состоящий из двух слов.
    >
    >     ```html
    >     <p class="main text">
    >       Его экзистенциальная тоска выступает как побудительный мотив творчества,
    >       однако символизм начинает импрессионизм.
    >     </p>
    >     ```
    > Есть несколько методологий именования классов. Самой популярной на сегодня является [БЭМ](https://ru.bem.info/methodology/). Методология призвана определить дополнительные правила именования классов и облегчить процесс придумывания имён.

    А в доке показать, что относится к списку, а что — нет, не получится.

А я вот сейчас показал. Это стока уже не относится к списку. Круто, да? А ещё удобно и правильно 🤞

**Comment by TatianaFokina** [comment]
То, что ты пытаешься сделать, не делают в виде списка. Пункты списка должны быть краткими, в пару предложений. В них так же можно вкладывать списки. Картинки, образцы кода и вот это все не должно быть списком. Тогда теряется вся их суть, это выглядит как гигантские куски текста, которые просто пронумерованы. Пронумеровать их можно и без списка.

**Comment by StarHamster** [comment]
Почему списки должны быть короткими? «Огромные пронумерованные куски текста» в моём понимании тоже списки

**Comment by TatianaFokina** [comment]
> Почему списки должны быть короткими? «Огромные пронумерованные куски текста» в моём понимании тоже списки

Можешь кинуть ссылкой на справочник, например, где об этом написано? Если ты посмотришь на справочники по типографики, то таких примеров не встретишь. То, что HTML позволяет запихивать огромные полотна текста внутрь `<ul>` или `<ol>` не отменяет правил.

**Comment by skorobaeus** [comment]
С точки зрения типографики и организации информации (aka дизайна 😁), оформлять в виде списков полотна текста, и правда, нехорошо. Столкнувшись с таким, я задалась бы вопросом "а правда ли здесь нужен список?".

Кажется, в данном случае игра не стоит свеч и ишью можно с чистой совестью закрыть.
