### ISSUE TITLE
Добавить сообщение об успешном копировании ссылки на раздел

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1036]
Сейчас при копировании ссылки на конкретный раздел доки или статьи не понятно, она скопировалась вообще или нет. Было бы клёво добавить какое-то сообщение о том, что ссылка скопирована и всё хорошо.

Я тревожный пользователь, поэтому мне было слегка не по себе, когда я копировала так ссылку и не поняла, что она скопирована сразу.

Перед тем, как начать заниматься кодом, нужно продумать дизайн ⚠️

**Comment by Inventoris** [comment]
@TatianaFokina, я вроде добавлял небольшое уменьшение значка после клика, но с сообщением точно получится понятнее. Могу сделать, тогда обсудим дизайн?

**Comment by TatianaFokina** [comment]
Кажется, что оно вообще не о чём не говорит. Это не самый распространённый паттерн для пользователей, боюсь, что мало кто поймёт, что всё скопировано успешно.

@skorobaeus,поможешь с дизайном того, как это может выглядеть?

**Comment by skorobaeus** [comment]
Привет!

Предлагаю заменять иконку ссылки при клике на неё. В очень нежном варианте на галочку, в более прямолинейном на сообщение, что ссылка скопирована, так как место нам позволяет.

Через некоторое время, достаточное, чтобы понять, что произошло, галочка и / или сообщение сменялось бы обратно на иконку ссылки.

![image](https://user-images.githubusercontent.com/29401439/207022226-4d50d602-0751-47ba-8a3f-38cf30d0d813.png)

**Comment by Inventoris** [comment]
@skorobaeus, задизайнишь мобильную версию? Текст подсказки перестаёт влезать, и его нужно куда-то приспособить, не потеряв красоту.

![image](https://user-images.githubusercontent.com/106589280/208244685-5ddc8b14-1d9c-4377-b82d-4a07d4857d30.png)

![image](https://user-images.githubusercontent.com/106589280/208244627-18800477-4eea-4b06-a846-31be41a4193c.png)

**Comment by Inventoris** [comment]
Кажется, оставить подсказку в мобильных будет тяжело.

**Comment by TatianaFokina** [comment]
Можно сделать тултипом, который появляется над кнопкой в крайнем случае. Как [на Веб-стандартах](https://web-standards.ru/articles/a11y-from-scratch/). И писать просто «Скопировано». Но это так, рассуждения вслух про альтернативные варианты.

**Comment by Inventoris** [comment]
Да, видел предложение в дискорде. Но мобильная версия тултипа у них хромает, если он не вмещается, то либо создает горизонтальный скролл, либо вообще улетает за пределы экрана, как тут:

![image](https://user-images.githubusercontent.com/106589280/208492498-b240717e-99e7-4653-b997-bcc3d1ffa19c.png)

На мой взгляд, можно оставить подсказку для десктопа, а для мобильных просто ставить галочку.

**Comment by TatianaFokina** [comment]
Я думаю, что решение есть, а галочка — это очень неочевидное решение. Не надо так пренебрегать мобильными пользователями :)

Тултип можно сделать так, чтобы он нормально позиционировался на всех устройствах. Если идти по этому пути.

**Comment by Inventoris** [comment]
Тогда ждём мнение уважаемой @skorobaeus по этому деликатному и заковыристому дизайнерскому вопросу 🐨

**Comment by skorobaeus** [comment]
Я сократила надпись до слова "Скопировано" и прикинула вариант на случай, если заголовок слишком длинный:

![image](https://user-images.githubusercontent.com/29401439/208657250-74c90b1f-f579-41b2-862b-1fc423111866.png)

Механизм — отнять от длины заголовка столько пикселей, сколько требуется сообщению о копировании. Тогда сообщение либо поместится без проблем, либо будет перенесено хоть одно слово заголовка и тогда иконка ссылки / надпись о копировании не повиснут в одиночестве на новой строке. У текста рваный край справа, поэтому поджатый заголовок не будет казаться неестественным.

Этот же механизм можно использовать и на планшетах.

На мобильных я бы предложила унести сообщение в попап в самом верху страницы:

![image](https://user-images.githubusercontent.com/29401439/208658952-74c4b85c-538e-4f9a-810e-d39a82b1a090.png)

**Comment by Inventoris** [comment]
@skorobaeus мне очень нравится текущий вариант, лаконично :)
