### ISSUE TITLE
Некоторые превью PR из `doka-guide/content` выдают `500` ошибку

### ISSUE THREAD

**Issue by rakleed** [doka-guide/platform#1050]
Некоторые превью PR из [`doka-guide/content`](https://github.com/doka-guide/content/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) выдают `500` ошибку:
- https://content-4157.dev.doka.guide/ (из https://github.com/doka-guide/content/pull/4157)
- https://content-4153.dev.doka.guide/ (из https://github.com/doka-guide/content/pull/4153)
- https://content-4156.dev.doka.guide/ (из https://github.com/doka-guide/content/pull/4156)

А у https://content-4125.dev.doka.guide/ (из https://github.com/doka-guide/content/pull/4125) отсутствуют стили, хотя PR только добавлял новую статью.

**Comment by TatianaFokina** [comment]
Превью контента сейчас работают, так что можно закрывать ишью.

**Comment by rakleed** [comment]
@TatianaFokina а что то было сделано, чтобы решить проблему? Так как вот [пример превью](https://content-4250.dev.doka.guide), которое было [2 недели назад](https://github.com/doka-guide/content/pull/4250#issuecomment-1427138372), где на главной странице просто не загружаются стили.

**Comment by TatianaFokina** [comment]
Ишью касается превью в контенте, а не в платформе. Можно заклянуть в [любой свежий контентный ПР](https://github.com/doka-guide/content/pull/4286).
