### ISSUE TITLE
Избавиться от горизонтального скролла на странице поиска

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1056]
## Описание проблемы

На странице расширенного поиска на мобилках появляется горизонтальный скролл, когда есть блок с выдачей по поисковому запросу.

## Как воспроизвести

1. Зайти на [странице расширенного поиска](https://doka.guide/search/) с мобильного устройства.
2. Ввести запрос. Например, «DOM».
3. Убедиться, что внизу появляется горизонтальный скролл, а часть содержимого обрезается.

## Как должно быть

Текст должен корректно переносится на новую строку и не переполнять контейнер. Мы как пользователи не должны терять возможность видеть всё содержимое без дополнительного скроллинга.

## Скриншоты

![Поисковая выдача на странице расширенного поиска по запросу «DOM». Кнопка с крестиком наполовину вылезает за экран, то же самое с выдачей.](https://user-images.githubusercontent.com/17615202/209140746-7f149a8b-81f6-45cf-9881-8f07a3daf149.jpg)

**Comment by GolubevDS** [comment]
Проблема возникает из-за строки `document.addEventListener('DOMContentLoaded',`
Текст слишком длинный и целиком не влезает на экран.
Как вариант, можно добавить в стилях `word-break: break-word;`, это обеспечит перенос не влезающих в строку слов, как на скриншоте ниже.

![doka guide_search__query=dom(iPhone 12 Pro)](https://user-images.githubusercontent.com/98118128/209343282-de957ef5-8198-4798-89e3-badf95a7b947.png)
