### ISSUE TITLE
Проблемы с контрастом у текста в блоках с кодом

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1059]
## Описание проблемы

Некоторые цвета, которые используются для подсветки кода, неконтрастны на белом фоне (#ffffff) в светлой теме.

- #3f4144;
- #50a14f;
- #e45649;
- #b76b01.

Они соотносятся 3.21:1 и не соответствуют минимальному соотношению 4.5:1.

В тёмной теме не соответствует нужному соотношению текст комментария (#6e7687) и фона (#282A2E). Сейчас соотношение 4.24:1.

## Как воспроизвести

1. Включить светлую тему и перейти на странице какого-то материала, где есть примеры кода. Например, «[Поверхностное и глубокое копирование](https://doka.guide/js/shallow-or-deep-clone/)».
2. Включить тёмную тему и перейти на страницу какого-то материала, где есть код с комментариями. Например, «[`switch`](https://doka.guide/js/switch/)».

Проверить можно руками в [WebAIM Contrast Checker](https://webaim.org/resources/contrastchecker/) или другим автоматическим способом. Например, [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html).

## Как должно быть

Минимальный контраст текста нормального размера должен соотносится с фоном 4.5:1.

**Comment by solarrust** [comment]
Цвета лежат по путям _src/styles/code-dark-theme.css_ и _src/styles/light-dark-theme.css_.

**Comment by TatianaFokina** [comment]
Тогда нужна помощь @skorobaeus, чтобы придумать, на какие цвета можно заменить проблемные. Наверное, можно даже слегка подкрутить существующие.

**Comment by skorobaeus** [comment]
Привет! Подобрала новые цвета под соотношение 4.5:1.

Вот как это будет выглядеть:

![image](https://github.com/doka-guide/platform/assets/29401439/a3498551-5f33-419f-86d4-be6f003d32a3)

Вот коды цветов:

| Цвет | Светлая | Тёмная |
|----------|----------|----------|
| Синий    | #0273DC   | #61AFEF   |
| Зелёный    | #008A1E   | #98C379   |
| Красный    | #B30000   | #FF5D5D   |
| Фиолетовый    | #A626A4   | #C678DD   |
| Жёлтый    | #A76201   | #D19A66   |
| Пунктуация    | #383A42   | #ABB2BF   |
| Комментарии    | #75767A   | #8491AA   |
| Базовый    | #282A2E   | #FFFFFF   |

**Comment by TatianaFokina** [comment]
@skorobaeus, спасибо! В ближайшее время кину ПР.
