### ISSUE TITLE
Контрастность клавиатурных сокращений в меню и на страницах материалов

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1066]
## Описание проблемы

В меню и на страницах материалов есть подсказки по тому, какие клавиатурные сокращения можно использовать на страницах, чтобы перейти к поиску, закрыть меню, перейти к следующей или предыдущей статьям. В светлой теме знак косой черты, Esc, клавиатурные сокращения для перехода к другим статьям (#d0d1d2) на белом фоне (#ffffff) соотносятся 1.52:1.

## Как воспроизвести

1. Зайти на [главную страницy](https://doka.guide) и на страницу любого материала. Например, «[`<div>`](https://doka.guide/html/div/)».
2. Проверить соотношение руками в [WebAIM Contrast Checker](https://webaim.org/resources/contrastchecker/).

## Как должно быть

Кажется, что это важная подсказка для читателей Доки, поэтому она должны отвечать минимальным требованиям контрастности — соотношению 4.5:1.

**Comment by skorobaeus** [comment]
Минимально подходящий цвет: `#757575`

![image](https://github.com/doka-guide/platform/assets/29401439/a63251d0-bd50-4cf4-bbdd-81a6104cb50e)
