### ISSUE TITLE
Починить главное выпадающее меню на мобильных устройствах

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1081]
## Описание проблемы

Никак не проскроллить меню со списком разделов Доки, когда оно полностью не умещается во вьюпорте. Когда пытаешься проскроллить его вниз, оно закрывается. В итоге видны только первые несколько пунктов из него.

## Как воспроизвести

1. Зайти на любую страницу Доки с мобильного устройства и включить ротацию экрана. Например, на [страницу раздела HTML](https://doka.guide/html/).
2. Открыть меню и попытаться его проскроллить ниже, чтобы выбрать последний пункт в списке разделов.

## Как должно быть

Дело в том, что у меню задано `position: fixed`. Так что выпадающее меню просто-напросто область, которая не скроллится сейчас ни при каких обстоятельствах.

## Видео

https://github.com/doka-guide/platform/assets/17615202/9b5712a5-b507-4b66-bc40-97a2c41cf0f5

**Comment by TatianaFokina** [comment]
Один из вариантов решения — добавить скроллбар в меню, но это не самое идеальное решение. Тогда на десктопах будет два скроллбара.

```
.nav {
    max-height: calc(100% - 50px);
    overflow-y: auto;
}
```

Другой вариант решения — JavaScript. Например, как в [этом примере](https://www.solodev.com/blog/web-design/how-to-create-on-scroll-fixed-positioning-with-css-and-js.stml).

**Comment by HellSquirrel** [comment]
Мне кажется надо просто добавить что-то типа
```

@media (orientation: landscape and max-width: ...) {
 .nav {
    // разделы в две колонки
  }
}
```

**Comment by TatianaFokina** [comment]
А ещё тут подумала, что можно же просто не делать меню `fixed` или `sticky` на мобилках. На экране всё равно мало места, а меню его почти полностью занимает в открытом состоянии. Почему бы не оставить его всегда наверху?
