### ISSUE TITLE
Приглушайте цвет шрифта в тёмной теме

### ISSUE THREAD

**Issue by rakleed** [doka-guide/platform#1082]
Для тёмной темы стоит приглушать контрастность шрифта. Сейчас он выглядит слишком ярким на тёмном фоне. Подробнее [раз](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-typography) и [два](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-images). Можно, например, задать ему прозрачность 80 %.

**Comment by TatianaFokina** [comment]
По ссылке же речь идёт не о шрифте, а о картинках. Ты имеешь в виду в ишью картинки или шрифт? Шрифт я бы не делала прозрачнее, всё же.

**Comment by rakleed** [comment]
Я почему-то вставил две одинаковые ссылки, причём обе про изображения. Но вот корректная ссылка: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-typography. И в тексте о затемнении шрифта как раз ссылаются на ранее приведённую информацию о [контрастности изображений](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-images).

**Comment by skorobaeus** [comment]
Это справедливое замечание. Перенесла его в большое ишью о типографике https://github.com/doka-guide/platform/issues/551. А это для удобства закрою.
