### ISSUE TITLE
Реализовать возможность копирования кода из сниппета

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#11]
В статьях мы приводим много сниппетов кода. Было бы круто дать возможность одной кнопкой скопировать этот код чтобы вставить потом куда-то в другое место: текстовы йредактор или песочницу. 

1. Кнопка должна появляться при наведении курсора на блок кода.
2. Код должен копироваться с соблюдением форматирования.

![image](https://user-images.githubusercontent.com/13676514/107647379-28c2ac00-6c8c-11eb-9a1a-f7c1df71b655.png)

**Comment by slitrobo** [comment]
@solarrust 

В дизайне есть вариант для этого.
Смотри справа под кодом

![image](https://user-images.githubusercontent.com/19207411/139961752-4deb4368-4cc4-4afb-a711-69bcdcf02054.png)
