### ISSUE TITLE
Перейти на `Eleventy 2.0.0`

### ISSUE THREAD

**Issue by rakleed** [doka-guide/platform#1105]
Вышел Eleventy 2.0.0: https://www.11ty.dev/blog/eleventy-v2/. Пора обновляться?

**Comment by igsekor** [comment]
Большое спасибо! :)

**Comment by loonlylokly** [comment]
В зависимостях вроде версия Eleventy уже 2.0.1. Получается ишью можно закрывать?

**Comment by TatianaFokina** [comment]
> В зависимостях вроде версия Eleventy уже 2.0.1. Получается ишью можно закрывать?

А и правда можно. Спасибо, что заметил.
