### ISSUE TITLE
Визуальное выделение нижней границы меню

### ISSUE THREAD

**Issue by Inventoris** [doka-guide/platform#1107]
Для выдвигающегося списка совпадений поиска есть визуальное выделение границ через `box-shadow`:

![image](https://user-images.githubusercontent.com/106589280/218985970-3127dc3e-6773-4596-a3c9-a5492a247df6.png)

Выделения границ нет для меню на главной, и это выглядит лаконично. Но вот то, что его нет для меню внутри разделов и статей, уже несколько странно:

![image](https://user-images.githubusercontent.com/106589280/218986797-a6cd26c1-5f2c-4208-9df0-3d52035c08b3.png)

Выглядит, на мой взгляд, как место к доработке, поскольку нижняя граница меню никак не видна и сливается с фоном страницы. Может, выделить её тоже через `box-shadow`? Будет вот так:

![image](https://user-images.githubusercontent.com/106589280/218987130-337c1eec-0682-4e4e-8dc1-3604bbec7437.png)

**Comment by Inventoris** [comment]
@skorobaeus, как на твой взгляд эта дизайнерская идея?

**Comment by skorobaeus** [comment]
Привет! 

Мы сейчас как раз в процессе перепридумывания этого меню, потому что выявили у него несколько проблем. Спасибо, что подметил этот момент с отсутствием нижней границы! Это обязательно надо учесть при выкатке нового решения, а прямо сейчас точечные фиксы я бы, наверное, не стала вносить. Призову @igsekor высказаться :)

**Comment by igsekor** [comment]
Это очень интересное и важное замечание. Спасибо, что подметил. Думаю, что надо будет также пересмотреть и способ раскрыва меню. Сейчас оно «наезжает» сверху на нижний уровень. Надо будет подумать и над этим механизмом.

**Comment by TatianaFokina** [comment]
Решено!
