### ISSUE TITLE
Меню убегает после нажатия на «Хорошо»

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#1110]
Привет! Как я этого добился:

1. Захожу на главную
2. Соглашаюсь с куками
3. Теряю меню

https://user-images.githubusercontent.com/105274/220922149-81f56be9-fb99-4b1b-8d1f-270f92213b48.MOV

Его конечно можно вернуть, если покрутить страницу, но это кажется лишним мучением

Это ишью продолжает мои мысли в #985

**Comment by TatianaFokina** [comment]
Ох ух это меню, там целый ворох проблем на всех экранах из-за него 😑

Сейчас в процессе исправления его поведения на главной. Надеюсь, что в ближайшее время часть проблем отпадёт.

Заметка на полях: проверить. что становится в фокусе с клавиатуры, когда пользователь согласился с кукиз.

**Comment by TatianaFokina** [comment]
Когда решим проблему на главной, при принятии кукиз открытое меню на главной всё равно будет закрываться при согласии с ними. Не уверена, правильное ли это поведение и как принято обрабатывать такое.

**Comment by TatianaFokina** [comment]
@igsekor поправит. Эта проблема есть на всех страницах, надо слегка улучшить скрипт.

**Comment by pepelsbey** [comment]
Ееееее 🤘
