### ISSUE TITLE
Статья предлагает почитать себя саму

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#1134]
Статья «Рынок труда» рекомендует почитать статьи «Рынок труда» и «Рынок труда». Есть опасность, что читатели могут свалиться в бесконечный цикл.

![image](https://user-images.githubusercontent.com/105274/232006325-64196458-d3bb-44de-a883-c7ae17360603.png)

**Comment by TatianaFokina** [comment]
Теперь не предлагает, так как статей больше, чем одна. Плохо конечно, что изначально релизнулись с этим.
