### ISSUE TITLE
В шрифте Graphic нет жирного курсива

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#1135]
Есть только прямой и курсив.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/105274/232007173-93514e50-d4f9-4093-ad8a-c884338c1427.png">

Поэтому браузер рисует faux bold, и это некрасиво.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/105274/232007230-1ea7d056-f42a-4bef-9368-c523558c50e3.png">

Возможно, стоит сдвинуть уровни заголовков вместо такого:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/105274/232006957-1735f7df-af2b-4d29-89b8-07fe871092cd.png">

Сейчас в контенте заголовки начинаются с h3, а потом идут фейковые. Если начать с h2, то будет ещё h3 и не будет пропускаться уровень.

**Comment by TatianaFokina** [comment]
И правда с заголовками всё странно вышло 😅 Я кинула [ПР с настоящими заголовками](https://github.com/doka-guide/landings/pull/3).

**Comment by TatianaFokina** [comment]
Заменила курсив на заголовки и исправила их иерархию.

![Страница статьи про рынок труда с букмарклетом h123. На ней правильная иерархия, есть заголовки первого, второго и третьего уровней.](https://github.com/doka-guide/platform/assets/17615202/2aa90798-9c50-4c76-8b72-44d339041688)
