### ISSUE TITLE
Что нужно исправить/улучшить в Baseline-блоке

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1143]
Давайте соберём тут то, что хотелось бы улучшить или исправить в новой фиче с Baseline. На проде можно найти, например, в [доке про `grid-area`](https://doka.guide/css/grid-area/#podskazki) (раздел с подказками).

## Исправить

- Уровень контрастности текста «Поддержка в браузерах» и ссылки «О Baseline». Сейчас соотношение 2:1 в тёмной теме.
- Возможно, стоит убрать `title` и `aria-label` у пунктов списка. `title` всё равно не показывается на пунктах списка, а `aria-label` содержит избыточную информацию, которая уже есть в скрытом спане.

## Улучшить

- Подумать про тултипы?

## Скриншоты

![image](https://github.com/doka-guide/platform/assets/17615202/7a0d74dd-5a3e-4131-91dd-49b51dd6da8a)
Блок в тёмной теме.

**Comment by skorobaeus** [comment]
- Убрать margin у первого элемента, чтобы иконки не съезжали вбок на мобильном 😅:

![image](https://github.com/doka-guide/platform/assets/29401439/a8354a3f-31ec-4822-9215-6633affc37a0)

**Comment by TatianaFokina** [comment]
Из обсуждения.

- Добавить раздел «Поддержка» / «Поддержка браузерами». Возможно, после «Подсказки», но не выводить его в боковой навигации.
- Описать новые поля в документации.
- Добавить ссылку на спецификацию.
