### ISSUE TITLE
Поправить ссылки в подвале спецпроекта «Трудоустройство»

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#1166]
Где: https://dream-job.doka.guide

1. Лицензии ведёт - https://dream-job.doka.guide/licenses/ надо - https://doka.guide/licenses/
1. О проекте - https://dream-job.doka.guide/licenses/ - надо - https://doka.guide/about/

**Comment by solarrust** [comment]
Актуально?

**Comment by igsekor** [comment]
Нет, всё работаем корректно. Забыли ишью закрыть, видимо
