### ISSUE TITLE
У шапки не должно быть анимации на прозрачность тени при затухании

### ISSUE THREAD

**Issue by denisputnov** [doka-guide/platform#1171]
предлагаю убрать анимацию измнеения прозрачности тени при затухании для шапки на сайте, в нынешней имплементации на всю шапку при быстром скролле появляется белая вспышка/

![pVLwhQXdnO](https://github.com/doka-guide/content/assets/58640700/4781d6e1-e93d-4bbe-8639-1b4a02a1198f)

**Comment by skorobaeus** [comment]
Привет! Да, выглядит достаточно странно. Я думаю, здесь трудно прийти к решению в дискуссии, и нужно на практике пробовать убирать анимацию и смотреть, станет визуально лучше. 

Пришлёшь PR? 😊

**Comment by denisputnov** [comment]
смогу посмотреть этот кейс, но не на этой неделе точно, так как занят на других активностях

**Comment by TatianaFokina** [comment]
Решено!
