### ISSUE TITLE
Много пустого места в разделах

### ISSUE THREAD

**Issue by denisputnov** [doka-guide/platform#1181]
# Проблема 
Подразделы состоят из разного количества статей, вёрстка к этому не адаптирована

![image](https://github.com/doka-guide/platform/assets/58640700/7f63e008-24dc-4f5c-9d58-b33af22eab23)

# Решение
Применить тот же приём, что на главной странице
![chrome_vmeUtOESvt](https://github.com/doka-guide/platform/assets/58640700/934c9e9f-9964-49ba-a934-c85c57deb50e)

**Comment by skorobaeus** [comment]
Привет и тут! 

Знаем об этой проблеме (#800), хотим решить :) Я закрою это ишью, как дублирующее, но всё обсуждение будет доступно по ссылкам.
