### ISSUE TITLE
Добавить выпадашки

### ISSUE THREAD

**Issue by fpetrakov** [doka-guide/platform#1213]
Привет, есть идея добавить выпадашки - [пример такой выпадашки](https://react.dev/learn/writing-markup-with-jsx#why-do-multiple-jsx-tags-need-to-be-wrapped). 

В доке есть `aside`, в него можно запихнуть более углубленную информацию, не обязательную для понимания статьи, но дело в том, что он всегда открыт и может занять много места на экране. 

Также есть элемент ответа на вопрос с собеседования, но, как я понимаю, его сейчас нельзя использовать в статье.

![image](https://github.com/doka-guide/platform/assets/34133492/9f3f0f6b-2d01-43bc-b081-245468d973df)

![image](https://github.com/doka-guide/platform/assets/34133492/794d3889-ca8b-4cea-8d89-e2355f443eb0)

![image](https://github.com/doka-guide/platform/assets/34133492/0e3f3298-58e6-4950-b3d9-abe7a8fffa53)

**Comment by skorobaeus** [comment]
Привет! Кажется, у нас есть именно такая механика, посмотри, пожалуйста, [вот здесь](https://doka.guide/js/performance/#sposoby-polucheniya-metok-i-izmereniy). Там использован вот такой код:

```
<details>
  <summary>Подробнее про метки автоматически записываемые браузером</summary>

  Для улучшения анализа производительности страницы, браузер автоматически записывает некоторые метки:
  1. `navigation` – события навигации браузера `domComplete`, `loadEventStart`, `loadEventEnd`, `redirectCount`, `domContentLoadedEventStart`, `domContentLoadedEventEnd`, `domInteractive`, `requestStart`, `responseStart`, `unloadEventEnd`, `unloadEventStart`.
  1. `resource` – содержат информацию о загрузке ресурсов сайтом. Например, можно узнать про загрузку стилей или выполнение запросов к API.
  1. `paint` – информация о рендере страницы, например, время отрисовки первого контента – `first-paint`, `first-contentful-paint`.
</details>
```

**Comment by fpetrakov** [comment]
@skorobaeus да, ты права, это то, что нужно :)
