### ISSUE TITLE
Кнопка 'Развернуть' сливается с контентом блока 'На практике - USERNAME советует'

### ISSUE THREAD

**Issue by vitya-ne** [doka-guide/platform#1232]
Светлая тема:
Кнопка 'Развернуть' имеет тень по контуру, но не отличима по цвету текста и фона:
![изображение](https://github.com/doka-guide/platform/assets/9317613/4819d59e-227a-4bfa-9b8a-768c9f7eba8b)

Тёмная тема:
Кнопка 'Развернуть' практически полностью сливается с контетном:
![изображение](https://github.com/doka-guide/platform/assets/9317613/d3452f79-a7e2-4132-96d0-0ceffdf81157)

Предложение:
Добавить контрастную обводку или котнтрастный фон, например как в заголовках:
![изображение](https://github.com/doka-guide/platform/assets/9317613/e9e30af8-02fc-4e0f-a7a2-73f0d710f846)

**Comment by skorobaeus** [comment]
В ПР #1170 добавила для кнопки рамку, такую же, как у всего блока.
