### ISSUE TITLE
Странная генерация списков контрибьютов на странице участника

### ISSUE THREAD

**Issue by skorobaeus** [doka-guide/platform#1234]
На странице участника выводятся статьи, в которые участник внёс свой вклад. В зависимости от типа вклада, статьи группируются в списки, представленные в разметке тегом `<ul>`, например: список статей, где участник автор, список статей, где участник написал совет, и т.д.

Однако в случае, есть тип вклада это ответ на вопрос на собеседовании, в разметке генерируется несколько `<ul>`.

**Где посмотреть**

На [странице Александра](https://doka.guide/people/punkmachine/) в разделе JavaScript:

![image](https://github.com/doka-guide/platform/assets/29401439/a92ceac2-fde7-4529-9592-af2521a8c9f0)

Вот разметка:

![image](https://github.com/doka-guide/platform/assets/29401439/84f67d46-949b-4773-920c-b507daf87c6d)

**В чём проблема**

Проблема в отсутствии отступа. На скриншоте выше слиплись "Функция" и "Функция", "Объект" и ".forEach", ".map" и "null". Но я думаю, что это симптом, и лечить надо первопричину: тот факт, что генерится несколько `<ul>` там, где должен генериться всего один.

**Comment by TatianaFokina** [comment]
Так как это списки статей и других типов вклада в разных разделах, списков должно быть тоже несколько. Так что с этим всё ок.

**Comment by skorobaeus** [comment]
> Так как это списки статей и других типов вклада в разных разделах, списков должно быть тоже несколько. Так что с этим всё ок.

Звучит логично, но, кажется, здесь не в этом дело. На скриншоте выше все вклады одного и того же типа — ответ на вопрос на собесе. Все в одном и том же разделе — в JS.

Давай посмотрим на две слипшиеся ссылки "Функция" на скриншоте выше. Это два ответа на два вопроса в одной статье [Функция](https://doka.guide/js/function/#na-sobesedovanii). 

В разметке эти ссылки лежат в двух разных списках `<ul>`. Причём первая ссылка лежит в `<ul>`, в котором она единственная.

Я не понимаю, как это работает.

**Comment by skorobaeus** [comment]
На странице [Саши Патлуха](https://doka.guide/people/pa7lux/) в разделе CSS также сгенерилось два `<ul>` вместо одного.

**Comment by vitya-ne** [comment]
@skorobaeus можно закрывать, да ?
