### ISSUE TITLE
`Error: Cannot find module '@11ty/eleventy-plugin-rss'` при выполнении `npm start`

### ISSUE THREAD

**Issue by corocoto** [doka-guide/platform#1241]
### Как воспроизвести:
1. Выполнить установку зависимостей `npm i`
2. Добавить `.env` файл со стандартной конфигурацией
3. Запустить команду `npm start`

### Ожидаемый результат: 
Процесс выполнится успешно

### Действительный результат:
Выполнение скрипта прервется на этапе поиска зависимости `@11ty/eleventy-plugin-rss`.

```bash
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error in your Eleventy config file '.eleventy.js'. You may need to run `npm install`. (via EleventyConfigError)
[11ty] 2. Cannot find module '@11ty/eleventy-plugin-rss'
...
[11ty] Original error stack trace: Error: Cannot find module '@11ty/eleventy-plugin-rss'
```

### Окружение:
* Версия node.js: v18.18.0,  v21.6.2
* Операционная система: Linux Mint 20.3

### Варианты решения:
1. Добавить пакет [`eleventy-plugin-rss`](https://github.com/11ty/eleventy-plugin-rss) в список зависимостей.

**Comment by corocoto** [comment]
Также хотелось бы отметить, что в последующих шагах, проблема, описанная в https://github.com/doka-guide/platform/issues/1231 также воспроизводится

**Comment by furtivite** [comment]
@corocoto привет, да, сейчас испытываем небольшие проблемы с локальной сборкой. Совсем скоро проблема будет исправлена, я или @igsekor придём в этот issue с комментариями. Спасибо, что сделал issue

**Comment by corocoto** [comment]
Ишью можно закрывать, поскольку [проблема уже исправлена](https://github.com/doka-guide/platform/commit/8f79e2a93ed8e0190ac8ae6acd374db170cceda0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R48)

**Comment by furtivite** [comment]
Спасибо, что заглянул. Рад, что всё работает
