### ISSUE TITLE
Исправить ошибку в RSS-фиде

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1245]
## Описание ошибки

Обнаружила, что не для всех материалов в фид попадает правильная ссылка. К примеру, пачка апдейтов за февраль 2024. Доки с именем автора на английском из раздела JavaScript сломались, так как в них оказалось имя автора: https://doka.guide/js/for-of/Viktar%20Nezhbart

## Наглядная демонстрация последствий

В результате к статье никак не перейти из RSS-читалки, а также у них нет превьюшек. Для примера лента в Feedly.

![image](https://github.com/doka-guide/platform/assets/17615202/3c9abfe5-d0e9-40cf-8f7f-336711d8a9b5)

**Comment by hcz** [comment]
@TatianaFokina Предлагаю поправить проблему с RSS так https://github.com/doka-guide/platform/pull/1272:
```diff
--- a/.eleventy.js
+++ b/.eleventy.js

-          post['url'] = titledLink[1].replace(/\), [А-ЯЁа-яё ,]*/, '')
+          post['url'] = titledLink[1].replace(/\/[^/]+$/, '/')
```
По созданному RSS выглядит, что это как раз решает проблему с никнеймами/именами латиницей
