### ISSUE TITLE
Бесполезная кнопка "Развернуть" в разделе "На практике"

### ISSUE THREAD

**Issue by Denis-GH** [doka-guide/platform#1274]
Иногда, когда в совете мало строк, происходит такая ситуация:

https://github.com/doka-guide/platform/assets/111387791/0889f67f-b086-48f6-b737-800225934f1d

Примеры статей: [раз](https://doka.guide/css/outline/), [два](https://doka.guide/html/iframe/) (смотрю на экране шириной 1280 px).

Считаете ли вы это проблемой, которую нужно решить? Просто я каждый раз чувствую себя обманутым 😁 когда хочу прочитать продолжение совета, а его там нет)

**Comment by TatianaFokina** [comment]
Думаю, что это проблематично с точки зрения юзабилити. Так что поддерживаю.

**Comment by vitya-ne** [comment]
@TatianaFokina, можем закрывать этот тикет ?

**Comment by vitya-ne** [comment]
@solarrust, @skorobaeus можем закрывать это ишью?

**Comment by skorobaeus** [comment]
Определённо можем :)
