### ISSUE TITLE
Поменять ссылку на документацию в рубрике "На собесе"

### ISSUE THREAD

**Issue by skorobaeus** [doka-guide/platform#1289]
Подумалось, что вот эта ссылка должна вести сюда: https://github.com/doka-guide/content/blob/main/docs/interviews.md Да и текст хорошо бы сделать более ясным.

![image](https://github.com/user-attachments/assets/bee67e52-c2a0-4603-a657-b98c90ff5bcf)

**Comment by furtivite** [comment]
Определённо согласен. Потому как логика меняется именно в этом месте.

**Comment by vitya-ne** [comment]
привет, 
я знаю как это исправить )
@skorobaeus, @furtivite  какой текст будем отображать ?

**Comment by skorobaeus** [comment]
> привет, я знаю как это исправить ) @skorobaeus, @furtivite какой текст будем отображать ?

Завела ишью, чтобы не забыть поправить и забыла поправить, конечно же))))

Давай напишем так:

```
Это вопрос без ответа. Вы можете помочь! Чтобы написать ответ, следуйте [инструкции](https://github.com/doka-guide/content/blob/main/docs/interviews.md#%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%BE%D1%82%D0%B2%D0%B5%D1%82).
```

**Comment by vitya-ne** [comment]
> Давай напишем так:

готово!
