### ISSUE TITLE
Придумать уникальные aria-label в якорях

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#135]
В #116 были введены якоря с одинаковым `'aria-label': 'Этот заголовок',`, это необходимо, чтобы не имеющий значения символ был понятен людям, которые пользуются скринридером. 

Тем не менее, возможно неправильно указывать везде одинаковый `aria-label` — нужно продумать этот момент.

**Comment by monochromer** [comment]
Скорее всего, можно закрыть.

**Comment by furtivite** [comment]
> Скорее всего, можно закрыть.

Это точно можно закрыть. Ты уже сделал. Спасибо!
