### ISSUE TITLE
Придумать способ вывода версионированного контента

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#151]
Статьи могут иметь различные версии. Необходимо придумать способ вывода контента прошлых версий.

**Comment by monochromer** [comment]
Какие реальные полезные случаи такой функциональности? Её достаточно сложно реализовать и будет большое количество "спама" - один человек добавил запятую, другой - точку с запятой и т.д.

**Comment by igsekor** [comment]
Есть уже способ, посмотреть коммиты файла. Для желающих)

**Comment by monochromer** [comment]
Так что? Закрываем?

**Comment by nlopin** [comment]
Да, договорились, что версии не нужны. Если очень нужно, то версии можно посмотреть в репозитории контента
