### ISSUE TITLE
Откорректировать размеры iframe на страницах

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#155]
Необходимо при сборке доставать высоту `<iframe>` и подставлять её в `height=""` для каждого случая, ширину установить одинаковую для всех.

**Comment by furtivite** [comment]
Возможно стоит указывать это прямо в контенте. 

Надо подумать, как сделать демки доступными на мобильном. (предложение: на мобильном делать под демкой кнопку, и по клику открывать демку в новой вкладке)

**Comment by skorobaeus** [comment]
До разделения на контент и платформу я прописывала высоту в атрибут height, подбирая её на глаз. В случае, если я ничего не указала, ставилась дефолтная высота ~150px.

Плюсы:
+ Это работает;

Минусы:
- Придётся перебрать все имеющиеся демки вручную и проставить высоту;
- Непостоянный результат в разных браузерах: где в хроме всё хорошо, там в лисе вылазит ненужный скроллбар (это лечится, но какие ещё сюрпризы могут быть, я не знаю);
- Максимально неадаптивно: уменьшается ширина > появляется скролл (тут смотря какой будет дизайн, если ширина статьи будет фиксированная, то всё в порядке, а если резина, то упс).

В идеале хочется, чтобы высота считалась автоматически по высоте `<body>`. Если делать это при сборке, снова не получается адаптивность.

---

> Надо подумать, как сделать демки доступными на мобильном. 

Пожалуй, я начну прописывать мобильные стили уже сейчас... :)

> (предложение: на мобильном делать под демкой кнопку, и по клику открывать демку в новой вкладке)

Я бы предложила сделать эту кнопку опциональной. В разделе HTML много демок, которые по размеру чуть больше кнопки и открывать их отдельно нет нужды :D https://i.gyazo.com/a44272d3851a591deee0a48c4e15d350.png

**Comment by furtivite** [comment]
Ширина установлена как 100% для всех `<iframe>` на платформе, высоты проставлены в контенте.
