### ISSUE TITLE
Пути до картинок в блоках «В работе» неправильно мапятся в разметке на проде

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#160]
А статье об API есть блок [«В работе»](https://github.com/Y-Doka/content/blob/main/js/articles/api/practice/bespoyasov.md), в котором есть ссылка на картинку:

<img width="294" alt="«Screenshot» 2021-05-30 at 12 55 38" src="https://user-images.githubusercontent.com/9102374/120099829-5998f500-c146-11eb-83ab-be52ffec34b6.png">

Локальное превью работает нормально, так как картинка лежит в папке `images` на уровень выше.

На продакшене этот путь остаётся без изменений, из-за чего картинка не подгружается:

<img width="1078" alt="«Screenshot» 2021-05-30 at 12 56 45" src="https://user-images.githubusercontent.com/9102374/120099878-864d0c80-c146-11eb-9116-d3693d12e5f8.png">

Нам, видимо, нужен какой-то трансформер для путей из подпапок внутри поста?

**Comment by nlopin** [comment]
@furtivite кажется нужен такой же трансформер, как и в #77
