### ISSUE TITLE
Переименовать организацию на Гитхабе и поправить пути

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#178]
Y-Doka — doka.guide

## Примерный план

1. Переименовать организацию в настройках Гитхаба
2. Платформа: найти и заменить все вхождения (пулреквест)
3. Контент: найти и заменить все вхождения (пулреквест)
4. Написать инструкцию, как обновить локальные ремоуты (Ноушен)

✅ Сначала нужно дождаться #177 (Прикрутить новый домен doka.guide к Netlify и сборке)

**Comment by pepelsbey** [comment]
@igsekor поможешь сформулировать набор команд, которые меняют адреса локальных ремоутов?

Было:
```sh
git remotes
> origin  git@github.com:Y-Doka/content.git (fetch)
> origin  git@github.com:Y-Doka/content.git (push)
```

Стало:
```sh
git remotes
> origin  git@github.com:doka.guide/content.git (fetch)
> origin  git@github.com:doka.guide/content.git (push)
```

**Comment by igsekor** [comment]
> @igsekor поможешь сформулировать набор команд, которые меняют адреса локальных ремоутов?

@pepelsbey конечно! Можно вот такой командой воспользоваться:

```bash

git remote set-url origin git@github.com:doka.guide/content.git

```

Только давайте проверим на всех доступных платформах. Должно работать.

**Comment by furtivite** [comment]
> Переименовать организацию в настройках Гитхаба

@pepelsbey  **doka.guide** или **doka.guide community**

**Comment by furtivite** [comment]
#177 решён.

Завёл #181 для дополнительных задач, связанных с доменом, а не с репозиториями.

**Comment by pepelsbey** [comment]
> @pepelsbey **doka.guide** или **doka.guide community**

@furtivite речь не про описание, а про URL организации. Описание обсудим отдельно.

**Comment by furtivite** [comment]
Кажется, в этом репозитории нет ничего, что упоминало бы старый репозиторий, так что как у @igsekor будет готово, можно переименовать. Жду отмашки.

**Comment by pepelsbey** [comment]
@furtivite переименование огранизации может сломать воркфлоу, так что я бы делал это вечером-ночью, чтобы не мешать авторам, ревьюерам и всем прочим :) Идеально — на выходных, но нет сил ждать!

**Comment by igsekor** [comment]
@pepelsbey @furtivite довольно много упоминаний в документации. Я сделал только для экшенов.

[PR #904 в репозитории контента](https://github.com/Y-Doka/content/pull/904)
[PR #185 в репозитории платформы](https://github.com/Y-Doka/platform/pull/185)

**Comment by furtivite** [comment]
[PR #188 в репозитории платформы](https://github.com/Y-Doka/platform/pull/188)
[PR #911 в репозитории контента](https://github.com/Y-Doka/content/pull/911)

Сделал пиары с изменениями в контентной части, про которые говорил @igsekor

**Comment by furtivite** [comment]
Надо будет за @doka-dog пройтись и бейджи поправить после переименования. Вот [issue](https://github.com/Y-Doka/badges/issues/6).

**Comment by furtivite** [comment]
Кажется, всё готово, можно закрывать?

@pepelsbey @igsekor

**Comment by igsekor** [comment]
> Кажется, всё готово, можно закрывать?
> 
> 
> 
> @pepelsbey @igsekor 

Ну вроде работает всё.

**Comment by pepelsbey** [comment]
Всем спасибо! Осталось только с почтой разобраться, но это мы отдельно.
