### ISSUE TITLE
Подключить почты и завести метрики

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#181]
@pepelsbey, кажется, пора подготовить работу на новом домене:

- завести, почту feedback@doka.guide, с алиасом feedback@y-doka.site
- поставить метрику

**Comment by pepelsbey** [comment]
Я бы обсудил почтовый адрес сегодня на созвоне, погоди :)

**Comment by furtivite** [comment]
Адрес для контактов hi@doka.guide
