### ISSUE TITLE
Обновить настройку markdown-it-anchor

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#197]
Теперь при сборке видно ошибку:

> Warning: Using deprecated markdown-it-anchor permalink option, see https://github.com/valeriangalliat/markdown-it-anchor#todo-anchor-or-file

Это было мажорное обновление библиотеки и поменялся API, к сожалению, этого не было в ченжлоге, но теперь `permalink: true` ругается и лучше бы это поправить.

Я бы не пытался чинить, а лучше взял готовый пример из документации и заменил бы наш код.

**Comment by monochromer** [comment]
Поменяли способ обработки добавления anchor для заголовков - постобработка HTML на этапе сборки
