### ISSUE TITLE
Создать плашку для статей-плейсхолдеров

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#207]
У статьи ставится тег «плейсхолдер» и должна выводиться плашка. Текст для плашки придумает @tachisis

**Comment by tachisis** [comment]
> Это незавершённая статья о N. Вы можете помочь её закончить! Почитайте [о том, как контрибьютить](#) в Доку.

> Это заготовка статьи о N. Вы можете помочь её закончить! Почитайте [о том, как контрибьютить](#) в Доку.
