### ISSUE TITLE
Время чтения статьи

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#214]
Есть потребность показывать в начале статьи сколько времени нужно чтобы её прочитать. 
В ходе обсуждения пришли к выводу, что просто показывать количество символов — абстрактно и неинформативно, писать время в минутах — все люди читают по разному, можем сильно промахнуться.
В итоге, кажется, наилучшим решением будет выводить высокоуровневые забавные фразочки в стиле «Это длинная история. Устраивайся поудобнее.» или «Изи, это будет быстро».

- [ ] Придумать механизм подсчёта символов. Возможно символы текста и символы кода считать не равноценно. Надо обсуждать.
- [ ] Придумать критерии для маленького, среднего, большого и очень большого текстов. Думаю, можно взять показатели по числу символов существующих статей и посмотреть какая у нас самая большая, а какая самая маленькая.
- [ ] Составить список фразочек, подходящих для вывода. Тут без @tachisis никак не обойтись.
- [ ] Реализовать механизм вывода условной длины статьи на сайте. 

Велком пообсуждать и уточнить статью =)

**Comment by tachisis** [comment]
Мне нравится идея, но копирайтер из меня так себе :)

Мне нравятся предложенные варианты, только мы везде нормализуем стиль в сторону чуть менее панибратского и молодежного, поэтому я бы предложила скорее

«Чтение займёт некоторое время. Устраивайтесь поудобнее»
«Чтение не займёт много времени. Раз и готово!»

**Comment by furtivite** [comment]
@solarrust, @tachisis, кажется, у нас уже есть такая плашка. Можем ли закрыть?

**Comment by monochromer** [comment]
> Составить список фразочек, подходящих для вывода. 

Почему решили не делать?
