### ISSUE TITLE
Сделать валидатор для HTML

### ISSUE THREAD

**Issue by igsekor** [doka-guide/platform#217]
Предлагается собирать платформу с контентом, а потом валидировать с помощью экшенов.

Из вариантов:
1. Пакет `node-w3c-validator` и обвязку из Java как [тут](https://github.com/web-standards-ru/web-standards.ru/blob/main/.github/workflows/html.yml)
2. Готовый экшен [HTML5 Validator Action](https://github.com/marketplace/actions/html5-validator)
3. Другие способы, которые можно обсудить 😇

@pepelsbey @nlopin @furtivite что скажите?

**Comment by pepelsbey** [comment]
Я бы проверил, какой из валидаторов а) быстрее отрабатывает и б) удобнее для настройки, чтобы фильтровать ошибки или настраивать файлы на вход.

**Comment by igsekor** [comment]
> Я бы проверил, какой из валидаторов а) быстрее отрабатывает и б) удобнее для настройки, чтобы фильтровать ошибки или настраивать файлы на вход.

Займусь ;)

**Comment by monochromer** [comment]
Попробовал валидатор [linthtml](https://github.com/linthtml/linthtml).

Наткнулся на следующие проблемы:
1. Падает с ошибкой переполнения памяти при линтинге более 500 файлов. При 300 ещё работал.
2. Разное поведение при запуске как npm-скрипта `"linthtml": "linthtml dist/**/*.html"` и через npx: `npx linthtml dist/**/*.html`.
