### ISSUE TITLE
Некорректно работает вывод даты последнего редактирования статьи 

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#232]
Дата считается от последней генерации сайта

[Пример на сайте](https://doka.guide/css/animation-duration/)
[Пример на ГХ](https://github.com/doka-guide/content/tree/main/css/animation-duration)

<img width="1291" alt="Снимок экрана 2021-07-02 в 11 58 35" src="https://user-images.githubusercontent.com/50330458/124249742-d5fb6b00-db2c-11eb-8a1e-7a31ae62b17b.png">
<img width="665" alt="Снимок экрана 2021-07-02 в 11 58 29" src="https://user-images.githubusercontent.com/50330458/124249751-d98ef200-db2c-11eb-8361-12cd348803d9.png">

**Comment by monochromer** [comment]
Попробую распутать клубок:

1. Eleventy по умолчанию заносит в `page.date` дату создания файла, а не его модификации. Можно сделать вычисляемое поле с датой последних изменений посредством стандартного модуля Node.js.
2. Ещё момент: дата изменений файла не обязательно должна совпадать с датой git-коммита.
3. Этапы работы в CI/CD могут "трогать" файлы, из-за чего у них будет меняться дата изменений.

Поэтому некоторые пытаются нормализовать даты, вот даже есть [github action](https://github.com/marketplace/actions/git-restore-mtime).

Я не спец по ОС, может здесь Игорь @igsekor  что подскажет.

**Comment by igsekor** [comment]
@monochromer прав, дело именно в этом. Сборка происходит в экшенах, поэтому дата проставляется неправильная. Файлы создаются в момент чекаута.

Ещё есть вопросы с Time Zone, которые текущая версия не учитывает, кажется.

GitHub API тоже не очень подходит для работы на клиенте. Есть [ограничения](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) на количество запросов. При большом количестве пользователей будут проблемы.

Решения:
1. Можно хранить дату изменения в самом файле (самый простой для Eleventy способ). Тут можно вручную или автоматизировать подстановку даты в материалы автоматически на этапе пиара.
2. Можно хранить время обновления материалов в специальном файле, который на этапе пиара можно обновлять для файлов контента из пиара.
3. Можно обращаться GitHub API на этапе сборки, проверять дату изменения статей по коммитам.
4. Можно сделать бэкенд.

**Comment by furtivite** [comment]
Мне кажется, что это удобный способ (хранить где-то в структуре), но было бы классно, чтобы дата туда подставлялась как-то автоматически. Например, завести Action, который будет проставлять дату в файл, когда он замёржен. Если изменений в файле нет, то Action дату не обновляет.

Возможно, было бы круто, хранить эту дату не в самом файле, а в том самом оглавлении, чтобы в глаза не бросалась и у авторов не чесались руки дату поправить, или поставить, и вообще они о дате не думали.

**Comment by nlopin** [comment]
Я попытался осознать решения выше, но не понял. 

Сейчас относительная дата изменения генерируется статически при сборке, по сути это отрезок от даты редактирования статьи и текущей даты в браузере пользователя. Этот отрезок не статичный, у него правый конец (текущая дата) всё время ползёт вправо. В этом случае статическая генерация не подойдёт и нужно получать это время на клиенте. 

Где я ошибаюсь?

**Comment by igsekor** [comment]
@nlopin проблема не в отображении. Проблема в самой генерации. На клиенте надо будет показывать правильный промежуток, но сначала надо получить правильную дату при генерации.

Мне кажется интересной эта идея «Последний раз редактировалось в июле 2021».

@furtivite @monochromer @pepelsbey @solarrust @tachisis что скажите?

**Comment by furtivite** [comment]
> «Последний раз редактировалось в июле 2021»

У нас статьи заливаются пачками по месяцам, согласно планированию. Кажется, надо сделать выборку чуть точнее. Вопрос в том, что если мы сможем брать дату редактирования из GitHub API, например, то можем сделать и точнее. Как мне кажется.

**Comment by igsekor** [comment]
> > «Последний раз редактировалось в июле 2021»
> 
> @igsekor у нас статьи заливаются пачками по месяцам, согласно планированию. Кажется, надо сделать выборку чуть точнее. Вопрос в том, что если мы сможем брать дату редактирования из GitHub API, например, то можем сделать и точнее. Как мне кажется.

Надо изучить подробнее. Сделаю тогда PR с экшеном или скриптом (что больше подойдёт), если все поддерживают идею. Само представление тогда можно затюнить после.

**Comment by monochromer** [comment]
Я сейчас работаю над скриптом для Github Action. 

Суть такая: используя команды git, достаем список файлов последнего коммита, фильтруем те, что находятся в папке статьи. В корне статьи создаем/обновляем файл `index.11tydata.json` с полем `updatedAt`, также на уровне платформы должна быть дата-fallback, так как не у всех сразу появится поле `updatedAt`.

Плюсы решения: не нужно править поля в самом md-файле, можно использовать в будущем для других динамически генерируемых полей.

**Comment by monochromer** [comment]
Еще нужно заменить правила относительного форматирования, так как вид "Отредактировано: 147 дней назад" мало информативен. Если разница составила больше суток, то просто оставлять полную дату, например "5 июля 2021"

**Comment by furtivite** [comment]
> Еще нужно заменить правила относительного форматирования, так как вид "Отредактировано: 147 дней назад" мало информативен. Если разница составила больше суток, то просто оставлять полную дату, например "5 июля 2021"

А если «Отредактировано n месяцев назад» и «Отредактировано больше года назад»? Без более точной даты, не уверен, что она прям очень нужна.

**Comment by furtivite** [comment]
Задача связана с #206

**Comment by pepelsbey** [comment]
> Еще нужно заменить правила относительного форматирования

@monochromer думаю можно поставить задачу @tachisis продумать формулировки, которые были бы полезны читателям.

**Comment by monochromer** [comment]
Создал PR'ы:
https://github.com/doka-guide/platform/pull/239
https://github.com/doka-guide/content/pull/1097

**Comment by monochromer** [comment]
Еще нужно подумать, какую дату взять как fallback, когда полей _createdAt_ и _updatedAt_ нет. Я пока поставил 9.02.2021 - дату первых коммитов в новый репо платформы.

**Comment by furtivite** [comment]
> Еще нужно подумать, какую дату взять как fallback, когда полей createdAt и updatedAt нет. Я пока поставил 9.02.2021 - дату первых коммитов в новый репо платформы.

Вот тут стоит подумать, у нас y-doka.site [в старом репо](https://github.com/doka-guide/y-doka.site/) запущен 27.09.2020, а первые материалы были написаны ещё в 2019, но точную дату не подскажу пока что. Надо выбрать дату.

**Comment by pepelsbey** [comment]
Вот не уверен, стоит ли считать даты из старого репозитория. Ценности в этом не очень много. Давайте может и правда фолбэком будет разделение на платформу и контент?
