### ISSUE TITLE
Прозрачная инфографика

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#240]
У нас есть инфографика в статьях с прозрачным фоном. Например, вот такая:

![01_v01](https://user-images.githubusercontent.com/50330458/124483133-ab224880-ddb2-11eb-8175-ccfc773cffa9.png)

Планировалось, что фоновый цвет будет подкладываться на стороне платформы, чтобы можно было менять фоновый цвет в зависимости от контента: разделы HTML, CSS, JS и так далее —  плюс управлять фоном в зависимости от темы сайта: тёмной-светлой.

**Comment by furtivite** [comment]
@monochromer думаю, что тут можно было бы сделать div-обёртку, либо доделать #3 и присваивать класс, который бы в зависимости от папки-раздела подставлял нужный цвет. Что думаешь?

**Comment by monochromer** [comment]
Пока трудно что-либо говорить. Нужен дизайн, чтобы все систематизировать, а не смотреть мелкие части.

Так была мысль преобразовывать контент статей (добавлять классы, менять обертки и пр.) с помощью библиотек типа JSDOM вместо всяких регулярок

**Comment by furtivite** [comment]
@monochromer окей, подобные картинки тогда пока отложим до введения нового дизайна. Надо просто такую потребность в голове держать, на момент создания. Спасибо 😉
