### ISSUE TITLE
Автоматический фичеринг статей

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#248]
На основании того, какие статьи пользователь уже прочитал выдавать ему подборку _возможно_ интересных статей. 
Это можно делать на основании дерева раздела — выдавать статьи из этого же или соседних разделов.
Или делать на основании ссылок внутри статьи — показывать те статьи, на которые ссылаемся в тексте. 
А лучше и то и другое =)

**Comment by pepelsbey** [comment]
# Вариант фичеринга №1

Брать порядок следования статьи в категории и предлагать предыдущую и следующю статьи

```
# animation-duration

<– animation-name  |  animation-iteration-count –>
```

**Comment by pepelsbey** [comment]
# Вариант фичеринга №2

Автоматически собирать упомянутые в статье внутренние ссылки и давать их как продолжение для чтения.

**Comment by monochromer** [comment]
Наверно, это issue можно закрыть как дубликат https://github.com/doka-guide/platform/issues/753.
