### ISSUE TITLE
Проблема с NODE_ENV на Windows

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#288]
На Windows-машинах при попытке запуска сборки командой `npm start` возникает ошибка:

```bash
"NODE_ENV" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `NODE_ENV=development eleventy --serve --quiet`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by furtivite** [comment]
Это можно решить несколькими способами:

1. Создать отдельную команду для Windows-пользователей 

было:

```js
"start": "NODE_ENV=development eleventy --serve --quiet",
```

стало:

```js
"start": "NODE_ENV=development eleventy --serve --quiet",
"startw": "SET NODE_ENV=development eleventy --serve --quiet",
```

и прописать в документации, что Windows-пользователям надо запускать платформу как `npm startw`

1. Просить в документации добавлять в команду `start` слово `SET` вручную

1. Протестировать как работает [решение win-node-env](https://github.com/laggingreflex/win-node-env), и если оно работает хорошо, рекомендовать windows-пользователям устанавливать дополнительно эту зависимость

1. Перейти на [cross-env](https://www.npmjs.com/package/cross-env)?

**Comment by lenaryan** [comment]
У меня проблем никаких, всё запускается. Но! Какое-то время назад на другом проекте как раз была проблема с NODE_ENV, лечилось установкой cross-env. Потом у меня обновилась винда - и проблема перестала появляться, и всё теперь прекрасно работает через NODE_ENV.

**Comment by skorobaeus** [comment]
Мне нравится второй вариант, потому что сохраняется привычная команда для запуска. Но первый, наверное, практичнее.

**Comment by furtivite** [comment]
13.08.2021 приняли решение о переходе на cross-env
