### ISSUE TITLE
Удалять содержимое dist при пересборке

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#298]
Иногда при переключении с ветку на ветку, или из build в dev в папке dist сохраняются артефакты, которые влияют на вёрстку. Их стоит удалять при пересборке.

**Comment by monochromer** [comment]
В режиме разработки сервер browser-sync смотрит в приоритете на папки внутри _src_ и _node_modules_ и затем только на _dist_. Так что проблем не должно быть. Это issue закрою, но если возникнут проблемы, то можно будет сделать пару задач для gulp по удалению всей папки dist или только некоторых артефактов.
