### ISSUE TITLE
Описание работы меню и поиска

### ISSUE THREAD

**Issue by monochromer** [doka-guide/platform#299]
Необходимо добавить описание работы меню и поиска в плане UI/UX

**Comment by nlopin** [comment]
Я предлагаю повесить какую-то одну функцию на этот список. 

Если это будет и переход в индекс, и фильтр, то непонятно, как пользователь узнает об этом. Я убеждён, что даже если мы реализуем обе возможности, то использоваться будет только одна, которая работает «в лоб». Так что мы только зря время потратим.

**Comment by nlopin** [comment]
Давайте еще сделаем, чтобы у поля поиска был автофокус при старте или мы бы начинали искать автоматически, когда фокус никуда не установлен. Кажется при этом только не стоит показывать список разделов.

Я вспоминаю юзкейс, когда я пытался воспользоваться докой как справочником при вёрстке и было очень неудобно постоянно кликать в поле поиска.

**Comment by nlopin** [comment]
Сейчас поиск начинает работать после того, как пользователь ввёл три символа и больше. Из-за этого невозможно найти короткие HTML-теги `a`, `br`, `p` и так далее.

Нужно решить, как мы обрабатываем такие случаи. Кажется базовом решением будет хранить словарь коротких тегов. Будем обсуждать здесь или отдельную задачу заведём?
