### ISSUE TITLE
Преобразование картинок

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#3]
Для уменьшения веса и большей поддержки картинок, а так же для оборачивания их в тег `<figure>` (чтобы иметь возможность добавить подпись при необходимости), предлагается использовать [плагин Image из eleventy](https://www.11ty.dev/docs/plugins/image/). 

Пример работы плагина можно посмотреть [в репозитории](https://github.com/furtivite/11ty-picture). 

Возможные проблемы, которые надо исследовать:
- приём `src` при сборке из другого репозитория
- работа с `*.gif` и `*.svg` без преобразования в `*.webp` и `*.jpeg`
- работа с `*.png` там где необходим прозрачный фон

P.S. Я помню, что от `*.gif` планировали отказаться.

**Comment by furtivite** [comment]
Дополнительно нужно исследовать возможности
- Добавлять классы к картинкам
- Добавлять несколько картинок, например @2x или в виде мобильных версий.

**Comment by furtivite** [comment]
Дополнительное условие. В репозитории контент, картинки должны оставаться в формате `![alt](url)`, чтобы их можно было предпосмотреть без участия платформы.

**Comment by pepelsbey** [comment]
> Дополнительное условие. В репозитории контент, картинки должны оставаться в формате `![alt](url)`, чтобы их можно было предпосмотреть без участия платформы.

Да, это важно.
