### ISSUE TITLE
Прокрутка до якоря в статье

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#309]
При клике на якорь в боковой панели, происходит прокручивание контента до соответствующего заголовка. При этом заголовок скрывается за "шапкой" сайта. 

Сейчас:

![Заголовок скрывается под шапкой](https://user-images.githubusercontent.com/50330458/131492458-b4b8fc81-2e17-4787-be11-233b810c6dd9.png)

Улучшить:

Сделать фиксированный отступ сверху, чтобы нужный заголовок не прятался под шапку.

![Заголовок не скрывается](https://user-images.githubusercontent.com/50330458/131492755-9659d804-8b88-4215-aab6-cc8b0bccbd95.png)

**Comment by pepelsbey** [comment]
Заголовкам нужно добавить `scroll-margin-top: [высота шапки с запасом]px`

**Comment by furtivite** [comment]
Закрыто из-за #410
