### ISSUE TITLE
Положение обложки на десктопе

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#310]
Сейчас обложка на десктопе ориентирована по грид-сетке в классе `.article__header`, из-за этого она смещается относительно центра, потому что в обложке (самой картинке) есть отступы. 

Пример ([гайд по флексбоксу](https://doka.guide/css/flexbox-guide/)):

![Снимок экрана 2021-08-31 141533](https://user-images.githubusercontent.com/50330458/131494149-e7475bdf-1799-4b84-81e5-29106b6da08a.png)

Необходимо сдвинуть картинку относительно заголовка таким образом, чтобы изображение стартовало вместе с заголовком, как получено в дизайне. 

![Снимок экрана 2021-08-31 141550](https://user-images.githubusercontent.com/50330458/131494377-40142e2f-ae65-4c76-8fcc-47f3b71da9ab.png)

**Comment by monochromer** [comment]
Предлагаю преобразовать это issue в обсуждение  (это [issue](https://github.com/doka-guide/platform/issues/368) можно закрыть) о том, как должны отображаться обложки и, как следствие, какие у них должны быть размеры и пр.
