### ISSUE TITLE
Сломался Docker Deploy

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#314]
После мержа #313 [сломался Docker Deploy](https://github.com/doka-guide/platform/runs/3481188110?check_suite_focus=true)

```
/usr/bin/docker buildx build --tag dokaguide/platform:latest --iidfile /tmp/docker-build-push-xQKDv0/iidfile --metadata-file /tmp/docker-build-push-xQKDv0/metadata-file --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-xQKDv0/tmp-2219-RLCL1gMdCVK1 --push https://github.com/doka-guide/platform.git#7b6ce8c4f855b88a6ab64a1ffd0d72735d750fe7
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 31.3s done
#1 creating container buildx_buildkit_builder-f449bd7d-b26f-498b-8aac-7dd65559ea7a0 done
#1 ERROR: Error response from daemon: No such image: moby/buildkit:buildx-stable-1
------
 > [internal] booting buildkit:
------
error: Error response from daemon: No such image: moby/buildkit:buildx-stable-1
Error: buildx failed with: error: Error response from daemon: No such image: moby/buildkit:buildx-stable-1
```

**Comment by igsekor** [comment]
> После мержа #313 [сломался Docker Deploy](https://github.com/doka-guide/platform/runs/3481188110?check_suite_focus=true)
> 
> 
> 
> ```
> 
> /usr/bin/docker buildx build --tag dokaguide/platform:latest --iidfile /tmp/docker-build-push-xQKDv0/iidfile --metadata-file /tmp/docker-build-push-xQKDv0/metadata-file --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-xQKDv0/tmp-2219-RLCL1gMdCVK1 --push https://github.com/doka-guide/platform.git#7b6ce8c4f855b88a6ab64a1ffd0d72735d750fe7
> 
> #1 [internal] booting buildkit
> 
> #1 pulling image moby/buildkit:buildx-stable-1
> 
> #1 pulling image moby/buildkit:buildx-stable-1 31.3s done
> 
> #1 creating container buildx_buildkit_builder-f449bd7d-b26f-498b-8aac-7dd65559ea7a0 done
> 
> #1 ERROR: Error response from daemon: No such image: moby/buildkit:buildx-stable-1
> 
> ------
> 
>  > [internal] booting buildkit:
> 
> ------
> 
> error: Error response from daemon: No such image: moby/buildkit:buildx-stable-1
> 
> Error: buildx failed with: error: Error response from daemon: No such image: moby/buildkit:buildx-stable-1
> 
> ```
> 
> 

Всё в порядке. Обычная ошибка с доступом со стороны серверов GitHub. При повторном запуске экшен отработал успешно. Закрываю.
