### ISSUE TITLE
Удалить зависимость шрифтов от типа материала в оглавлении

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#326]
Сейчас в оглавлении есть зависимость шрифтов от типа материала: дока - моноширинный, статьи - обычный.

![photo_2021-09-07_12-28-29](https://user-images.githubusercontent.com/50330458/132322341-6a062ae5-8c56-47ef-9f57-6d7971fed37c.jpg)

Нужно ввести бэктики в заголовки и рендерить их. Плюс удалить зависимость от типа материала. 

У нас не всегда в доках только код, иногда и текст.

**Comment by pepelsbey** [comment]
То есть:

```
title: "Свойство `font-weight`"
title: "`font-weight`"
```

Но это только если нужно иметь код в заголовках. Нужно свериться с макетом.

**Comment by monochromer** [comment]
Здесь заголовок "Комментарии" набран моноширинным шрифтом

![image](https://user-images.githubusercontent.com/6412192/132328913-baf4657b-3e55-46a1-92e2-6f961657cca2.png)
