### ISSUE TITLE
Удалить прокрутку страницы

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#329]
При переходе на страницу [Работа с формами](https://doka.guide/js/deal-with-forms/) страница автоматически прокручивается до `<iframe>` с полем, где находится курсор. Это мешает чтению статьи. Нужно придумать решение, при котором авторы смогут встраивать в статью формы, но при этом положение курсора не влияло на прокрутку страницы.

**Comment by monochromer** [comment]
В зависимости от того, что должно быть в фреймах, можно добавлять атрибуты `sandbox` и `allow` с нужными feature-policy.

**Comment by pepelsbey** [comment]
Это всего одна демка и я сейчас кину ПР, который добавляет атрибут `sandbox`, а там посмотрим, нужно ли это нам на всех формах. Задачу я бы переформулировал в ключе автоматизации добавления этого атрибута.

**Comment by pepelsbey** [comment]
[Пофиксил здесь](https://github.com/doka-guide/content/pull/1479)
