### ISSUE TITLE
Вывод блоков _pre_ с сохранением форматирования 

### ISSUE THREAD

**Issue by monochromer** [doka-guide/platform#330]
Вопрос: нужно ли выводить блоки с сохранением форматирования текста, кроме блоков с кодом, конфигами, выводами в консоль?

Если да, то предлагаю пару вариантов:

- Для кода использовать тройные backtick'и, для остального - html-тег _pre_
  ````md

  ```
  server {
    location / {}
  }
  ```

  <pre>
  Села муха на варенье
  Вот и всё... )
  </pre>
  ````

- Для кода - backtick'и c явными указанием языка, для остального - пустые backtick'и
  ````md

  ```nginx
  server {
    location / {}
  }
  ```

  ```
  Села муха на варенье
  Вот и всё... )
  ```
  ````

**Comment by pepelsbey** [comment]
Думаю второй вариант более привычный и уже используется в контенте: когда это не язык, а абстрактный код — язык не указывается. Хотелось бы избежать тегов в маркдауне, если можно обойтись без них.

**Comment by monochromer** [comment]
Тогда в контенте надо везде проставить имена для языков и конфигов

**Comment by furtivite** [comment]
> Тогда в контенте надо везде проставить имена для языков и конфигов

У нас на данный момент без указания языка, но через тройные бэктики у нас есть несколько использований, вот список:

- в статье про [css/content](https://github.com/doka-guide/content/blob/main/css/content/index.md) - фраза про мушкетёров

на рендере выводится сейчас как 

```html
<pre><code class="code font-theme font-theme--code">«Вспомните, как говорили мушкетёры: „Один за всех, все за одного!”»
</code></pre>
```

- в практиках в [css/letter-spacing](https://github.com/doka-guide/content/blob/main/css/letter-spacing/practice/solarrust.md)

```html
<pre><code>x * z / 1000 = y
</code></pre>
```

- в практиках [css/line-height](https://github.com/doka-guide/content/blob/main/css/line-height/practice/solarrust.md)}
- в тексте дважды [js/array.forEach](https://github.com/doka-guide/content/blob/main/js/array-foreach/index.md), та же статья [в практиках](https://github.com/doka-guide/content/blob/main/js/array-foreach/practice/windrushfarer.md) (тут, я бы заменил обычный тройной бэктик, на бэктик с указанием bash, в качестве языка, потому что это вывод терминала, но тут без @nlopin  и @tachisis не решить)
- в тексте дважды [js/асинхронность](https://github.com/doka-guide/content/tree/main/js/async-in-js) (тут тоже вывод терминала)
- в тексте [js/хранение данных в браузере](https://github.com/doka-guide/content/blob/main/js/browsers-storages/index.md) (терминал)
- в тексте [js/стиль кода](https://github.com/doka-guide/content/blob/main/js/code-style/index.md) (консоль)
- в тексте дважды [js/работа с формами](https://github.com/doka-guide/content/blob/main/js/deal-with-forms/index.md) (консоль)
- многократно в тексте [js/как браузер рисует страницы](https://github.com/doka-guide/content/blob/main/js/how-the-browser-creates-pages/index.md) (тут много ASCII-графики, надо понять как её вообще выводить и выделять) 

например:

```html
<pre><code>              html
                |
              body
        (font-size: 14px)
        ________|________
        |               |
      p.text           img
    (color: red)  (max-width: 100%)
        |
  "Hello world"
</code></pre>
```
- многократно в тексте [js/разработка через тестирование (TDD)](https://github.com/doka-guide/content/blob/main/js/tdd/index.md) (консоль)
- мнокократно в тексте [tools/веб-сервер Apache](https://github.com/doka-guide/content/blob/main/tools/apache-web-server/index.md) (тут конфигурационные файлы, и было бы классно, кмк, выводить их как-то более оформленно, вопрос к @nlopin и @igsekor)
- в практиках [tools/системы сборки](https://github.com/doka-guide/content/blob/main/tools/bundlers/index.md) (тоже конфигурационый файл)
- в практиках [tools/мультиконтейнерное приложение и Docker Compose](https://github.com/doka-guide/content/blob/main/tools/docker-compose/practice/igsekor.md) (конфиг)
- мнокократно в тексте [tools/управление данными в Docker](https://github.com/doka-guide/content/blob/main/tools/docker-data-management/index.md) (конфиг)
- в практиках [tools/Git CLI — минимум для работы](https://github.com/doka-guide/content/blob/main/tools/git-cli/practice/igorkamyshev.md) (тоже конфигурационый файл)
- мнокократно в тексте [tools/веб-сервер Nginx
](https://github.com/doka-guide/content/blob/main/tools/nginx-web-server/index.md) (конфиг?)
- мнокократно в тексте [tools/веб-сервер](https://github.com/doka-guide/content/blob/main/tools/web-server/index.md (консоль?)

--- 

т.е. кажется, надо вначале придумать, как мы выводим вывод консоли, как ASCII, как конфиги и обычные выделения преформатированного текста, а затем перевести в код.
