### ISSUE TITLE
На страницах-сборщиках не указан title

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#337]
У нас есть страницы-сборщики:

- [HTML](https://doka.guide/html/) собирается из [файла](https://github.com/doka-guide/content/blob/main/html/index.md)
- [CSS](https://doka.guide/css/) собирается из [файла](https://github.com/doka-guide/content/blob/main/css/index.md)
- [JS](https://doka.guide/js/) собирается из [файла](https://github.com/doka-guide/content/blob/main/js/index.md)
- [Инструменты](https://doka.guide/tools/) собирается из [файла](https://github.com/doka-guide/content/blob/main/tools/index.md)

У страниц пустой `<title></title>`. 

Предлагается:

1. Добавить в контент файлов поле `title` перед первым `name`, чтобы он выводился

или

2. Изменить шаблон так, чтобы при отсутствии `title` проверялось наличие самого верхнего поля `name` и выводилось бы оно?

**Comment by nlopin** [comment]
@furtivite Вадим создал похожий тикет (#348). Закроем этот?
