### ISSUE TITLE
Вывести в индексе категорию со статьями без категорий

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#346]
В конце, даже если их нет в файле индекса. Своеобразная защита от невнимательности.

Рабочее название категории «Остальные».

Решили на звонке, что если материала нет в индексе, то это не должно прятать какие-то статьи раздела. Сортировка по алфавиту должна просто сортировать, а не показывать больше.

**Comment by nlopin** [comment]
@pepelsbey мы проговаривали, что мы можем оставлять статью вне содержания, если хотим выпустить несколько одновременно. Мне ок и так, и так, но хочу понять, почему решения меняются

**Comment by pepelsbey** [comment]
> @pepelsbey мы проговаривали, что мы можем оставлять статью вне содержания, если хотим выпустить несколько одновременно. Мне ок и так, и так, но хочу понять, почему решения меняются

Хм, я плохо помню зачем оставлять статью вне оглавления. Можно освежить договорённости.

**Comment by monochromer** [comment]
В фильтре по алфавиту выводятся все статьи категории

**Comment by pepelsbey** [comment]
@monochromer обновил описание задачи: решили, что это важно на вчерашнем звонке.
