### ISSUE TITLE
Обработать бэктики в названиях статей

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#347]
В заголовках начинают появляться бэктики, чтобы можно было выводить и текст, и код:

```yaml
title: "Мой любимый тег `<blink>`"
```

Нужно выводить их там, где можно вывести и не выводить там, где нельзя:

```html
<title>
  Мой любимый тег <blink>
</title>
…
<h1>
  Мой любимый тег <code>&lt;blink&gt;</code>
</h1>
```

**Comment by furtivite** [comment]
Пример такой статьи [`<br>` - да или нет](https://doka.guide/html/br-pros-cons/)
