### ISSUE TITLE
Устройство блоков кода и копирование

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#365]
Сейчас блок кода устроен вот так:

```html
<div class="code-block font-theme font-theme--code" tabindex="0">
  <table class="code-block__content" aria-hidden="true">
    <tbody>
      <tr class="code-block__line">
        <th class="code-block__line-number"></th>
        <td class="code-block__line-content">LINE 1</td>
      </tr>
      <tr class="code-block__line">
        <th class="code-block__line-number"></th>
        <td class="code-block__line-content">LINE 2</td>
      </tr>
    </tbody>
  </table>
  <pre class="code-block__origin visually-hidden" data-lang="js">
    <code class="language-js">LINE 1
LINE 2</code>
  </pre>
</div>
```

То есть код повторяется два раза, одна часть прячется, другая показывается. А для строк используется таблица. Уфф.

И если скопировать такой код со страницы, то получается не очень.

Оригинальный код:

```js
if (условие) {
  console.log("выполнюсь, если условие истинное")
}
```

Chrome: иногда копируется таб.

```js
	if (условие) {
  console.log("выполнюсь, если условие истинное")
}
```

Firefox: добавляются лишние строки и табы

```js
	if (условие) {

	  console.log("выполнюсь, если условие истинное")

	}
```

Safari: копируется два исходника.

```js
if (условие) {
  console.log("выполнюсь, если условие истинное")
}
if (условие) { console.log("выполнюсь, если условие истинное") }
```

Я предлагаю сделать блок кода **сильно** проще:

```html
<pre>
  <code>LINE 1</code>
  <code>LINE 2</code>
</pre>
```

[Пример реализации](https://pepelsbey.github.io/playground/tabs-spaces/).

В таком случае _код кода_ становися сильно проще и он без проблем копируется. Насколько я знаю, Highlight.js умеет разбивать код на произвольные строки.

**Comment by monochromer** [comment]
Safari не поддерживает `::marker`

**Comment by pepelsbey** [comment]
> Safari не поддерживает `::marker`

Ну да, придётся с псевдоэлементами, но кажется это не принципиально.
