### ISSUE TITLE
Ссылка с кода неотличима от кода

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#366]
Один из этих примеров кода `if...else` — это ссылка, а другой — нет.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/105274/133524685-7fb9dd03-179d-4b7e-9c53-fa05b27f89ce.png">

К сожалению, разницу не заметить, только если не подвести курсор. На тачах шансов понять нет вообще.

Предлагаю подчеркнуть текст кода внутри, чтобы было понятно, что это ссылка. Как именно — над проверить, но сделать это нужно обязательно, иноаче по таким ссылкам не будут ходить.

**Comment by monochromer** [comment]
Сейчас ссылки с блоками кода более-менее видно, поэтому issue закрою
![image](https://user-images.githubusercontent.com/6412192/143400547-4327b335-257f-48ac-88c7-a07c19067df0.png)
