### ISSUE TITLE
Картинки пережимаются слишком сильно

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#372]
[В статье про Debounce](https://doka.guide/js/debounce/) были загружены картинки в высоком качестве, после сборки картинки были сильно пережаты. Нужно уменьшить степень сжатия или не пережимать десктоп от дизайнеров. 

Было
![](https://user-images.githubusercontent.com/50330458/133618055-0749dbe1-c283-48a8-ac81-c6099ae67c35.png)

Стало
![](https://doka.guide/js/debounce/images/not-debounced-600w.webp)

**Comment by skorobaeus** [comment]
Если я правильно поняла, сейчас из исходной картинки делается три сжатых версии: 300 пикселей по ширине, 600 и 1200.

Картинки выше исходно были 950 по ширине, вот их и уменьшило так сильно. Мне кажется, между 600 и 1200 очень большой разлёт, может, возможно добавить ещё версию шириной 900? Или оставлять версию картинки с исходным размером..?

В любом случае, какое бы решение ни приняли, дайте, пожалуйста, знать, в каком размере изображения встраиваются на сайт, чтобы мы могли правильно их готовить ✌

**Comment by monochromer** [comment]
> В любом случае, какое бы решение ни приняли, дайте, пожалуйста, знать, в каком размере изображения встраиваются на сайт, чтобы мы могли правильно их готовить ✌

Судя по макетам, максимальный размер картинки может быть 1223px. Но, наверно, лучше брать с запасом - 1240px или даже 1400px. И умножить на 2 для поддержки retina-экранов.
