### ISSUE TITLE
Редирект y-doka.site -> doka.guide

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#389]
У нас есть домен y-doka.site, он продлён на год (до сентября 2022), чтобы пользователи, которые сохранили Доку в закладках не потеряли его после окончания домена и до запуска. 

Нужно придумать, как максимально безболезненно перевести пользователей на новый домен, чтобы они смогли обновить закладки и искали нас уже по новому адресу.

**Comment by pepelsbey** [comment]
Есть два варианта:

1. Просто редиректить старый домен на новый, на уровне DNS (очень просто)
2. Редиректить с сохранением путей (сложнее)

Чтобы сохранять пути, нужно составить карту страниц на старом сайте и сопоставить её с новым. Думаю, что подавляющее большинство страниц можно сделать автоматически, но часть нужно отлавливать руками: мы много переименовывали.

Также важно сделать все редиректы правильно с точки зрения поисковиков, чтобы они склеили домены и стали ходить на новый сайт по старым ссылкам из индексов.

Насколько я помню, можно сделать редиректы на уровне Netlify, раз мы пока не переезжаем.

@igsekor твой ход, кажется :)

**Comment by pepelsbey** [comment]
Моё мнение: я бы просто поставил редирект старого домена и не парился. Мы потеряем только тех, кто поставил закладки. На мой взгляд, это не стоит возни. С точки зрения поисковиков тоже не так важно: на старую Доку мало ссылаются (если ссылаются вообще), а значит домен не очень-то и важный. На новый будут ссылаться сильно больше.

**Comment by furtivite** [comment]
> Насколько я помню, можно сделать редиректы на уровне Netlify, раз мы пока не переезжаем.

На уровне Netlify можно открывать даже один и тот же сайт с разных доменов. Осталось определить как нам надо.

**Comment by furtivite** [comment]
Моё мнение: надо бы полгодика хотя бы выводить плашку на старом домене о том, что мы переехали и просит обновить закладки. Можно при этом выводить уже сразу новый сайт. А через полгода просто сделать редирект.

**Comment by pepelsbey** [comment]
> Моё мнение: надо бы полгодика хотя бы выводить плашку на старом домене

@furtivite а зачем нам в интернете две Доки?

**Comment by furtivite** [comment]
> > Моё мнение: надо бы полгодика хотя бы выводить плашку на старом домене
> 
> @furtivite а зачем нам в интернете две Доки? Поисковики не видят плашек, они будут индексировать.

Поисковикам можно сказать, что домен y-doka.site - это алиас основного домена, поэтому трафик на него будет считаться трафиком на основной домен. 

Я боюсь, что есть где-то документы, где сохранён старый адрес, плюс есть закладки.

**Comment by pepelsbey** [comment]
> Я боюсь, что есть где-то документы, где сохранён старый адрес, плюс есть закладки.

Так можно же сделать вот так, условно:

```
rewrite /html/doka/doctype/    https://doka.guide/html/doctype/ permanent;
```

То есть каждый, зашедший на `https://y-doka.site/html/doka/doctype/` тут же окажется на `https://doka.guide/html/doctype/`, включая поисковики. И нам не нужно хранить никакой контент на старом сайте, только на уровне сервера (Netlify, Nginx) хранить схему редиректов.

**Comment by igsekor** [comment]
Ну я же сделал [пиар](https://github.com/doka-guide/y-doka.site/pull/726) с решением, там что-то не так?

**Comment by pepelsbey** [comment]
@igsekor я думаю про него все забыли просто. Шах и мат :)
