### ISSUE TITLE
Неразличимый код в коллауте

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#390]
В [статье о тестовых данных](https://doka.guide/js/testing-and-fake-objects/#moki) в коллауте есть куски кода, фон которых сливается с фоном самого коллаута:

<img width="963" alt="«Screenshot» 2021-09-20 at 15 49 24" src="https://user-images.githubusercontent.com/9102374/134004989-25244f89-8f06-4a75-8562-3abda8783b57.png">

Самое простое, что можно сделать, это «продырявить фон»:

<img width="804" alt="«Screenshot» 2021-09-20 at 15 49 56" src="https://user-images.githubusercontent.com/9102374/134005089-ef765d4a-e144-490b-a762-a044b561a5f6.png">

...Но мне кажется, пусть лучше это решат дизайнеры :—)

**Comment by pepelsbey** [comment]
Тут не совсем продырявить, сколько инвертировать — но отлично решение :)

**Comment by bespoyasov** [comment]
Ну я хотел это вывороткой или инверсией назвать, но я не дизайнер, поэтому чужие термины боюсь употреблять 😃

**Comment by monochromer** [comment]
Поправлено в этом [PR](https://github.com/doka-guide/platform/pull/430)
