### ISSUE TITLE
Отступ между коллаутом и следующим элементом

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#391]
В [статье об ФП](https://doka.guide/js/fp/) есть место, где коллаут и details соседничают, и кажется, что отступа между ними не хватает.

Десктоп:
<img width="956" alt="«Screenshot» 2021-09-20 at 15 52 39" src="https://user-images.githubusercontent.com/9102374/134005405-4e6f1d2e-3e34-4ce4-8173-dc50c61ea7ee.png">

Мобильный:
![IMG_5634](https://user-images.githubusercontent.com/9102374/134005444-61775bee-e0d8-495e-8a82-5db54f91203a.PNG)

**Comment by bespoyasov** [comment]
Нашёл [ещё](https://doka.guide/js/throttle/):

<img width="1082" alt="«Screenshot» 2021-09-20 at 19 21 50" src="https://user-images.githubusercontent.com/9102374/134038092-23fc3d78-80c4-4bd1-ab85-82db3a415767.png">

...и [ещё](https://github.com/doka-guide/platform/issues/397).

**Comment by nlopin** [comment]
Больше примеров в #397
