### ISSUE TITLE
Подсветка инлайн-кода в заголовках и боковой колонке

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#393]
В статье про [поток документа](https://doka.guide/html/flow/) есть код в заголовках. Он пишется моношрифтом, но не выделяется цветом.
Я не знаю, планируем ли мы выделять такой код.

**Comment by pepelsbey** [comment]
Если речь про [Обтекание при помощи float](https://doka.guide/html/flow/#obtekanie-pri-pomoshchi-float), то кажется, что так и должно быть.
