### ISSUE TITLE
Учесть высоту шапки при переходе по якорям

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#394]
Сейчас переход по якорю скроллит страницу прямо к якорю, но из-за фиксированной шапки, якорь не видно. Получается, что нас прискроллило куда-то, но непонятно, куда именно смотреть:

<img width="946" alt="«Screenshot» 2021-09-20 at 16 22 54" src="https://user-images.githubusercontent.com/9102374/134009878-f8ee16d9-5c57-4f96-9037-95b4d196b115.png">

Хочется, чтобы якорь в фокусе после скролла было видно:

<img width="930" alt="«Screenshot» 2021-09-20 at 16 25 04" src="https://user-images.githubusercontent.com/9102374/134010034-d1c8eead-887f-4d29-a911-78fe3762f144.png">

**Comment by pepelsbey** [comment]
У нас это решено [для обычных заголовоков](https://doka.guide/js/async-in-js/#cikl-sobytiy), надо так же сделать и для всех остальных.

**Comment by monochromer** [comment]
Поправлено в это [PR](https://github.com/doka-guide/platform/pull/426)
