### ISSUE TITLE
Инлайн-код растягивается на всю строку

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#395]
![CleanShot 2021-09-20 at 16 25 59](https://user-images.githubusercontent.com/13676514/134010247-1bb45a1d-99a8-4914-8494-ad3ee4744751.png)

Если код длинный, то он _падает_ на новую строку и занимает её всю. Из-за этого идущая следом точка падает уже на третью строку. 

Статья [про HTML](https://doka.guide/html/html/)

**Comment by solarrust** [comment]
Точка падает на новую строку даже если инлайн-код не длинный, а просто находится в конце строки

**Comment by monochromer** [comment]
Поправлено в этом [PR](https://github.com/doka-guide/platform/pull/430)
