### ISSUE TITLE
Коллаут и демка слипаются

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#397]
[В статье](https://doka.guide/html/fieldset/) рядом стоят коллаут и демка. И они слиплись 
![CleanShot 2021-09-20 at 18 40 18](https://user-images.githubusercontent.com/13676514/134031335-1940b4e0-08fc-43f0-9c2a-85e671deaead.png)

**Comment by solarrust** [comment]
![CleanShot 2021-09-20 at 19 35 12](https://user-images.githubusercontent.com/13676514/134039869-9b9c4b63-e959-46c7-951f-385382e2c7f0.png)

Два коллаута слипаются вместе

**Comment by nlopin** [comment]
закрою, как дубликат #391
