### ISSUE TITLE
Стили для цитат?

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#400]
Может, стоит как-то выделить цитаты? Сейчас там просто отступ, но его [как будто недостаточно](https://doka.guide/js/architecture-mvc/).

<img width="988" alt="«Screenshot» 2021-09-20 at 19 25 19" src="https://user-images.githubusercontent.com/9102374/134038611-6d0dc4be-70ec-4e47-a209-ecac94952d8d.png">

Я бы сделал их по виду, как коллауты, только вместо эмоджи там бы всегда была открывающая кавычка. Но это как вариант.

**Comment by pepelsbey** [comment]
Дубликат #396
