### ISSUE TITLE
Убрать ссылку на себя?

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#402]
Я не знаю, какая у нас политика в этом плане, но кажется, что ссылку на себя можно не ставить в меню на странице статьи:

<img width="942" alt="«Screenshot» 2021-09-20 at 19 30 49" src="https://user-images.githubusercontent.com/9102374/134039284-8f8d990d-e7b1-4198-85ab-584f2d6d8046.png">

Будет как-то так:

<img width="922" alt="«Screenshot» 2021-09-20 at 19 32 00" src="https://user-images.githubusercontent.com/9102374/134039416-fd614c03-4232-45f1-b30e-ff96eab95024.png">

Если у этой ссылки есть какая-то функция, то ишью можно закрыть.

**Comment by pepelsbey** [comment]
Ссылка на саму себя в логотипе — полезно. А с заголовка лучше убрать, чтобы не было сомнений.
