### ISSUE TITLE
`/` и `Esc` в поиске не открывают и не закрывают модалку с поиском

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#403]
Сейчас `Esc` не закрывает модалку с поиском, а слэш не открывает его.

<img width="1440" alt="«Screenshot» 2021-09-20 at 19 33 48" src="https://user-images.githubusercontent.com/9102374/134039687-d90032f6-e597-437c-81a6-fcfa8908b3b7.png">

Клик на серый бэк-дроп тоже не закрывает модалку:

<img width="1440" alt="«Screenshot» 2021-09-20 at 19 35 28" src="https://user-images.githubusercontent.com/9102374/134039954-4b1f4675-0cf4-4a2a-915e-54632928bbf0.png">

**Comment by pepelsbey** [comment]
Шапка пока не доделана, ждали дизайна саджеста. Но ишью пока оставлю, только «ошибку» уберу :)
