### ISSUE TITLE
Баг с моментом появления градиента в шапке?

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#405]
Не уверен, что это критично, и вообще, но если не вовремя перестать крутить страницу, то можно сломать шапку 🙃

<img width="1440" alt="«Screenshot» 2021-09-20 at 19 45 34" src="https://user-images.githubusercontent.com/9102374/134041425-1376715b-79f1-48fc-be8c-9de8105cd516.png">

**Comment by pepelsbey** [comment]
Подтверждаю, тоже замечал

**Comment by monochromer** [comment]
Что именно считается багом?

**Comment by bespoyasov** [comment]
> Что именно считается багом?

Резкий переход к белому градиенту из синего:

<img width="25" alt="«Screenshot» 2021-09-29 at 11 37 28" src="https://user-images.githubusercontent.com/9102374/135233499-c97f17a7-0138-4247-aeac-2742a993d791.png">
