### ISSUE TITLE
Страница с лицензиями ведёт на 404

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#406]
[Лицензии](https://doka.guide/licenses) убивают нашу собачку :–( 

<img width="1440" alt="«Screenshot» 2021-09-20 at 19 48 51" src="https://user-images.githubusercontent.com/9102374/134041776-a801d609-c72c-43e4-b883-c62f2e0a3f43.png">

**Comment by pepelsbey** [comment]
[Страница уже в ПР](https://github.com/doka-guide/content/pull/1570), это контент. Лучше закрою.
