### ISSUE TITLE
Сделать подписи к картинкам подписями

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#408]
Сейчас подписи к изображениям в некоторых статьях (например, [API](https://doka.guide/js/api/)) сделаны параграфом:

<img width="749" alt="«Screenshot» 2021-09-20 at 19 59 40" src="https://user-images.githubusercontent.com/9102374/134043350-1490bb02-2b95-40c2-b7d9-9ae11d810e7c.png">

Хочется использовать `<figcaption>`. Это может ударить по удобству, потому что нужно будет объявлять тег `<figure>` для картинки, но может быть у нас появятся какие-то идеи, как это решить.

**Comment by pepelsbey** [comment]
Это всё же не ошибка, в маркдауне это не подпись к картинке, а обычный параграф:

```markdown
![Изображение банкомата, внутри которого сидит человек. API — кнопки банкомата](images/atm.jpeg)

Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
```

Другое дело, что нам надо бы придумать систему, чтобы так можно было :)

Мне кажется, что будет круто просто писать без отступа:

```markdown
![Изображение банкомата, внутри которого сидит человек. API — кнопки банкомата](images/atm.jpeg)
Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
```

И чтобы оно сразу становилась подписью с точки зрения какого-нибудь маркдаун-плагина.

**Comment by bespoyasov** [comment]
Видимо, при переносе контента из Ноушена не уследили. В оригинале точно была подпись :–) 

Идея с подписью без отступа крутая. Это неочевидно, но можно считать это advanced-синтаксисом для авторов 😎

**Comment by pepelsbey** [comment]
> Идея с подписью без отступа крутая. Это неочевидно, но можно считать это advanced-синтаксисом для авторов 😎

Только представь: у тебе приходят новички и спрашиваю «Как ты это сделал?!» А ты такой «Я знаю трюк, смотрите».

**Comment by furtivite** [comment]
Мы же можем использовать тут чистый html и эти `<figure>`, которые @bespoyasov предлагал сильно раньше?

**Comment by pepelsbey** [comment]
> Мы же можем использовать тут чистый html и эти `<figure>`, которые @bespoyasov предлагал сильно раньше?

Можем, но придётся писать сильно больше кода и не забывать пустые строки. Сравни:

```markdown
![Изображение банкомата, внутри которого сидит человек. API — кнопки банкомата](images/atm.jpeg)
Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
```

И вот это:

```markdown
<figure>

![Изображение банкомата, внутри которого сидит человек. API — кнопки банкомата](images/atm.jpeg)

  <figcaption>Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».</figcaption>

<figure>
```

А если захочется использовать в подписи ссылку или код, то становится совсем невыносимо:

```markdown
<figure>

![Изображение банкомата, внутри которого сидит человек. API — кнопки банкомата](images/atm.jpeg)

<figcaption>

Пользователь не видит, что [происходит](link) внутри, для него `доступно` только API «калькулятора».

</figcaption>

<figure>
```

**Comment by furtivite** [comment]
@pepelsbey, да, согласен, это достаточно сложный в написании тег, значит, действительно без отступа строки, а потом преобразовывать на месте так, как нам нужно, через трансформацию. Хоть в ту же фигуру. Надо только научить линтер не ругаться на такое сочетание, потому что он будет, плюс описать об этом в документации.
