### ISSUE TITLE
Покрасить заголовок окна

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#415]
Было бы классно красить заголовок окна в Доке в зависимости от темы и раздела, где находится пользователь. 

Пример сайта с покрашенным заголовком:
<img width="1552" alt="Screenshot 2021-09-22 at 11 00 05" src="https://user-images.githubusercontent.com/50330458/134305431-a52c062e-4470-46a2-ae89-1dc91d077738.png">

Пример сейчас:
<img width="1552" alt="Screenshot 2021-09-22 at 11 00 01" src="https://user-images.githubusercontent.com/50330458/134305456-340b9500-fe7e-448c-8ad7-28f7ac348e81.png">

**Comment by pepelsbey** [comment]
```html
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#fff">
<meta name="theme-color" media="(prefers-color-scheme: dark)"  content="#000">
```

**Comment by furtivite** [comment]
На самом деле тут проблема стоит несколько глубже:

1. Было бы классно красить заголовок окна в чёрный и белый только на сервисных страницах, которые не относятся ни к одному из разделов. 
2. У каждого раздела свой цвет. 
3. Выбранная тема не всегда системная, а иногда выбранная вручную.

**Comment by nlopin** [comment]
кажется это можно накручивать поверх основы, предложенной Вадимом. Или я путаю?

**Comment by furtivite** [comment]
> кажется это можно накручивать поверх основы, предложенной Вадимом. Или я путаю?

Можно просто вставить теги, предложенные Вадимом, но при переключении темы кнопкой, переключение тега не сработает. Так что надо будет писать JS, а раз писать JS, можно и условия по разделам добавить.

**Comment by pepelsbey** [comment]
Я предложил чёрный и белый как примеры. Мы можем в шаблонах выводить там нужные цвета. А если мы не в разделе — ставить чёрный или белый, в зависимости от темы. JS тут не нужен.
