### ISSUE TITLE
Сделать чередование вывода картинки и описания для featured-статей

### ISSUE THREAD

**Issue by monochromer** [doka-guide/platform#416]
В дизайне сделано чередование вывода - на нечётных элементах списка отображается картинка, на чётных - текстовое описание. Мне кажется, из-за этого страдает UX. Например, новичок смотрит на карточку "Поток документа" с картинкой и ему непонятно о чём статья.

Почему бы не выводить все данные?
![image](https://user-images.githubusercontent.com/6412192/134464322-a134ab33-2807-4cc1-9655-f2f1c2eb9e60.png)

**Comment by furtivite** [comment]
Мне кажется, что это спорная идея потому, что тогда пропадёт идея «квадратности» интерфейса, он станет прямоугольным, что вряд ли соответствует задумке дизайнеров. Возможно, стоит обсудить это изменение UX.
