### ISSUE TITLE
В саджесчены при поиске никак не попасть с клавиатуры

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#417]
![CleanShot 2021-09-23 at 08 41 11](https://user-images.githubusercontent.com/13676514/134459440-7294f488-541e-4cd1-8968-ac247bff4aa8.png)

**Comment by monochromer** [comment]
Если нажать Tab, то фокус перейдёт на ссылки, но там есть другая проблема - блок c `overflow: hidden` начнёт прокручиваться, если в фокус попадёт скрытая ссылка.

**Comment by solarrust** [comment]
Ага, да, табом можно переключиться на саджест, но стоит сделать выделение активного (находящегося в фокусе) пункта более явным =)
![CleanShot 2021-09-23 at 10 41 54](https://user-images.githubusercontent.com/13676514/134470967-688f0945-a675-4c93-b03c-24f4dcb3a280.png)

**Comment by nlopin** [comment]
Я бы ещё перемещение в саджест по кнопке вниз добавил. Это поведение, которому нас учат раскрывающиеся списки

**Comment by monochromer** [comment]
Оставлю [issue](https://github.com/doka-guide/platform/issues/527), а это закрою.
