### ISSUE TITLE
Если в поиске нажать какой-то фильтр, то отжать его не получится

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#421]
1. Ищем что-нибудь.
2. Нажимаем фильтр в боковой колонке.
3. Больше не можем отжать фильтр и видеть все-все статьи =(

**Comment by monochromer** [comment]
Сейчас для этого неявно служит кнопка "Esc"

**Comment by solarrust** [comment]
У меня по Esc Сафари выходит из полноэкранного режима =)

**Comment by pepelsbey** [comment]
> У меня по Esc Сафари выходит из полноэкранного режима =)

@monochromer нужно добавить preventDefault для Esc

**Comment by monochromer** [comment]
> @monochromer нужно добавить preventDefault для Esc

Чтобы нельзя было выйти из полноэкранного режима? )

**Comment by pepelsbey** [comment]
> Чтобы нельзя было выйти из полноэкранного режима? )

Чтобы срабатывало только одно действие, пока мы его слушаем. А потом, вторым нажатием, уже можно выйти из фулскрина.

**Comment by cergmin** [comment]
На мобильной версии тоже наблюдается эта проблема, но кнопки Esc там нет :(

**Comment by pepelsbey** [comment]
Завёл ишью с задачей-решением для этой, велком #826
