### ISSUE TITLE
Поправить title в зафичеренных статьях

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#428]
В зафичеренных статьях, у квадратных цветных блоков в качестве `title` у ссылок выводится название статьи, если в названии находится тег с бэктиками, он выводится так же с бэктиками. 

- Если в заголовке есть бэктики, выводить `title` без них.

Возможно, если в статье есть `description` стоит подумать, чтобы выводить в `title` при наведении именно `description`, это поможет решить проблему, описанную в #416

**Comment by monochromer** [comment]
Бэктики не выводятся, они преобразуются в тег `<code>`

**Comment by furtivite** [comment]
> Бэктики не выводятся, они преобразуются в тег `<code>`

https://www.loom.com/share/4fbbee07300b47e29807b002b36c4427 

Вот такое поведение имею в виду.

**Comment by monochromer** [comment]
> https://www.loom.com/share/4fbbee07300b47e29807b002b36c4427
> 
> Вот такое поведение имею в виду.

Слова **атрибут** было бы достаточно )
