### ISSUE TITLE
Смена оформления инлайнового  элемента `<code>`

### ISSUE THREAD

**Issue by monochromer** [doka-guide/platform#442]
Сейчас используется такое оформление для инлайнового элемента `<code>` (видимо, дизайнеры подсмотрели за github'ом):
![image](https://user-images.githubusercontent.com/6412192/134764588-496852ee-f3f5-4b1e-aa32-7bd93250026c.png)

Обнаружился ряд проблем:
- затруднение чтения из-за визуального нагромождения, так как такие элементы забирают пространство и отвлекают цветовым контрастом
- ссылки [визуально не распознаются](https://github.com/doka-guide/platform/issues/366), если в них есть код
- элементы с кодом могут находится внутри цветных плашек (callout, например), поэтому приходится регулировать контрастность фонового цвета. В будущем, таких плашек может стать больше и для каждой плашки нужен будет свой цвет. Добавьте сюда ещё тёмную тему.

Предлагаю просто убрать фоновый цвет у элемента `<code>`. Моноширинного шрифта должно быть достаточно.

<details>
  <summary><b>Было:</b></summary>

  ![image](https://user-images.githubusercontent.com/6412192/134764913-47ecc774-899d-4ea7-881f-5b775e7928aa.png)
</details>

<details>
  <summary><b>Стало:</b></summary>

  ![image](https://user-images.githubusercontent.com/6412192/134764926-0a49db85-f17c-404a-9b2f-7e645621dccc.png)
</details>

**Comment by pepelsbey** [comment]
На мой взгляд, мы теряем многое из стиля, если совсем убираем булочки из фрагментов кода. Мы их вроде бы поджали их до размеров поменьше — стало лучше.

**Comment by furtivite** [comment]
Да, кажется, во время дизайна не подумали, что у нас ссылки не имеют другого цвета, а у гитхаба он есть. Пример:

[`<a>`](https://github.com/doka-guide/content/blob/main/html/a/index.md)

При этом мне кажется, что для обозначения ссылки в куске кода, можно использовать `border`, это будет перекликаться с кнопкой «Редактировать на Github»

<img width="1181" alt="Screenshot 2021-09-26 at 12 42 44" src="https://user-images.githubusercontent.com/50330458/134802538-2cae6c8f-78e6-4df6-82b0-e27e435fc800.png">

**Comment by pepelsbey** [comment]
Обводка для ссылок не обозначает ссылки, их нужно подчёркивать, как и все остальные на сайте. Я предложил [решение с подчёркиванием](https://github.com/doka-guide/platform/issues/366).
