### ISSUE TITLE
Лишний квадрат вокруг фавиконки

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#445]
Дано:
1. Safari 15
2. Big Sur 11.6
3. Тёмная тема

Последовательность:
1. В Сафари открываем Доку
2. Закрепляем вкладку
3. Уходим на другую вкладку
4. Видим, что вокруг круга с буквой Д на фавиконке есть какой-то полупрозрачный квадрат

Для примера поставила рядом вкладки с другими круглыми фавиконками. У них всё хорошо 

<img width="153" alt="CleanShot 2021-09-27 at 01 35 11@2x" src="https://user-images.githubusercontent.com/13676514/134825000-326bc244-5aca-4ec6-9397-1d5e76b4bea6.png">

**Comment by pepelsbey** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/105274/134917142-e17f8de1-9ec7-46f9-b0e4-8f339dfd3830.png">

Это баг (фича?) Safari: вокруг логотипа MDN тоже рисуется рамка, а в самой иконке ничего нет:

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/105274/134917287-0cfa8030-a152-4e41-9af4-25fb7beab9cc.png">

**Comment by solarrust** [comment]
Да, я посмотрела исходник фавиконки перед тем как ставить задачку. Видела, что там нет никакого квадратика. Есть подозрение, что это зависит от окраски верхней части окна Сафари. Замечаю, что квадрат виден, если окраска светлая. Но это пока не точно, надо наблюдать. Давай пока закроем
