### ISSUE TITLE
Убрать `title` со ссылок?

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#448]
Иногда подсказка перекрывает текст, если «неправильно» остановить курсор:
<img width="466" alt="«Screenshot» 2021-09-27 at 16 28 46" src="https://user-images.githubusercontent.com/9102374/134918149-66d75062-4622-45cc-add0-00709818cc99.png">

Да и в целом вроде здесь `title` пользы не несёт, в нём дублируется текст самой ссылки:
<img width="188" alt="«Screenshot» 2021-09-27 at 16 32 33" src="https://user-images.githubusercontent.com/9102374/134918596-d2268a0f-7a03-41ed-b13b-0bfaf8b5cb0e.png">

**Comment by pepelsbey** [comment]
Зачем там `title` это вопрос. Кажется незачем :) Думаю, надо убрать.
