### ISSUE TITLE
Ссылка на трансформации с главной 

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#464]
При переходе c главной [по якорной ссылке на Трансформации](https://doka.guide/css/#transformacii) в Safari 15, попадаешь не в нужный блок, а куда-то в район «подвала»

https://www.loom.com/share/83373453fa19421a9e84d05d98c2a2f2

BigSur 11.6

**Comment by furtivite** [comment]
@monochromer, посмотри, пожалуйста, кажется, это проблема связана с zoom. На 100%, не воспроизводится, если сделать зум меньше, например на 1 уровень, то может появиться. Сможешь протестировать?

**Comment by monochromer** [comment]
не воспроизводится

**Comment by monochromer** [comment]
Если будет воспроизводится снова, то можно будет открыть. Пока закрою.
