### ISSUE TITLE
Поредактировать форму фидбека

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#479]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/105274/136198167-a75ece42-9472-4435-b628-389b8bf989df.png">

Форму видно в конце [каждой статьи](https://doka.guide/html/input/).

Вот файл [feedback-form.njk](https://github.com/doka-guide/platform/blob/main/src/includes/feedback-form.njk)

Было бы хорошо причесать формулировки, включая «Ошибки отправляйте в pull-request на GitHub».

**Comment by tachisis** [comment]
Как вам формулировка «Статья была полезной?» А то «Оцените» это как-то очень общо.

Ну а для второй строки: «Если вы нашли ошибку, отправьте нам пул-реквест!»
