### ISSUE TITLE
Сделать плашку про Cookies

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#480]
Дизайнеры нарисовали плашку про Cookies:

<img width="753" alt="Screenshot 2021-10-06 at 20 55 29" src="https://user-images.githubusercontent.com/50330458/136258122-aee5aaa4-e103-4cf6-9f0d-49371d0a71f7.png">

<img width="810" alt="Screenshot 2021-10-06 at 20 56 35" src="https://user-images.githubusercontent.com/50330458/136258129-e6a397ed-2467-4e3e-9668-1d333a8fdd63.png">

Мы должны эту плашку выводить для резидентов и граждан ЕС (The Privacy and Electronic Communications (EC Directive) Regulations 2003). 

Предлагается доработать эту плашку таким образом:

1. Текст:

«Мы используем куки. Как? (ссылка на страницу)»

2. Кнопка «Хорошо»

---

Показывать эту плашку, если пользователь не нажал кнопку «Хорошо», и хранить эту информацию в LocalStorage, например.

**Comment by pepelsbey** [comment]
> может, лучше вместо "куки" написать "cookie"?

Если мы говорим «куки», то кажется пора уже и писать «куки». Мы же перестали писать sms и перешли к смс.
