### ISSUE TITLE
Обозначить использование Aglolia в качестве движка для поиска

### ISSUE THREAD

**Issue by igsekor** [doka-guide/platform#481]
Нужно внести упоминание Algolia в результатах поиска. Наверное, можно начать с отображения логотипа на странице поиска.

<img width="1401" alt="Screenshot 2021-10-06 at 21 19 34" src="https://user-images.githubusercontent.com/13916521/136260771-9fb371f3-b22f-4eea-9032-49780d2732f8.png">

Логотипы надо брать на [специальной странице](https://www.algolia.com/press/?utm_medium=page_link&utm_source=dashboard&section=brand-guidelines) тут:

<img width="1409" alt="Screenshot 2021-10-06 at 21 23 01" src="https://user-images.githubusercontent.com/13916521/136261231-cf85125e-b4bc-460f-85dd-2b7a7684f4f0.png">

**Comment by pepelsbey** [comment]
Я бы написал текстом и использовал только логотип. Что-то вроде:

Поиск работает с помощью [<img src="https://res.cloudinary.com/hilnmyskv/image/upload/q_auto/v1633455143/Algolia_com_Website_assets/images/shared/algolia_logo/algolia-blue-mark.svg" width="16"> Algolia](https://www.algolia.com/)

Хотя бы потому, что Search by Algolia — это странная реплика по-английски на сайте, который говорит по-русски.

**Comment by monochromer** [comment]
Судя по всему упоминание с логотипом можно добавить на страницу "О проекте"

**Comment by pepelsbey** [comment]
Это очень расплывчатая формулировка. Плюс я не вижу удачного места, где бы можно было рассказать про поиск на странице «О проекте».

Давайте всё же в сайдбар на странице поиска.

**Comment by pepelsbey** [comment]
> Там же, где говориться об Eleventy

Это старая версия страницы, на новой [по-другому](https://github.com/doka-guide/content/blob/7c1d6eaf55e59a93940ea0a83a6e9c88d61c92d3/pages/about/index.md)
