### ISSUE TITLE
Тёмная тема и iframe

### ISSUE THREAD

**Issue by monochromer** [doka-guide/platform#497]
У элемента iframe по умолчанию прозрачный фон и при этом он не наследует стили внешней среды. Из-за этого в тёмной теме текст становится нечитабельным.

![image](https://user-images.githubusercontent.com/6412192/136535531-3dc053b9-5ff3-433b-9430-800163bdb35e.png)
![image](https://user-images.githubusercontent.com/6412192/136535496-3ca7005f-310c-4087-aeff-f8509a8ffe34.png)

Как простое решение - добавить к iframe стили `background-color: #fff;`. Chrome в авторежиме умничает и сам делает фон белым.

**Comment by nlopin** [comment]
Мне сложно говорить о демках. Круто, если они вливаются в общую тему, но тогда у нас вырастает трудозатраты на каждую демку.
