### ISSUE TITLE
Неудобно возвращаться в основной раздел, если в статье кликал по содержанию 

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#522]
Каждый клик по заголовкам содержания добавляет запись в историю. Когда хочется после чтения статьи вернуться в основной раздел, то приходится долго отматывать историю назад:

[🎥 Демонстрация](https://www.loom.com/share/b5d1d93be5df4f689be920fddcf22340)

Если это неудобно не только мне, то надо заменить `pushState` на `replaceState`. Кажется это лёгкий стартовый баг для новичков

## Шаги

1. Зайти в длинную статью. Например, [области видимости](https://doka.guide/js/closures/)
2. Кликнуть несколько раз на разных разделах содержания — экран будет прокручиваться к выбранному разделу
3. Попытаться вернуться назад при помощи кнопки «назад» браузера

## Ожидаемое поведение

Одно нажатие кнопки «назад» переносит из статьи в основной раздел

## Наблюдаемое поведение

Нужно нажать на кнопку «назад» столько раз, сколько перемещений по содержанию произвёл пользователь

**Comment by monochromer** [comment]
Если кликать на anchor-ссылки в самих заголовках, то нужно тоже менять поведение.

**Comment by monochromer** [comment]
> Если кликать на anchor-ссылки в самих заголовках, то нужно тоже менять поведение.

Но нужно ли, так как это стандартное браузерное поведение?

**Comment by pepelsbey** [comment]
Я бы оставил это поведение — именно так работает браузер и якоря в нём. Сейчас можно перейти в раздел и получить на него ссылку в адресной строке. И мы не пытаемся трюковать и выкручиваться, всё просто работает.

Стоит послушать фидбек пользователей, прежде чем идти на меру, которая отключает встроенное браузерное поведение якорей.

**Comment by solarrust** [comment]
@pepelsbey закрываем или ждём возможности собрать фидбэк? Я бы оставила как есть сейчас

**Comment by igsekor** [comment]
Плюсую к @solarrust!

**Comment by pepelsbey** [comment]
Давайте оставил и продолжил слушать. Закрываю тогда :)
