### ISSUE TITLE
Добавить перемещение между результатами поиска с помощью клавиатуры

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#527]
Понял, что привык пользоваться поиском без участия мыши: ввёл слово, получил какой-то suggestion, начал прыгать по предложениям стрелками на клавиатуре, дальше по enter попадаю на нужную страницу. 

Это может быть полезно людям с ограниченными возможностями, либо тем, у кого нет возможности воспользоваться мышкой. Кажется, нам стоит об этом подумать, такой фичи пока нет.

## Из строки поиска

Вот тут возможно: придётся ещё и стрелки влево-вправо задействовать.

<img width="873" alt="Screenshot 2021-10-12 at 09 46 29" src="https://user-images.githubusercontent.com/50330458/136905840-adcf9845-171e-4b4a-b97f-d88f71fc7ff2.png">

Пример реализации

<img width="1003" alt="Screenshot 2021-10-12 at 09 57 22" src="https://user-images.githubusercontent.com/50330458/136907089-d6965ac1-8278-4b28-b7fb-e5bb16f452a1.png">

## Из страницы

<img width="945" alt="Screenshot 2021-10-12 at 09 46 45" src="https://user-images.githubusercontent.com/50330458/136905842-650e0108-669c-4085-a479-01d4d19cb089.png">

Выделение может быть стандартным синим, как аутлайн, а может совпадать по цвету с цветом раздела

<img width="1428" alt="Screenshot 2021-10-12 at 09 53 01" src="https://user-images.githubusercontent.com/50330458/136906719-7aebb069-a47c-4e39-b934-7ab0058a322c.png">

**Comment by solarrust** [comment]
Кажется, сейчас можно комфортно перемещаться по шапке и телу статьи с клавиатуры. Ещё актуально?

**Comment by furtivite** [comment]
Из шапки в сафари на странице поиска пока нельзя выйти по клавиатуре, чтобы попасть на список статей.

**Comment by igsekor** [comment]
Да, нужно поправить!

**Comment by solarrust** [comment]
Без проблем вышла из шапки, дойдя до кнопки Esc https://cln.sh/juzYzm

Или речь про то, что по кнопке Esc на клавиатуре Сафари выходит из полноэрканного режима?

**Comment by furtivite** [comment]
<img width="1436" alt="Screenshot 2022-04-04 at 13 37 01" src="https://user-images.githubusercontent.com/50330458/161527055-f027d8ab-28d8-4624-bd34-a1e0051ba542.png">

[страница](https://www.doka.guide/search/?query=def)

При нажатии на таб, в сафари курсор 15.3 прыгает в адресную строку
При нажатии на esc строка очищается и поиск вместе с ней

То есть без мышки мы не можем перепрыгнуть на первый и последующие пункты из выдачи

**Comment by pepelsbey** [comment]
@furtivite чтобы Safari ходил с помощью таба не только по полям ввода, но и по ссылкам, нужно включить настройку в браузере (в Chrome это включено по умолчанию):

<img width="792" alt="image" src="https://user-images.githubusercontent.com/105274/161626771-e2117aaf-54c8-45bd-b04b-ed33420a598b.png">

Именно так делают те, кому важна и нужна навигация с клавиатуры. Если мы будем делать такое с помощью скриптов, мы а) замучаемся и б) будем мешать тем, кто пользуется встроенной браузерной навигацией по интерактивным элементам.

**Comment by pepelsbey** [comment]
Я бы закрыл задачу: базовую навигацию из поиска мы сделали.

**Comment by furtivite** [comment]
@pepelsbey, спасибо, да, тогда задачу можно закрывать.
