### ISSUE TITLE
Пересмотреть оптимизацию картинок

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#528]
А то в статье «[Файлы и файловые системы](https://doka.guide/tools/file/)» есть 3 МБ картинка WebP, которая должна быть 279 КБ JPEG или 157 КБ WebP.

**Comment by monochromer** [comment]
> А то в статье «[Файлы и файловые системы](https://doka.guide/tools/file/)» есть 3 МБ картинка WebP, которая должна быть 279 КБ JPEG или 157 КБ WebP.

Откуда такие точные значения?

Уже говорили, что даже `quality: 80` приводит к пережатому тексту. Поэтому применяется сжатие без потерь.

**Comment by monochromer** [comment]
Я при настройках `quality: 75` и `effort: 4` смог только получить 446Kb
