### ISSUE TITLE
Прокрутка к блоку

### ISSUE THREAD

**Issue by igsekor** [doka-guide/platform#537]
При нажатии на ссылку "Кастомные свойства" в футере на главной странице прокрутка к блоку на некоторых мониторах не заметна.

<img width="1278" alt="Screenshot 2021-10-12 at 20 45 45" src="https://user-images.githubusercontent.com/13916521/137004385-012b1434-c805-4df0-91dc-a7aa2ea2ceb2.png">

**Comment by web-padawan** [comment]
Немного контекста: блок на моем мониторе находится внизу справа
![Screenshot 2021-10-12 at 20 56 41](https://user-images.githubusercontent.com/10589913/137005929-92fc4381-ccab-434d-909d-2fa06274d627.png)

Из-за того, что читаемая область достаточно широкая, взгляд не сразу попадает туда при прокрутке.
Если эту же страницу прокрутить к началу и нажать <kbd>Enter</kbd> в строке браузера, прокрутка не происходит.
