### ISSUE TITLE
Неправильное выделение активного пункта в левом меню

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#540]
Если на [странице](https://doka.guide/js/web-security/) встречается несколько подзаголовков с одинаковым содержимым, то левое меню ломается и не знает, какой пункт выделять как активный:

<img width="1440" alt="«Screenshot» 2021-10-12 at 22 24 22" src="https://user-images.githubusercontent.com/9102374/137016826-c520f029-aac9-4752-9381-88dacdd2d195.png">

Судя по всему, в механизм слагификации при появлении одинаковых ID надо добавить постфикс в виде индекса:

<img width="645" alt="«Screenshot» 2021-10-12 at 22 26 07" src="https://user-images.githubusercontent.com/9102374/137017016-d0f7cc84-e863-4e41-91b0-319953ce0b74.png">

Пример страницы:
- https://doka.guide/js/web-security/

**Comment by teleginzhenya** [comment]
Я возьмусь
