### ISSUE TITLE
Добавить файлик .nvmrc с нужной версией ноды

### ISSUE THREAD

**Issue by starkovsky** [doka-guide/platform#547]
Было бы очень удобно иметь такой файлик, поскольку множество проектов требуют для работы свою версию ноды.
Это также является хорошей практикой для разработчиков

Ссылка на доку
https://github.com/nvm-sh/nvm#nvmrc

**Comment by starkovsky** [comment]
> У нас [указана](https://github.com/doka-guide/platform/blob/main/package.json#L5-L7) желательная версия Node.js и npm.

Здравствуйте Вадим, я помню, что вы не любите лишних файликов в проекте, но nvm позволяет переключать версии ноды в неймспейсе каждого проекта. Это действительно удобно. Возможно вы передумаете.

**Comment by pepelsbey** [comment]
Закрыто в #559
