### ISSUE TITLE
Чуть более эффективное использование пространства

### ISSUE THREAD

**Issue by olegKusov** [doka-guide/platform#558]
![изображение](https://user-images.githubusercontent.com/28058268/137126554-b91ffe70-71d5-4e6e-b4be-0dae096992b5.png)

Хочется понимать что означают карточки. если это самые популярные разделы то возможно стоит так и назвать "Популярное".

также визуально я бы сделал высоту карточек меньше или бы обернул их в более узкий контейнер на экранах ноутбуков. на небольших экранах использовать сайт будет сложновато.

**Comment by olegKusov** [comment]
> 
> 
> > Хочется понимать что означают карточки. если это самые популярные разделы то возможно стоит так и назвать "Популярное".
> 
> Привет, спасибо за обратную связь!
> 
> Карточки сейчас — это статьи, которые мы сами порекомендовали и поместили на главной.

возникает небольшой дискомфот когда видишь карточки статей которые никак не описываются. хочется понимать что это. если рекомендация, то возможно стоит над ними так и написать "Рекомендуем". Спасибо!

**Comment by pepelsbey** [comment]
Спасибо за фидбек! Мы послушаем, возникают ли сложности у других читателей и если это что-то общее, то подумаем, как сделать лучше.
