### ISSUE TITLE
Доступность: убрать фокус сайдбара  

### ISSUE THREAD

**Issue by lex111** [doka-guide/platform#569]
Сейчас если кликнуть по сайдбару или перейти на него к клавиатуры, он непонятно зачем получает фокус.

UPD: Понятно, это из-за `tabindex="0"`, который актуален для мобильных устройств, чтобы сделать кнопку оглавления доступной, в любом случае на декстопе это лишний фокус.

![image](https://user-images.githubusercontent.com/4408379/137160756-be7ead9f-f03b-403a-af0f-b135bd029c98.png)

**Comment by monochromer** [comment]
Это осталось после рефактора. Но его не нужно удалять, а перенести на другой вложенный элемент, чтобы при фокусе можно было стрелками посмотреть элемент.

**Comment by lex111** [comment]
Не исправлено, по-прежнему фокус есть на сайдбаре.

![image](https://user-images.githubusercontent.com/4408379/137580819-c1a4b952-daec-4106-b9e7-c98a0483fe8f.png)

**Comment by lex111** [comment]
Если элемент содержит фокусируемые элементы, то достаточно обеспечить чтобы он мог бы прокручиваемый.  Типичный пример - https://web.dev/learn/css/ -- здесь в сайдбаре фокус переходит на первый фокусируемый элемент (ссылку), и с помощью клавиш-стрелок появляется возможность прокрутить контент. Делать явно прокручиваемый весь сайдбар имеет смысл если там будет только статический контент, без фокусируемых элементов вроде ссылок. Здесь же всегда есть ссылки, поэтому нет необходимости делать сайдбар полностью фокусируемый.

![image](https://user-images.githubusercontent.com/4408379/137590244-5f2df513-e109-4a00-bbf5-b6fd57ce22ab.png)
