### ISSUE TITLE
Предложение: Убрать градиент под шапкой

### ISSUE THREAD

**Issue by ishindanil** [doka-guide/platform#583]
_Данное изменение может улучшить User Experience._

Когда я читаю статьи, я использую верхнюю часть браузера или шапку сайта (если она `sticky`), как линейку в начальных классах школы - чтобы было видно, на какой строчке я нахожусь. Например, если отвлечешься, то не нужно будет глазами искать, где ты остановился. Поэтому градиент под шапкой мешает мне, затеняя часть текста. 

Возможно, я такой не один, и удаление его удаление улучшит пользовательский опыт.

![image](https://user-images.githubusercontent.com/22240112/137332473-5f836e97-1a9b-454e-a2ba-ae9674ca2067.png)

**Comment by skorobaeus** [comment]
В ПР #707 тень под шапкой была сделана более гладкой и прозрачной. При обновлённых параметрах попадающий под тень текст никогда не перекрывается стопроцентно непрозрачной заливкой, и это очень хорошо! Я померила контрастность текста под градиентом: она варьируется от 4.5:1 до 6.2:1, что соответствует АА-стандарту доступности, то есть означает, что текст достаточно читаем даже под тенью. Тень можно оставить :)
