### ISSUE TITLE
Предложение: увеличить размер шрифта для оглавления

### ISSUE THREAD

**Issue by Semigradsky** [doka-guide/platform#586]
`12px` - это **слишком** мало.

![image](https://user-images.githubusercontent.com/1198848/137339955-55c842cb-ceba-408d-b163-0f749166ee8c.png)

Как вариант - увеличивать размер шрифта при наведении мышью на `.article_aside`?

**Comment by TatianaFokina** [comment]
Как вариант можно увеличить `line-height` с `1.6px` до `2px` или другим способом расстояние между ссылками в этом списке, чтобы высота одного пункта в сумме была минимум `24px`. Тогда мы избежим ошибки касания цели и это будет соответствовать [новому критерию о размере цели из WCAG 2.2](https://www.w3.org/TR/WCAG22/#target-size-minimum).

![В боковом меню с якорными ссылками к статье выделен пункт «Строчные элементы в нормальном потоке». Его высота 19.19 пикселей.](https://user-images.githubusercontent.com/17615202/200400656-f1dddd9b-7b73-45eb-bf5e-7ec53ae322d0.png)
Сейчас высота пункта списка в сумме `19.19px`.

![В боковом меню с якорными ссылками к статье выделен пункт «Контекст форматирования». Его высота 24 пикселя.](https://user-images.githubusercontent.com/17615202/200400666-1e56fbac-d0b1-468d-806c-05a08a556299.png)
За счёт `line-height: 2px` высота пункта стала `24px`. Так сложнее нажать не на тот пункт.

**Comment by skorobaeus** [comment]
Я перенесла комментарии из этого ишью в большое ишью о типографике #551. А это для удобства закрою.
