### ISSUE TITLE
Рассмотреть возможность динамически задавать высоту демок

### ISSUE THREAD

**Issue by lex111** [doka-guide/platform#593]
Сейчас периодически встречаются демки-фреймы, в которых есть небольшая (ненужная) прокрутка, пример -- https://doka.guide/css/fill/

![image](https://user-images.githubusercontent.com/4408379/137397628-77687159-0252-4a0f-9f41-d857ad2addfb.png)

Или здесь https://doka.guide/html/option/

![image](https://user-images.githubusercontent.com/4408379/137398958-13ad7bf9-b2a8-412b-80ee-f3425bf56311.png)

Можно попробовать динамически задавать им высоту, а в случае длинных демок явно устанавливать высоту как ограничение (как сейчас).

**Comment by monochromer** [comment]
> Гораздо надёжнее сработает механизм ручной установки высоты

Ну как надёжный... Шрифт не загрузился или скрипт, который что-то меняет в DOM, не отработал, и высота iframe теперь не равна той, что в атрибуте height.

**Comment by solarrust** [comment]
Будем ли думать в сторону автоматической высоты ещё? Кажется, на всех предыдущих обсуждениях мы пришли к выводу, что это не реально.

**Comment by igsekor** [comment]
Кажется, что это не реально в масштабах всех демок. Проще сделать вручную.

**Comment by furtivite** [comment]
Там было две проблемы:

1. Надо вытаскивать высоту демки из iframe наружу
1. Надо пересчитывать высоту демки на мобильных и узких экранах

Плюсую к Игорю, вручную надо делать точно.

**Comment by solarrust** [comment]
Задачу закрываю
