### ISSUE TITLE
Добавить стили для заголовков 4-го уровня

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/platform#6]
Сейчас трудно понять, что «Бесшовность» или «Быстродействие» — это заголовки, а это нужно для быстрого «сканирования» содержания по заголовкам, особенно в лонгридах.

<img width="935" alt="«Screenshot» 2020-11-25 at 11 38 37" src="https://user-images.githubusercontent.com/9102374/100202903-fae28c80-2f12-11eb-9673-1f8ce1340ee8.png">

Я бы предложил как минимум выделить их жирным, но нужно мнение дизайнеров.

P.S. Технически мы можем в лонгридах убрать заголовок «Как понять» второго уровня и поднять всю иерарихю подзаголовков повыше, но это несистемное решение 🙂

**Comment by furtivite** [comment]
[Пример использования](https://doka.guide/html/deprecated-tags/#kogda-ispolzovalos)

**Comment by monochromer** [comment]
В новой версии у заголовков 4-го уровня такой же размер, как и у обычного текста, и при этом нет жирного начертания. Поэтому они сливаются. Для шрифта Gpahik есть версии c medium-жирностью, а для Spot Mono нет.

**Comment by monochromer** [comment]
Как насчёт таких визуальных подсказок для заголовков?

![image](https://user-images.githubusercontent.com/6412192/146242893-114280f4-1bf1-4c5d-bfb9-8b51e9752dc8.png)

![image](https://user-images.githubusercontent.com/6412192/146242921-95126220-c70c-4a61-995b-b052b5be6d90.png)

**Comment by pepelsbey** [comment]
> Как насчёт таких визуальных подсказок для заголовков?

Норм, только бы ширину рамки подогнать под толщину штриха

**Comment by skorobaeus** [comment]
Придумали придерживаться исходной идеи Материалиста и выделять заголовки размером. Также предлагаю задать размеры и для заголовков h5 (на всякий случай).

**1680+**
H4 - 32px
H5 - 26px

**1366 - 1680**
H4 - 26px
H5 - 22px

**768 - 1366**
H4 - 24px
H5 - 20px

**375 - 768**
H4 - 22px
H5 - 19px

На десктопе выглядеть будет так:

![image 38](https://user-images.githubusercontent.com/29401439/168759868-f1163bd7-e3de-4265-97ef-2152f8d6fbb5.png)

**Comment by nlopin** [comment]
@skorobaeus нужны еще `line-height` если можно. Или оставить as-is?

**Comment by nlopin** [comment]
На большом экране четвертый и третий у меня почти не отличаются:
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/1469636/170882157-40d151e5-e46a-4d13-8165-3a4df2e9a8ca.png">

**Comment by nlopin** [comment]
Мы точно хотим делать пятый уровень? У нас нет ни одной статьи с таким уровнем вложенности

**Comment by solarrust** [comment]
Я визуально вижу разницу между заголовками, хоть и не большую. Пятый уровень, на сколько я понимаю, просто про запас.

**Comment by skorobaeus** [comment]
Я добавила `line-height` в свой комментарий выше ✌

> На экране 1366-1680 четвертый и третий у меня почти не отличаются (30 vs 26px):

Согласна, выглядят похоже. На скриншоте заголовки H3 и H4 совпали по длине и это только усиливает сходство.

Но я не могла щедро приращивать по 10px на уровень, так что пошла на компромисс :) Мне кажется, разница в 4px  видна.

![image](https://user-images.githubusercontent.com/29401439/170978847-f0e98d95-8545-4d2a-8ba7-459ee119509b.png)

> Мы точно хотим делать пятый уровень? У нас нет ни одной статьи с таким уровнем вложенности

Если это сложно технически, то можно не делать. Но я подумала, что если возможность закрыть вопрос насовсем, то это хорошо :)
