### ISSUE TITLE
Формировать список статей автора

### ISSUE THREAD

**Issue by igsekor** [doka-guide/platform#608]
Можно сделать это отдельной страницей, можно сделать попутчиком, можно и так, и так. А можно ещё как-нибудь, например, на странице поиска добавить фильтр дополнительно (правда придётся индекс чуть подработать напильником)...

**Comment by monochromer** [comment]
Нужно уточнить происхождение задачи. Если делать список статей автора отдельной страницей, то нужно делать его страницу в общем

**Comment by monochromer** [comment]
Наверно, нужно актуализировать описание, так как происхождение задачи, повторюсь, не понятно. Раздел с людьми будет, тогда задачу можно сформировать как "Добавить фильтр по авторам и контрибьюторам". Но сильно ли это нужно?

**Comment by solarrust** [comment]
Кажется, это задача-родитель для #807 Верно понимаю?

**Comment by igsekor** [comment]
Даже прародитель.

**Comment by solarrust** [comment]
Значит эту задачу закрываю.
