### ISSUE TITLE
Ширина iframe с демками в статьях не соответствует содержимому

### ISSUE THREAD

**Issue by ArturAntonov** [doka-guide/platform#610]
Нашел такую проблему, что ширина iframe в статьях не задается, задается только высота. В итоге iframe сплющен там, где это не нужно.
Внизу на скриншотах примеры двух демок из статей по инпутам и по тенюшкам.
Нашел, какой используется стиль [figure__content](https://github.com/doka-guide/platform/blob/4ba98057e471af8be82b628fe7c1225eaefbd782/src/styles/blocks/figure.css). Казалось бы достаточно будет прописать туда `width: 100%`, но я заметил, что в некоторых демо на самом деле ну нужна ширина на весь экран.
А поскольку мест, где на 100% будет лучше больше, чем мест, где не нужно так, то все же добавить в класс figure__content width: 100%, а уже для фреймов, где не нужна такая ширина прописывать в разметке атрибут `style="width: 200px"`.

<img width="900" alt="Снимок экрана 2021-10-15 в 21 49 10" src="https://user-images.githubusercontent.com/15684266/137539632-08e7add4-a618-4548-b562-c8d388c15bd2.png">
<img width="900" alt="Снимок экрана 2021-10-15 в 21 49 20" src="https://user-images.githubusercontent.com/15684266/137539614-1fd60612-294a-43f5-8227-445d79df1ec9.png">
<img width="900" alt="Снимок экрана 2021-10-15 в 21 49 42" src="https://user-images.githubusercontent.com/15684266/137539582-fb9f4b04-ed2a-47e5-8520-7f34ed494b70.png">
<img width="900" alt="Снимок экрана 2021-10-15 в 21 50 04" src="https://user-images.githubusercontent.com/15684266/137539569-207263f4-bd7d-41e5-8329-fcb390b8e3f7.png">
.

**Comment by pepelsbey** [comment]
Скоро раскатится и починится. Спасибо за внимательность! Мы сегодня выкатили подписи к демкам и промахнулись.
