### ISSUE TITLE
Html код используемый для оформления текста показывается в расширенном поиске как есть

### ISSUE THREAD

**Issue by vaiil** [doka-guide/platform#613]
Статья https://doka.guide/css/font-style/ содержит текст выделенный `span`-ом, который попадает в summary:

![image](https://user-images.githubusercontent.com/3755615/137559317-48463dfe-73d2-4496-aebe-f748e6ab352a.png)

Я вижу два возможных решения:
* Вырезать html теги при формировании поискового индекса из абзацев
* Не применять escape к этому тексту (что потенциально не безопасно)

**Comment by monochromer** [comment]
Мне кажется, для извлечения текста лучше использовать LinkeDOM, так как можно однозначно получить все нужные элементы и чистое текстовое представление. Все пограничные случаи вряд ли получится выразить в виде регулярных выражений.

**Comment by nlopin** [comment]
Может нам индекс из из маркдауна собирать, а не из html? Или нам нужен html, чтобы точно отдавать место совпадения?

**Comment by vaiil** [comment]
@nlopin он собирается из маркдауна, просто там в самом md файле есть html код
