### ISSUE TITLE
Остаётся много пустого пространства если рядом стоят категории с разным количеством статей

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#629]
![CleanShot 2021-10-17 at 11 29 04](https://user-images.githubusercontent.com/13676514/137618679-b57b3f76-d992-4d19-95d2-77212aa1445a.png)

**Comment by monochromer** [comment]
> Внешне ничего не изменилось https://cln.sh/XAgJla

> Поменяли раскладку в https://github.com/doka-guide/platform/pull/579

**Comment by monochromer** [comment]
Можно, кончено, откатить к старой раскладке. Но, скорее всего, придётся убрать анимацию target-блока в Safari (если её не пофиксили), залипающие заголовки групп статей и помнить, что порядок следования будет сверху-вниз, а не слева-направо.
