### ISSUE TITLE
Скрываемая шапка приводит к перекомпоновке

### ISSUE THREAD

**Issue by lex111** [doka-guide/platform#630]
Каждое появление и скрытие шапки приводит к принудительной перекомпоновке:

> [Violation] Forced reflow while executing JavaScript took 42ms

В итоге при активной чтении статьи в консоли много ошибок:

![image](https://user-images.githubusercontent.com/4408379/137618642-5b4aa058-d520-4651-8ea6-cf5c9815c2f1.png)

**Comment by pepelsbey** [comment]
А в чём суть проблемы? Мы не рассчитываем, что нас будут читать с открытой консолью.

**Comment by pepelsbey** [comment]
Тогда предлагаю поменять описание ишью (или открыть новую, как удобно) и может ещё привести более удачные примеры поведения таких шапок.
