### ISSUE TITLE
Кнопка навигации статьи мешает выбрать тему

### ISSUE THREAD

**Issue by xxtereshko** [doka-guide/platform#631]
![image](https://user-images.githubusercontent.com/19520678/137633376-171d8509-db1c-4ad1-aff6-80de0f643313.png)

**Comment by pepelsbey** [comment]
Тоже хотел завести ишью и предложить сдвинуть кнопку вправо: либо на всех экранах, либо на узких.

Обсудим, решим. Спасибо!

**Comment by xxtereshko** [comment]
Думал предложить дать отступ снизу, но понял, что просто это сделать не выйдет

**Comment by Jumpinlord** [comment]
Соглашусь, кнопку можно бы сдвинуть вправо для удобства, полагаю, футеру это не  должно повредить.

**Comment by pepelsbey** [comment]
Завёл задачу на исправление #827

**Comment by monochromer** [comment]
Сдвинули кнопку вправо в этом [PR](https://github.com/doka-guide/platform/pull/832). Но, думаю, лучше было бы показывать кнопку при скролле наверх. Но там больше всяких UX-нюансов.
