### ISSUE TITLE
Переименовать блок «В работе» в «На практике»

### ISSUE THREAD

**Issue by Mitorun** [doka-guide/platform#648]
В конце статей есть раздельчик "В работе". Он сильно неудачно выглядит по оформлению и своему названию. Когда впервые его увидел, то было непонятно что это и зачем - кажется что эта статья дальше "в работе", какое-то имя ссылкой, потом какие-то абзацы непонятно к чему относящиеся. Когда узнал зачем этот раздел (на самом деле все еще не уверен), то он также кажется неудачно оформленным.
![image](https://user-images.githubusercontent.com/68237469/137816748-73caa0ed-bb52-4698-aef3-3b83c5c7fdad.png)
Как сделать лучше - не знаю, вот идеи навскидку: сделать название типа "Использование в работе", "Идеи по применению", "приемы из практики" или "Лайфхаки". Имя автора сделать меньше по размеру и добавить двоеточие "Алёна Батицкая:".

П.С. На странице https://doka.guide/css/outline/ также есть опечатка, выделена на скриншоте.

**Comment by pepelsbey** [comment]
Да, вы правы — пока не очень понятно. Но у нас есть планы сделать раздел «В работе» лучше, чтобы отделить его от остальной статьи. Пока он оформлен как есть и это вряд ли решится заголовком или двоеточиями, нужно его оформить особым образом.

**Comment by monochromer** [comment]
> П.С. На странице https://doka.guide/css/outline/ также есть опечатка, выделена на скриншоте.

Опечатки, пожалуйста, несите в [репозиторий контента](https://github.com/doka-guide/content), а лучше сразу делайте PR.
