### ISSUE TITLE
Относительные ссылки в результатах поиска

### ISSUE THREAD

**Issue by lex111** [doka-guide/platform#650]
На примере https://doka.guide/search/?q=%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D1%8B

![image](https://user-images.githubusercontent.com/4408379/137884309-98455b29-8e1e-47b6-83f2-8075ae138b1c.png)

![image](https://user-images.githubusercontent.com/4408379/137884445-c63cef70-af64-447c-865f-a96debea3876.png)

**Comment by monochromer** [comment]
Поправлено в [этом PR](https://github.com/doka-guide/content/pull/2224).
