### ISSUE TITLE
Использовать возможности 11ty для вывода даты обновления статьи

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#652]
Обратил внимание, что после мёржа не изменилась дата изменения [статьи Git CLI](https://doka.guide/tools/git-cli/).

Дата изменения указана 20 сентября:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1469636/137982587-c7c99d8d-6b20-4bda-a746-1b3d8dac7376.png">

При этом 19 октября было [вмёржено дополнение к статье](https://github.com/doka-guide/content/pull/1947).

**Comment by igsekor** [comment]
Можно просто доавить вариант ручного запуска. Я ещё флоу немного поменяю, будет запускаться. Взял к себе.

**Comment by monochromer** [comment]
В принципе, можно вычислять даты на стороне сборщика, запуская git-процесс и парсить его вывод. Но это может значительно увеличить время сборки. Зато такой способ позволит избавиться от data-файлов в репозитории контента.

**Comment by solarrust** [comment]
@igsekor кажется, в 11ty появилось поле даты, которое может нам помочь с этой задачкой. Правильно помню?

**Comment by igsekor** [comment]
> @igsekor кажется, в 11ty появилось поле даты, которое может нам помочь с этой задачкой. Правильно помню?

Да, теперь можно использовать:

```yaml
---
date: Last Modified
---
```
