### ISSUE TITLE
Перемещение переключателя

### ISSUE THREAD

**Issue by knoxydev** [doka-guide/platform#657]
Предлагаю переместить переключатели тёмной темы к поисковому `input` который находится в шапке страницы

**Comment by pepelsbey** [comment]
Вы могли бы это как-то аргументировать?

**Comment by nkr413** [comment]
> А вы могли бы аргументировать это с точки зрения вашего опыта? Вы часто такими переключателями пользуетесь?
> 
> Дело в том, что наш переключатель (да и любой другой подобный) — это скорее аварийный стоп-кран, когда вам не нравится та тёмная или светлая тема, которую мы включили на основе ваших предпочтений в ОС или в браузере. То есть это не игрушка, а инструмент настройки. Наша задача не в том, чтобы с ней играл каждый зашедший на сайт, а чтобы к ней обращались те, кому это нужно.
> 
> Это почему она так расположена. Текст тоже сильно понятнее иконок, если честно. Может быть не так привычно (часто такое делают иконками), но точно понятнее.

Я вас понял. Хорошо. Спасибо за ответ и ваше подробное объяснение)

**Comment by skorobaeus** [comment]
При проектировании пользовательского опыта есть правило размещать переключатели внутри или в непосредственной близости от элемента, который таковые переключатели меняют. Переключение с тёмной темы на светлую затрагивает всю и, а значит переключатель темы нужно размещать где-то в "общей" части страницы. Это хэдер и футер в равной степени, боковая панель в меньшей степени.

Мне, на данный момент, неизвестно о каком-либо UX-исследовании на этот счёт, а беглый анализ макетов и собственная насмотренность подсказывают, что дизайнеры делают выбор между хэдером и футером в соотношении примерно 50/50. А так как оба варианта реализовать невозможно, всегда приходится выбирать :) То же самое и по поводу иконок против слов — в равной степени используются оба варианта, хотя вариант со словесным обозначением даже более доступный.

Мы хотим сейчас сосредоточиться на ишью, значительно влияющих на функциональность платформы, и, по возможности, уменьшить техдолг. С этой точки зрения кажется рациональным оставить текущее работающее решение.
