### ISSUE TITLE
Фиксированная шапка на внутренних страницах

### ISSUE THREAD

**Issue by atereshhuk68** [doka-guide/platform#667]
На внутренних страницах сайта, шапка фиксированная. Неудобно читать статью.

Ошибка в консоли:
`Failed to execute 'matches' on 'Element': '.header:not(.header--static,.search-page__header)' is not a valid selector`

![13_30_34](https://user-images.githubusercontent.com/60702379/138260504-e395a7fa-f477-46fa-a2dd-854bee12f7c8.jpg)

**Comment by pepelsbey** [comment]
@monochromer может упростим селектор для лучшей совместимости?
