### ISSUE TITLE
Добавить в make-links.js удаление симлинков

### ISSUE THREAD

**Issue by xxtereshko** [doka-guide/platform#676]
Пока переписывал темплейт нунчак, заметил, что при изменении .njk файлов пересобирается весь проект, вместе с со всеми статьями. Я думаю, было бы здорово сделать скрипт, который бы убирал линки на репозиторий с контентом, потому как приходится очень долго ждать сборки после каких либо изменений в платформе.

**Comment by solarrust** [comment]
@igsekor что нужно сделать по этой задачке?

**Comment by igsekor** [comment]
> @igsekor что нужно сделать по этой задачке?

Мы уже это обсуждали, я сделаю вариант сборки для одной статьи.

**Comment by furtivite** [comment]
@xxtereshko, привет, мы тут сделали, но не отписались. Теперь Дока при старте удаляет ссылки и добавляет новые, или новую. Можно проверить)
