### ISSUE TITLE
Проблема с фокусом на кнопке "Показать ещё", а также у ссылок в блоке materials-collection

### ISSUE THREAD

**Issue by maxdenaro** [doka-guide/platform#678]
Привет!

Сейчас на сайте нет состояния :focus у кнопки "показать ещё", думаю оно было бы не лишним.

Также, ссылки в блоке materials-collection имеют фокус, но он обрезается из-за overflow: hidden как у li, так и у ul.

**Comment by monochromer** [comment]
Да, на windows такой фокус у Chromium-браузеров. Нужно разрабатывать свой визуальный стиль фокусов, учитывающий `overflow: hidden`;

**Comment by TatianaFokina** [comment]
Создала большую задачу про внешний вид фокуса, для кнопки из этой ишью на Windows сейчас применяются браузерные стили по умолчанию, так что думаю, что можно закрыть. Если есть какие-то идеи, проблемы и хочется это обсуждать дальше, то предлагаю делать это в #1093.
