### ISSUE TITLE
Сделать Доку PWA

### ISSUE THREAD

**Issue by rx1310** [doka-guide/platform#682]
Привет! Спасибо Вам за вашу работу. Благодаря Вам мой младший брат начал интересоваться вебом.

Хотелось бы иметь возможность пользоваться Докой как PWA-приложением, дабы вне доступа к сети иметь возможность обучаться.

Да хотелка. Да фича не первой важности. Однако было бы удобнее мне как юзеру.

**Comment by pepelsbey** [comment]
Закрываю в пользу будущих, более точно сформулированных задач про PWA и офлайн.
