### ISSUE TITLE
хотелось бы rss бы к проекту

### ISSUE THREAD

**Issue by mazzy-ax** [doka-guide/platform#691]
в rss хотелось бы видеть:

1. [на главной страние](https://doka.guide/) публикуются... хм... плашки с featured статьями на доке. в rss могут попадать статьи, которые попали в эти плашки. (рекомендуется. сделать сложнее) 
2. новые или обновленные статьи на доке. (сделать намного легче, но опыт с виками подсказывает, что генерируется много мусора в rss)

**Comment by TatianaFokina** [comment]
RSS прикрутили.
