### ISSUE TITLE
Ссылка на страницу 404 из поиска

### ISSUE THREAD

**Issue by cergmin** [doka-guide/platform#698]
Если вбить в поиске "yaml", то на странице результатов будет 2 ссылки на статью про YAML в разных разделах, причём первая ссылка (на статью из раздела js) ведёт на страницу 404.
![результаты поиска](https://user-images.githubusercontent.com/21996065/139383795-7100a85a-3529-4f60-a29b-b85bfc8575e9.png)

**Comment by igsekor** [comment]
Да, нужно просто из индекса его удалить. Сделаю.

**Comment by monochromer** [comment]
Индекс обновлён.
