### ISSUE TITLE
Не могу увидеть начало разделов из-за div блока (св-во header-inner--menu)

### ISSUE THREAD

**Issue by Artes-megion** [doka-guide/platform#702]
Не вижу начало разделов (JS.HTML.CSS) из за верхней шапки,причём закрыть её нельзя, в DevTools если удаляю её (элемент div со свойством header-inner--menu), то всё  становится окей. Почему так? Это у меня что-то не так? 
   Я сразу заранее извиняюсь если что-то не так описал, я новичок в верстке (полный прям) если что, на сайт нарвался как раз для изучения, но тут такое вот выяснилось.
  Разрешение монитора - 2560х1440. Браузер Chrome (вернее Cent -  но он на движке хрома полностью, разницы в отображении нету).
![1](https://user-images.githubusercontent.com/75933517/139452734-4f1ae9e3-c3eb-4f5c-9a4c-474c974398bd.png)
![2](https://user-images.githubusercontent.com/75933517/139452741-b083b483-c736-4eb5-b984-adde230de237.png)

**Comment by ZheniaEU** [comment]
Данная проблема у меня возникала только на Cent браузере. Cent браузер сходит с ума на сайте доки, постоянные проблемы с отображением и дисконты при переходе по ссылкам.  Нет возможности закрыть хедер никак, ни кликом по крестику, ни по клавише ESC. В связи с чем, я просто перестал им пользоваться на доке.

**Comment by pepelsbey** [comment]
@ZheniaEU браузер Cent не обновлял движок Chromium уже не меньше года и некоторые современные возможности CSS там не работают. Мы конечно поправим ошибки и улучшим совместимость, но мне кажется, что там и патчей безопасности год как не было, так что подумайте про выбор браузера :)
