### ISSUE TITLE
Показывать дополнительное поле в доках «появилось в»

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#704]
## Идея

Мы часто пишем про новые выражения и инструкции, которые могут работать не во всех браузерах. 

Мы не caniuse.com, но будет полезно указывать номер спеки, в которой инструкция появилось, чтобы читатель мог сам дальше разобраться. Это особенно полезно в JS, где инструменты (например, babel) часто требуют указывать под какую версию транспилировать код

Пример: «Появилось в ES6»

## Возможная реализация

Создать опциональное поле в метаданных, которое будет хранить номер версии и подставлять по шаблону в начало доки

**Comment by pepelsbey** [comment]
Боюсь, что это сложно будет формализовать. Некоторые штуи появились не в спеках, а просто в браузерах. И уже потом стали частью спек, а некоторые вещи даже не стали )

**Comment by igsekor** [comment]
А может запилить таки аналог вставки с caniuse.com? Я думал над этим в качестве будущей фичи. Думаю, это можно реализовать. Поговорим?

**Comment by pepelsbey** [comment]
Просто у Can I Use большая, но не всегда корректная база. Так что я бы нашару не вставлял. Но давать ссылку туда — точно стоит. И ссылку на спеку. Всё это можно и нужно, на мой взгляд, зашить в мету каждой доки.

**Comment by igsekor** [comment]
> Просто у Can I Use большая, но не всегда корректная база. Так что я бы нашару не вставлял. Но давать ссылку туда — точно стоит. И ссылку на спеку. Всё это можно и нужно, на мой взгляд, зашить в мету каждой доки.

Я и не говорил о том, чтобы внедрять его у нас. Я говорил об аналоге. Там у них с лицензией ещё не всё в порядке для нас)

**Comment by solarrust** [comment]
Что нужно сделать в рамках этой задачи?

**Comment by igsekor** [comment]
Просто сделать! 😇

**Comment by solarrust** [comment]
Что именно сделать?
1. Свою версию CanIuse?
2. Обязательные поля в мете на спецификацию и canIuse?

**Comment by igsekor** [comment]
Я предлагаю два этапа, сначала второй пункт, а потом, если будет возможно, то и первую.

**Comment by solarrust** [comment]
Тогда давай заведём две отдельные задачи, а эту закроем?

**Comment by solarrust** [comment]
#922 
#923
