### ISSUE TITLE
Рассинхронизация обновления поискового индекса и сайта

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#713]
Через 14 минут после мёржа:

<img width="884" alt="image" src="https://user-images.githubusercontent.com/105274/139751005-1975b59e-05fb-4e27-a6a8-653df2b3b98c.png">

Статью уже можно найти:

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/105274/139750964-0793bec5-2606-4dec-80f0-e9f38a867414.png">

Но она ещё 404

<img width="1280" alt="2" src="https://user-images.githubusercontent.com/105274/139750971-7cefa7c7-ded9-4342-8ee6-c69a19b350bc.png">

UPD: через 16 минут появилось, но всё же :)

**Comment by monochromer** [comment]
Полагаю, issue должно называться как-то так - "Рассинхронизация обновления поискового индекса и сайта".

**Comment by pepelsbey** [comment]
> Полагаю, issue должно называться как-то так - "Рассинхронизация обновления поискового индекса и сайта".

@monochromer спасибо, я ночью не смог сформулировать правильно, но было важно не забыть

**Comment by monochromer** [comment]
Как вариант - запускать сборку индекса после деплоя.

**Comment by monochromer** [comment]
> Как вариант - запускать сборку индекса после деплоя.

Например, [так](https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed).

**Comment by solarrust** [comment]
@igsekor сохранилась ли эта проблема?

**Comment by igsekor** [comment]
Нет. Можно закрывать, поскольку мы вообще переезжаем с Algolia.
