### ISSUE TITLE
Показывать фиксированную шапку при скролле наверх

### ISSUE THREAD

**Issue by slitrobo** [doka-guide/platform#718]
Шапка, которая выезжает при изменении позиции скролла должна выезжать когда пользователь скроллит наверх.

**Comment by monochromer** [comment]
Что будет происходить с шапкой, когда пользователь скроллит до самого вверха?

**Comment by cergmin** [comment]
Кажется, что удобнее, когда хлебные крошки почти всегда видны на странице, чем когда они появляются только при дополнительном действии (скроле наверх).

**Comment by slitrobo** [comment]
@monochromer Она должна разворачиваться в статичную шапку. Для этого мы сделали их одинаковыми.
@cergmin Читателю удобнее, когда 100% высоты окна отдано под контент статьи, которую он читает — меньше приходится скроллить. А кейс с навигацией — второстепенный относительно чтения.

**Comment by monochromer** [comment]
> Она должна разворачиваться в статичную шапку. Для этого мы сделали их одинаковыми.

Фиксированная и статичная отличаются структурой и размерами

![image](https://user-images.githubusercontent.com/6412192/145040806-0ac002b3-b9fc-4a2e-bcd1-674d1a3e4b56.png)
![image](https://user-images.githubusercontent.com/6412192/145041023-80245cd8-7d88-44ea-8cb1-03d7dae58514.png)
