### ISSUE TITLE
Завести страницы авторов-контрибьюторов

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#720]
Необходимо завести layout для страниц авторов в Доке. 

1. На странице выводить
    - Имя автора
    - Ссылку от автора на его проект или гитхаб
    - Фото автора (опционально)
    - Краткое описание (опционально)
    - Бейджи за активность
    - Список статей, где владелец страницы — автор
    - Список статей, где владелец страницы — контрибьютор
    - Список статей, где владелец страницы — редактор
    - Галерею изображений со ссылками на статьи, для дизайнеров
2. Поправить мету в папке `people` для обеспечения функциональности
3. Реализовать на платформе

**Comment by solarrust** [comment]
> Необходимо завести layout для страниц авторов в Доке.
> 
> 1. На странице выводить
>    
>    * Имя автора
>    * Ссылку от автора на его проект или гитхаб
>    * Краткое описание (опционально)
>    * Бейджи за активность
>    * Список статей, где владелец страницы — автор
>    * Список статей, где владелец страницы — контрибьютор
>    * Список статей, где владелец страницы — редактор
>    * Галерею изображений со ссылками на статьи, для дизайнеров
> 2. Поправить мету в папке `people` для обеспечения функциональности
> 3. Реализовать на платформе

Я бы начала с MVP, где будет:
- Имя
- Ссылка
- Список статей под авторством
- Список статей с контрибьюшенами
- Список блоков «на практике»

Остальные пункты можно добавлять итеративно.

> Список статей, где владелец страницы — редактор
Редактор у нас один и других быть не может =) Или это персонально для Оли?

**Comment by furtivite** [comment]
Я целиком и полностью за MVP даже без дизайна. 

> Список статей где хоть как-то засветился

У нас есть два поля, автор и контрибьютор, тут кажется проще выводить два списка, чем объединять в один. 

> Редактор у нас один и других быть не может =) Или это персонально для Оли?

Редактор у нас один — Оля, но если вдруг появится второй, то поле статей для редактирования выводить только в том случае, если в статье указан, как редактор. То есть, кажется, что тут простой проверкой на наличие поля можно решить.

**Comment by furtivite** [comment]
@nlopin, @pepelsbey, @monochromer, @igsekor выскажетесь?

**Comment by igsekor** [comment]
Кажется, что в MVP несложно будет добавить и список статей сразу. И разделить этот список было бы здорово по степени участия (автор статьи, автор практики, контрибьютор, работа над иллюстрацией, работа над демками).

Роль редактора выделять, думаю, не стоит. Редактор у нас один! :)

Технически, наверное, нам надо добавлять это не в мету автора, а в мету демок (не понятно куда её поместить, правда) и в мету практики.

**Comment by solarrust** [comment]
Ну, практики у нас все находятся в подписанных файлах с именем автора. А вот с демками я бы пока не заморачивалась.

**Comment by nlopin** [comment]
Кажется демки — это слишком. Мы авторов демок сейчас записываем в контрибьюторы, так что в списке всё равно засветится.

Мне нравится идея говорить сделать два списка автор и контрибьютор, но не настаиваю

**Comment by monochromer** [comment]
> Фото автора (опционально)

Аватар, помнится, хотели заливать прямо в репо, а не использовать внешние ссылки?

**Comment by monochromer** [comment]
> Аватар, помнится, хотели заливать прямо в репо, а не использовать внешние ссылки?

Как поле будет называться - `avatar` или `photo`?

**Comment by pepelsbey** [comment]
> Как поле будет называться - `avatar` или `photo`?

@monochromer давай `photo`, так чуть понятнее, даже если там и не всегда фото

**Comment by monochromer** [comment]
Так ли нужны ссылки и счётчики с issues и pull requests?

**Comment by solarrust** [comment]
Решили, что счётчики ишью и пул-реквестов будут классной фишкой, но не на этапе MVP
