### ISSUE TITLE
Разделить конфиги eslint для браузерного кода сайта и для кода nodejs-скриптов

### ISSUE THREAD

**Issue by monochromer** [doka-guide/platform#722]
Это совершенно разные среды и для них нужны разные конфиги. Можно что-то общее переиспользовать. Для браузера желательно использовать browserslist.

**Comment by pepelsbey** [comment]
> Это совершенно разные среды и для них нужны разные конфиги

Речь исключительно про поддержку ES-фич или про синтаксис тоже?
