### ISSUE TITLE
Некоректно отображается код внутри кода

### ISSUE THREAD

**Issue by cergmin** [doka-guide/platform#723]
Если в статье необходимо показать, как в markdown можно размечать код через бэктики, то нужно использовать сложную конструкцию, где внутри четверных бэктиков будет фрагмент кода, обёрнутый в тройные бэктики:
`````md 
````md
Функция ```console.log(...)```
выводит текст в консоль.

Сумму двух переменных
можно вывести так:
```javascript
let a = 1;
let b = 2;

alert(a + b);
```
````
`````

В итоге она должна отображаться так:
````md
Функция ```console.log(...)```
выводит текст в консоль.

Сумму двух переменных
можно вывести так:
```javascript
let a = 1;
let b = 2;

alert(a + b);
```
````

Но doka показывает её так:
![image](https://user-images.githubusercontent.com/21996065/140072724-956df6c2-8383-4913-87f3-976daa59a868.png)

**Comment by pepelsbey** [comment]
Если не указывать язык, то получается нормально:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/105274/140075074-7b32b04d-a81f-48df-a41a-3004406f097d.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/105274/140075125-1071641b-519c-4d16-9197-2a444ca7ff54.png">

**Comment by cergmin** [comment]
Это действительно работает

**Comment by cergmin** [comment]
Только сейчас понял, что если не указывать тип, то нумерация строк показываться не будет.

**Comment by cergmin** [comment]
@monochromer, да, с этими исправлениями всё работает. Спасибо!
![image](https://user-images.githubusercontent.com/21996065/140250432-3f15df70-bcb3-44bc-bf40-caf25c92ef96.png)
