### ISSUE TITLE
Не появляется страница 404

### ISSUE THREAD

**Issue by cergmin** [doka-guide/platform#735]
Если открыть несуществующий адрес, например https://doka.guide/abcdef, то откроется главная страница, а не 404

**Comment by pepelsbey** [comment]
Мы вчера переезжали на новый сервер и, видимо, не перевезли адреса ошибок в конфигах.

Спасибо, поправим!

**Comment by igsekor** [comment]
Проблема решена! Спасибо, что заметили!
