### ISSUE TITLE
Ошибка в генерации файла-изображений

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#737]
В [гайде по гриду](https://doka.guide/css/grid-guide/) на проде в Safari 15 не открываются часть картинок (Проще всего найти по фразе: «Грид-ячейка: пространство между соседними грид-линиями. Единица грид-сетки.»)

<img width="1308" alt="Screenshot 2021-11-05 at 15 56 27" src="https://user-images.githubusercontent.com/50330458/140514202-a134ec06-f0ab-402e-aa62-f4d338122ba1.png">

В других браузерах на проде всё открывается. 

<img width="1379" alt="Screenshot 2021-11-05 at 15 56 46" src="https://user-images.githubusercontent.com/50330458/140514233-a637eef2-6e38-49aa-b0b4-0d54c2e75ea7.png">

На локалхосте в Safari тоже открывается. 

Если попробовать сохранить битое изображение из Safari на компьютер, его тоже нельзя открыть стандартными средствами просмотра MacOS, при этом, если скачать файл не из Safari, то он открывается. 

Ссылка на файл пример: [https://doka.guide/css/grid-guide/images/4-2880w.webp](https://doka.guide/css/grid-guide/images/4-2880w.webp)

**Comment by monochromer** [comment]
А как отображает ли Safari другие webp-картинки?

**Comment by furtivite** [comment]
> А как отображает Safari другие webp-картинки?

Всё отображается корректно. 

Пример корректной картинки: [https://doka.guide/css/grid-guide/images/1-2880w.webp](https://doka.guide/css/grid-guide/images/1-2880w.webp)

**Comment by igsekor** [comment]
Не отображаются со 2 по 5 включительно. Причём 5-я вообще 505-Not found. Ребята, а может картинки не залились до конца всё же, а другие браузеры без окончания файлы могут отображать? Что-то пришло в голову. Надо попробовать перебрать сайт. Сейчас запущу пересборку и повторный залив. Удалю все файлы на сервере непосредственно перед заливкой (downtime < 10 секунд)...

**Comment by furtivite** [comment]
> Не отображаются со 2 по 5 включительно. Причём 5-я вообще 505-Not found. Ребята, а может картинки не залились до конца всё же, а другие браузеры без окончания файлы могут отображать? Что-то пришло в голову. Надо попробовать перебрать сайт. Могу запустить пересборку и повторный залив. Удалю все файлы на сервере непосредственно перед заливкой (downtime < 10 секунд)...

Мне тоже кажется, что проблема в том, что часть картинок просто не залилось.

**Comment by igsekor** [comment]
Эксперимент проведён. Та же ерунда. Значит проблема именно с файлами, которые отображаются везде, но не в Safari.

**Comment by monochromer** [comment]
> На локалхосте в Safari тоже открывается.

В dev- или prod-режиме?

Нужно сделать prod-сборку. Посмотреть, какие ошибки и заголовки (Accept, Content-Type) отсылаются и приходят.

Поддержка webp идёт в Safari с 14-ой версии и ОС Big Sur.

**Comment by monochromer** [comment]
> Нужно сделать prod-сборку. Посмотреть, какие ошибки и заголовки (Accept, Content-Type) отсылаются и приходят.
> 
> Поддержка webp идёт в Safari с 14-ой версии и ОС Big Sur.

Есть у кого-нибудь возможность проверить?

**Comment by furtivite** [comment]
> > Нужно сделать prod-сборку. Посмотреть, какие ошибки и заголовки (Accept, Content-Type) отсылаются и приходят.
> > Поддержка webp идёт в Safari с 14-ой версии и ОС Big Sur.
> 
> Есть у кого-нибудь возможность проверить?

Я делал и прод и дев сборку, но проверить не смогу. После установки Safari Technology Preview всё магическим образом починилось, но я спрашивал у @nlopin, кажется, проблема всё ещё есть.

**Comment by pepelsbey** [comment]
Safari 15.2 на macOS 12.1 — часть картинок тоже битые, к сожалению.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/105274/146377658-239f5e8f-945b-4713-9da7-68f4d55a4f14.png">

**Comment by pepelsbey** [comment]
Для картинок 2–4 пишет «Resource has no content»

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/105274/146377912-2047c400-4f13-4103-a59e-60018aa019e2.png">

**Comment by pepelsbey** [comment]
Если сохранить картинки на десктоп, то у 5 превью есть, а у 2 нет. То есть WebP-движок macOS не справляется

<img width="230" alt="image" src="https://user-images.githubusercontent.com/105274/146378181-972d1558-6444-455e-824b-d3e1e5cc07a3.png">

Но если закинуть картинку прямо в Chrome или Firefox, то она рендерится

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/105274/146378296-cfc4b85f-31b8-440d-bd85-b396816d411e.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/105274/146378348-cda48523-b0c6-4249-b55b-0434cd8cfd70.png">

**Comment by monochromer** [comment]
Значит, в MacOS сломанный кодек.

**Comment by pepelsbey** [comment]
Ну или sharp генерирует картинки не по спеке, я бы им [занёс ишью](https://github.com/lovell/sharp/issues), если получится просто воспроизвести.

**Comment by monochromer** [comment]
Недавно Safari обновлялся до версии 15.3, может, и кодеки починили?

**Comment by furtivite** [comment]
> Недавно Safari обновлялся до версии 15.3, может, и кодеки починили?

Только сегодня обновил, у меня вроде всё работает, но хорошо бы собрать мнения от всех, кто может проверить.

**Comment by monochromer** [comment]
На MacOS Monterey Safari 15.1 грузится webp

![image](https://user-images.githubusercontent.com/6412192/152944119-5b09cf08-faca-4bbb-b7a6-de743d587430.png)
