### ISSUE TITLE
На главной странице сайта поменять способ загрузки картинок для улучшения LCP

### ISSUE THREAD

**Issue by igsekor** [doka-guide/platform#738]
В Lighthouse в числе прочих точек улучшения рекомендуется поработать с картинками зафичеренных статей:

![IMAGE 2021-11-05 20:45:57](https://user-images.githubusercontent.com/13916521/140555459-544b5412-722b-4ebb-bbb2-9ef3fd970cad.jpg)
![IMAGE 2021-11-05 20:45:59](https://user-images.githubusercontent.com/13916521/140555468-474e4b7e-b699-4eb9-afc4-90a819df9b9e.jpg)

Если картинка отображается на мобильном или десктопе для первых зафичеренных статей, а мы её грузим с помощью ленивой загрузки, мы ухудшаем LCP на ровном месте.

**Comment by pepelsbey** [comment]
Как раз собирался завести это ишью по результатам лайтхауса, но ты меня опередил :)

**Comment by monochromer** [comment]
Добавил [здесь](https://github.com/doka-guide/platform/pull/741)
