### ISSUE TITLE
Поиск на 404 странице

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#743]
Очень удивилась, когда попав на 404 старицу и нажав `/` для продолжения поиска не получила никакой реакции. 

Точно ли мы хотим чтобы с этой страницы можно было вернуться только на главную или провалится в карточки?

**Comment by pepelsbey** [comment]
Согласен! Давайте вернём туда такую же шапку, как на всех страницах сайта.

**Comment by nlopin** [comment]
+1000
