### ISSUE TITLE
Изменить способ фичеринга статей на главной

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#751]
## Интро
Сейчас мы фичерим на главной некоторые статьи:

![Screenshot 2021-11-12 at 13 51 35](https://user-images.githubusercontent.com/50330458/141458864-05671577-4ebb-4585-9257-899bd8d9c9f8.png)

Они выводятся через коллекцию `featuredArticles` посмотреть [тут](https://github.com/doka-guide/platform/blob/main/src/views/views.11tydata.js#L50) и [тут](https://github.com/doka-guide/platform/blob/main/src/includes/articles-gallery.njk).

Коллекция выводит все статьи, при наличии у них тега `featured` [пример](https://raw.githubusercontent.com/doka-guide/content/main/html/input/index.md):

```md
tags:
  - doka
  - featured
```

## Проблема
- Сложно отследить какие статьи зафичерены, а какие нет
- Сложно обновлять статьи на главной

## Предложения к улучшению
- Сделать несколько списков для зафичеренных статей,
    - `featured` - __уже зафичеренные__ статьи, которые выводятся/могут выводиться на главной
    - `candidate` - __потенциальные статьи для фичеренга__: те статьи, которые собираются с некоторой регулярностью редакцией разделов. Робот должен пройтись по этому списку и сделать часть статьей зафичеренными
    - `force` - __обязательно-зафичеренные__ статьи: те статьи, по которым робот не ходит, и которые будут выводиться на главной обязательно, по усмотрению редакторов разделов.
- Сделать функцию-рандомайзер, которая будет в случайном порядке сортировать статьи на главной из тех, что уже зафичерены
- Перенести статусы фичеринга статей из статьи, в индексный файл ([пример файла](https://raw.githubusercontent.com/doka-guide/content/main/css/index.md)), чтобы при создании нового списка статей для фичеринга их было легко отслеживать.

**Comment by furtivite** [comment]
@pepelsbey, @nlopin, @solarrust, @monochromer приглашаются в обсуждения.

**Comment by monochromer** [comment]
>  Робот должен пройтись по этому списку и сделать часть статьей зафичеренными

По какому признаку статья должна быть помечена как _featured_?

**Comment by monochromer** [comment]
Предложил бы хранить один достаточно большой список featured-статей и при сборке случайно доставать из него статьи.

**Comment by monochromer** [comment]
Ещё немного не по теме, но близко - выводить секции с недавно обновлёнными статьями и новыми статьями.

**Comment by nlopin** [comment]
У меня в голове представляется, что нужны только две сущности: пул зафичеренных материалов и прибитые материалы.

Прибитые показываются всегда на первых местах, а остальные добираются случайно из пула. Мы даже можем продолжать догружать статьи при клике на «Показать ещё» пока пул статей не закончится.

Мне нравится идея оставлять информацию связанную со статьей в самой статье, поэтому предлагаю эти флаги проставлять в метаданных статьи. Их очень удобно находить поиском по проекту:
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1469636/141528636-d7588644-04c5-49e9-8f82-5961bc37b473.png">

Альтернативно можно создать отдельный файл с метаданными для главной страницы.

Я против появления тегов в индексах статей — они большие, а тегами мы только увеличим их. Охватить одним взглядом все зафичеренные статьи не получится, а вот читать оглавление точно станет сложнее.

**Comment by monochromer** [comment]
> Мы даже можем продолжать догружать статьи при клике на «Показать ещё» пока пул статей не закончится.

Только там ничего не грузится - на страницу вставляется не больше 18 статей и они визуально открываются.
