### ISSUE TITLE
 Action "Surge Preview" делает начальную сборку для другого состояния (коммита)

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#752]
В [PR#2389 в контенте](https://github.com/doka-guide/content/pull/2389) в превью на Surge не сработала трансформация, описанная в PR #662

Сурж:

![сурж](https://user-images.githubusercontent.com/4408379/141296587-835fb7ca-5d68-4dbd-be29-f4013eb96dbd.png)

Локалхост:

![деплой](https://user-images.githubusercontent.com/4408379/141296537-3b239e79-1bb7-4359-943a-6d0150b16018.png)

Необходимо выводить трансформацию в предпросмотре, даже если у нас нет ресурсов на сжатие картинок.

**Comment by monochromer** [comment]
[В новых превью](https://doka-guide-content-pr-2550.surge.sh/css/grid-guide/) собралось корректно. Видимо, сборка идёт не для той версии, что в PR. Например, [в этом PR](https://github.com/doka-guide/content/pull/2550) был поправлен title c "Комментарии" на "Комментарии в CSS", но отображается старая версия заголовка.

**Comment by devcustrom** [comment]
> [В новых превью](https://doka-guide-content-pr-2550.surge.sh/css/grid-guide/) собралось корректно. Видимо, сборка идёт не для той версии, что в PR. Например, [в этом PR](https://github.com/doka-guide/content/pull/2550) был поправлен title c "Комментарии" на "Комментарии в CSS", но отображается старая версия заголовка.

Когда делал PR [html/nav](https://github.com/doka-guide/content/pull/2532) , первый раз на surge было собрано без моих правок, но после дополнительных коммитов сейчас там собралось со всеми изменениями

**Comment by monochromer** [comment]
Может быть, нужно использовать в качестве `ref` значение `github.event.pull_request.head.sha`?

**Comment by igsekor** [comment]
> > Видимо, сборка идёт не для той версии, что в PR
> 
> Может быть, нужно использовать в качестве `ref` значение `github.event.pull_request.head.sha`?

Это нам не подходит, ибо мы используем `pull_request_target`. Это не работает, я начал с этого.

**Comment by igsekor** [comment]
> [В новых превью](https://doka-guide-content-pr-2550.surge.sh/css/grid-guide/) собралось корректно. Видимо, сборка идёт не для той версии, что в PR. Например, [в этом PR](https://github.com/doka-guide/content/pull/2550) был поправлен title c "Комментарии" на "Комментарии в CSS", но отображается старая версия заголовка.

Как раз вот поправили экшен

**Comment by monochromer** [comment]
Переименовал issue, чтобы отразить причину, а не симптомы.

**Comment by igsekor** [comment]
Насколько я понимаю, ошибка уже исправлена?

**Comment by solarrust** [comment]
Кажется, эта проблема решена и превьюшки собираются правильно. Если вдруг будут замечены новые проблемы — заводим новые ишью. Потому что причина явно будет другой.
