### ISSUE TITLE
Фичеринг в подвале статей

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#753]
Необходимо сделать возможность перехода на предыдущую/следующую статью по списку в индексном-файле внизу статьи. 

Пример реализации [в документации по Vue@3](https://v3.vuejs.org/guide/instance.html#lifecycle-diagram)

![Screenshot 2021-11-12 at 14 44 13](https://user-images.githubusercontent.com/50330458/141462117-93030ecd-0be6-480a-b5d9-1a48e417a79c.png)

**Comment by furtivite** [comment]
@pepelsbey, @solarrust, @nlopin и все желающие приглашаются в обсуждения.

**Comment by furtivite** [comment]
Кажется, 
- если это первая статья в списке, можно в качестве предыдушей выводить ссылку на раздел. 
- если это последняя статья в списке, то на следующий раздел

## Вопросы
- Что делать, если у нас есть взаимосвязанные темы из разных разделов? Например, статьи про формы связывают JS и вёрстку
- Что делать, если автор, или редакция решит зафичерить определённую статью, которая будет полезна для понимания?

**Comment by monochromer** [comment]
> Что делать, если у нас есть взаимосвязанные темы из разных разделов? Например, статьи про формы связывают JS и вёрстку

А как они сейчас связаны в техническом плане?

Пример для документации Vue хорош, но там есть чёткая последовательность чтения. Как понимаю, в Доке связанные статьи можно читать в разнобой.

Предлагаю просто вставлять список со статьями (исключая текущую) из тематической группы.

**Comment by nlopin** [comment]
> А как они сейчас связаны в техническом плане?

Сейчас статьи из разных разделов никак не связаны, только если автор вручную проставил ссылки в тексте статьи. Статьи из одного раздела связаны через содержание

Мне нравится реализация, которую предлагает Егор, только без ссылок на разделы — раз мы находимся в статье, то следующий переход тоже должен быть в статью. 

Предлагаю переходить в первую статью следующего раздела, если закончился текущий. Получается:
- если это первая статья в списке, в качестве предыдушей выводить ссылку на первый материал предыдущего по индексу раздела и пометку с текстом «раздел Х»
- если это последняя статья в списке, в качестве следующей выводить ссылку на первый материал следующего раздела и пометку с текстом «раздел Y»

**Comment by solarrust** [comment]
Присоединюсь к Колином варианту. 
Если статья первая выводим ссылку на **последний** материал из предыдущего раздела. Можно в качестве обозначения использовать цветную подсветку, а не текст. Почему последний материал? Потому что пользователь, попав туда, должен увидеть ссылку на материал, из которого он только что пришёл. Чтобы можно было ходить по кругу, так сказать. Чтобы путь был предсказуемый.

Нарисовала простую схему:
![CleanShot 2021-11-19 at 13 39 47](https://user-images.githubusercontent.com/13676514/142609409-b1003aed-e6ab-4e0a-826d-1728b391e771.png)

**Comment by nlopin** [comment]
у нас тогда с тобой видение не совпадает в деталях. Поразмыслив, я согласен с твоим подходом

**Comment by monochromer** [comment]
В макете дизайн карточек для связанных (related) статей отличается от тех, что есть на главной. Вот пример при том же разрешении:
![image](https://user-images.githubusercontent.com/6412192/153585936-a0abc2ab-8d36-4972-a507-2738eb4e8fe8.png)
![image](https://user-images.githubusercontent.com/6412192/153585984-f8152355-432c-47ee-b5d9-43ab59194495.png)

В каких они взаимоотношениях? Создавать новый компонент или делать модификацию? 
Также в дизайне есть только разрешения 1366, 375. Остальные отсутствуют.

Для ссылок на статьи явно стоит проработать тёмную тему.

**Comment by monochromer** [comment]
Также в макетах картинки в карточках избранных статей сделаны каждая со своим размером. У нас задано правило, что картинки будут вписываться в квадрат.
