### ISSUE TITLE
Эмодзи превращается в юникод в колаутах

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#754]
Скрины из статьи «[Спред-синтаксис](https://doka.guide/js/spread/)»

Было в тексте:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/105274/141484714-f128dc06-8013-4fe2-b1e3-811a332902bc.png">

Стало на сайте

<img width="359" alt="image" src="https://user-images.githubusercontent.com/105274/141484755-497b4a4b-1ce4-4d0c-a837-779e34ce54e0.png">

Возможно, есть и другие примеры.

**Comment by monochromer** [comment]
Возможно, придётся перенести иконки в атрибут `data-icon`.
