### ISSUE TITLE
Добавить перенос строк в блоках с кодом для больших экранов

### ISSUE THREAD

**Issue by Ortiz1221** [doka-guide/platform#756]
У меня разрешение 1920 на 1080. Столкнулась с тем, что блоки с кодом приходится скроллить, чтобы полностью прочитать комментарии. 

![image](https://user-images.githubusercontent.com/41075682/141501984-48866ac9-01b4-4e33-9e26-847d12bee755.png)

**Comment by solarrust** [comment]
Мы пока не придумали, как автоматически переносить строки кода. Есть сложности с тем, что можно нечаянно сломать код. А один из наших основных принципов: «Копируй, применяй».

**Comment by pepelsbey** [comment]
Это поправили на уровне форматирования комментариев: просто перенесли на две строчки

<img width="814" alt="image" src="https://user-images.githubusercontent.com/105274/161861964-8a31c2fa-2b34-4346-bf31-87539e158b62.png">

Спасибо что принесли, пишите ещё :)
