### ISSUE TITLE
Автоматическая проверка битых ссылок

### ISSUE THREAD

**Issue by vitalybaev** [doka-guide/platform#769]
Битые ссылки появляются, это факт. С другой стороны, выглядит не очень сложной задачей добавить скрипт на Node.js, который будет проходиться по маркдаун файлам, искать там внутренние ссылки и просто проверять наличие соответствующих файлов.

**Comment by monochromer** [comment]
Проверка битых ссылок как раз таки есть и находится в github actions репозитория контента.

**Comment by vitalybaev** [comment]
Действительно, нашел экшен по проверке битых ссылок и вот что понял по текущему статусу:ъ

1. Используется два экшена - проверка маркдаун файлов и проверка собранного сайта.
2. Проверка маркдаун файлов фактически не работает ([пример](https://github.com/doka-guide/content/runs/4330856706?check_suite_focus=true#step:4:14)). Быстро разобраться, почему так - не получилось. С другой стороны, при наличии экшена проверки собранного сайта - текущий теряет свою полезность.
3. В проверке собранного сайта отсутствовали исключения `localhost`, `127.0.0.1`. Добавил их в ПР doka-guide/content#2518
4. Оставшаяся проблема с проверкой собранного файла - инструмент muffet, который используется для проверки ссылок, не умеет работать с srcSet в котором перечислены несколько URL. Попробую решить эту проблему в их репозитории, небольшой опыт на Go есть

**Comment by vitalybaev** [comment]
Совместно с автором экшена `ruzickap/action-my-broken-link-checker` исправили его работу с srcSet, теперь экшен работает как нужно и можно обращать на него больше внимания, так как в нем не будет потока лишнего мусора.
Плюс я в ПР уже упоминал - я предлагаю вообще убрать экшен `JustinBeckwith/linkinator-action@v1`, так как, во-первых, он сейчас фактически не работает, а во-вторых, необходимость в нем, я считаю, отпала, так как `ruzickap/action-my-broken-link-checker` работает хорошо.

**Comment by vitalybaev** [comment]
Проблемы исправлены
