### ISSUE TITLE
Поправить заголовок `Cache-Control` для статичных ресурсов (CSS, JS, картинки, шрифты)

### ISSUE THREAD

**Issue by monochromer** [doka-guide/platform#772]
Заголовок `Cache-Control` дублируется:
```
cache-control: max-age=31536000
cache-control: must-revalidate, public, max-age=31536000
```

Также нужно удалить `must-revalidate`.

**Comment by igsekor** [comment]
С первым полностью согласен, не досмотрел. Со вторым нет. Есть [рекомендации от Google](https://web.dev/uses-long-cache-ttl/?utm_source=lighthouse&utm_medium=lr).

**Comment by monochromer** [comment]
А где в этой рекомендации написано о совместном использовании `max-age` и `must-revalidate`?

**Comment by igsekor** [comment]
Вот на [этой картиночке](https://web-dev.imgix.net/image/tcFciHGuF3MxnTr1y5ue01OGLBn2/dGDjkwsoUBwFVLYM0sVy.png?auto=format&w=1600).

**Comment by monochromer** [comment]
А Microsoft, наоборот, не доволен:
![image](https://user-images.githubusercontent.com/6412192/142484635-41c204ef-180b-4bb1-8f99-c17b51fea74f.png)

**Comment by monochromer** [comment]
То есть получается, суть `must-revalidate` в том, что, если в момент запроса новой версии устаревшего ресурса, сервер окажется недоступен, то браузер обязан грохнуть и старый кэш. Если это js c бизнес-логикой, то это желаемое поведение, а вот CSS неплохо бы показать хоть какой-то.

**Comment by igsekor** [comment]
Если сервер окажется недоступен, то и сайт окажется не доступен со всем контентом. Вряд ли у пользователя закешированы все страницы сайта. Другое дело, что PWA это починит, что мы и собираемся сделать в ближайшее время.

**Comment by nlopin** [comment]
Мы собираемся делать PWA?

**Comment by igsekor** [comment]
> Мы собираемся делать PWA? 

Думаю, что да. Мы обсуждали и сошлись Натали, что это было бы очень удобно для разработчика. Не как повседневная практика (наверное). Популярность Dash сама о себе говорит.

**Comment by igsekor** [comment]
Все исправлено на данный момент! :)
