### ISSUE TITLE
Изменение темной темы

### ISSUE THREAD

**Issue by maff0702** [doka-guide/platform#786]
Привет!
Я любитель пользоваться темными темами, и когда захожу в доку через десктоп, то у меня сразу текст в глазах плывет в прямом смысле. Со светлой темой все норм, на мобилке темная тема тоже нормальная.
Попробуйте поиграть с фоном, либо со шрифтами что то придумайте. В общем у вас есть дизайнеры)

P.S. Зрение у меня идеальное.

**Comment by pepelsbey** [comment]
Привет, заходите в [существующую ишью](https://github.com/doka-guide/platform/issues/536) и давайте продолжим обсуждение там.
