### ISSUE TITLE
Отодвинуть обложку от подписи

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#788]
Необходимо не меняя размера блока с обложкой, уменьшить размер самой обложки так, чтобы она была отодвинута на некоторое расстояние от подписи. 

![photo_2021-12-01 17 42 31](https://user-images.githubusercontent.com/50330458/144255116-5385ccf7-ee9b-4a15-94c0-48482f1bad3e.jpeg)

А то у нас есть (или будут) обложки, которые могут задевать подпись или сливаться с ней.

**Comment by furtivite** [comment]
@monochromer, это Кира попросила сделать, скриншот дан просто для примера отступа, размер блока менять не надо.

**Comment by monochromer** [comment]
Странное условие. Если увеличить отступ между подписью и блоком, то размеры блока уменьшаться.

**Comment by furtivite** [comment]
> Странное условие. Если увеличить отступ между подписью и блоком, то размеры блока уменьшаться.

Имел в виду, чтобы обложка + подпись, как и раньше были по всей ширине контента.

Кажется, там можно обойтись тем, чтобы у `article-image__content` уменьшить ширину на `.5em`, но это не точно. Примерно так:

![Screenshot 2021-12-02 at 14 56 56](https://user-images.githubusercontent.com/50330458/144417748-1d51a554-d6ad-4e48-a458-08bf9429967d.png)

Тут тебе виднее.
