### ISSUE TITLE
При скролле наблюдается появление белой полоски в шапке меню

### ISSUE THREAD

**Issue by gladkym** [doka-guide/platform#790]
https://user-images.githubusercontent.com/49369823/144836175-26994b4e-11fa-46b7-aef6-73a014fbdac8.mov

Добрый день!
При скролле наблюдается появление белой полоски в шапке меню.
Устройство:iPhone 11

**Comment by monochromer** [comment]
Выглядит как элемент интерфейса ОС, а не сайта.

**Comment by xxtereshko** [comment]
Это нормально для сафари

**Comment by solarrust** [comment]
Спасибо большое за желание делать Доку лучше! ♥️
Пожалуйста, пиши, если увидишь ещё какие-то возможности для доработки. Эту задачку закрываю.
