### ISSUE TITLE
Нет анимации исчезновения шапки

### ISSUE THREAD

**Issue by cergmin** [doka-guide/platform#808]
Если мы почти доскролили до верха страницы, то шапка просто пропадает, без анимации.

https://user-images.githubusercontent.com/21996065/145658089-c879d261-7d77-4395-9244-af534b6d84bc.mp4

**Comment by devcustrom** [comment]
Любопытно, что на локалке этой проблемы нет, и вот [action](https://github.com/doka-guide/platform/actions/runs/1564476162) который это фиксит. Возможно на продуктовом сервере не актуальная версия или это проблема из этой [темы](https://github.com/doka-guide/platform/issues/752)
