### ISSUE TITLE
Не работает прокрутка до anchor-блока

### ISSUE THREAD

**Issue by cergmin** [doka-guide/platform#818]
Кажется, что не только Chrome "не прокручивает до anchor-блока, если в адресной строке нажать enter", но и другие браузеры на базе Chromium. По крайней мере, такая проблема наблюдается и в Яндекс Браузере. Может убрать проверку isChrome?

https://github.com/doka-guide/platform/blob/89b55969d719b0316f908d9bb9a6b717d452b1a3/src/scripts/modules/articles-index.js#L49-L59

**Comment by xxtereshko** [comment]
Chrome 98, все в порядке.

**Comment by cergmin** [comment]
@xxtereshko, ну если я правильно всё понимаю, то это потому что специально для хрома добавлен фикс.
К тому же, проблема воспроизводится, по крайней мере у меня, только если дока уже открыта, а я нажимаю на адресную строку, дописываю к url хэш и нажимаю enter.
