### ISSUE TITLE
Битая картинка деплоя в Ридми

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#821]
У нас со времён Netlify осталась картинка, адрес которой переименовали массово. Теперь картинка битая.

Может убём её?

![Screenshot 2021-12-17 at 15 24 09](https://user-images.githubusercontent.com/50330458/146544387-a5c9a7f0-004f-44e7-9a3b-ac521d97c740.png)

**Comment by pepelsbey** [comment]
Эта картинка побилась потому, что экшен переименовался. Netlify давно выпилили
