### ISSUE TITLE
Настроить Prettier 

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#825]
Создано по итогам [дискуссии](https://github.com/doka-guide/platform/discussions/797) 

Нужно добавить в проект Prettier так, чтобы он работал совместно с eslint и не конфликтовал (`eslint-prettier`). Запускать на прекоммит хук и форматировать только staged файлы. Для этого можно воспользоваться минималистичным [nano-staged](https://github.com/usmanyunusov/nano-staged).

Конфиг стоит настроить так, чтобы минимально повлиять на текущий код. Конфиг примерно такой, но во время выполнения нкжно посмотреть, точно ли он подходит:

```
{
  "printWidth" : 120, // тут стоит проверить, может и 80 ок
  "semi": false,
  "singleQuote": true,
}
```

**Comment by pepelsbey** [comment]
@edbond88 заходи и хватай, если интересно :)

**Comment by pepelsbey** [comment]
> `"printWidth" : 120`

Может сделаем `"printWidth" : Infinity` или какое-то другое большое значение? Мне это кажется диковатым правилом. Я погуглил, оно не отключается совсем.

**Comment by nlopin** [comment]
Оно там не совсем в лоб работает, поэтому нужно посмотреть, насколько будет норм со 120

**Comment by edbond88** [comment]
Отлично! Я тогда беру таску. 

Есть вопрос по гит хокку. На хук вешаем именно еслинт фикс или только чек на ошибки и фикс уже ручками делаем?

**Comment by edbond88** [comment]
@nlopin у нас уже используется `lint-staged`. Заменить его на `nano-staged`?

**Comment by edbond88** [comment]
Предлагаю разделить на 2 таски и пул реквеста, чтобы проще было делать ревью:
1. Добавление и настройка prettier с eslint. Добавление git хуков
2. Фикс всех js файлов
