### ISSUE TITLE
Сделать кнопки фильтра на манер чекбоксов

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#826]
# Проблема

- Нельзя отжать фильтр категории в поиске
- Нельзя поискать по двум и больше категориям

# Как так?

Если что-то поискать, то попадаешь в режим «всё сразу»:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/105274/146599741-52c85ae4-db99-492e-99c1-b3cecd85b9d7.png">

Тут, на самом деле, должны быть выделены все 4 кнопки, они же включены!

Если потом нажать CSS, то получаешь только его:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/105274/146599791-732f8daf-6752-4291-89fc-f566dc7cc2cc.png">

И нельзя никак выбрать только HTML и CSS, например.

# Предложение

Чтобы при загрузке были выделены активными все четыре фильтра:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/105274/146600407-57d973a3-0c6a-4817-86a9-e6ffdc731b6c.png">

И если я хочу перестать искать по JS и инструментам, я их сниму:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/105274/146600453-64327bcd-9fac-4127-9204-5d0b9729e63c.png">

Кажется, что решается это всё заменой `radio` на `checkbox` и обработкой этой логики.

**Comment by pepelsbey** [comment]
@solarrust как тебе такое решение твоей задачи #421?
@monochromer а ты что скажешь?

**Comment by monochromer** [comment]
[Здесь](https://github.com/doka-guide/platform/pull/798) это уже решается
