### ISSUE TITLE
В альты к картинкам пролезают HTML-комментарии

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#836]
```html
<img class="article-image__content" src="images/covers/desktop.svg"
  alt="Два человека, один панк и <!-- yaspeller ignore:start -->
    растатуирован div`ами<!-- yaspeller ignore:end -->,
    а второй удивляется, открыл рот"
  itemprop="image" width="1920" height="1080">
```

**Comment by monochromer** [comment]
Что написано, то и прилетает:
```yaml
alt: 'Два человека, один панк и <!-- yaspeller ignore:start -->растатуирован div`ами<!-- yaspeller ignore:end -->, а второй удивляется, открыл рот'
```

**Comment by pepelsbey** [comment]
Так-то да, но можно ли это как-то чистить при выводе? Кажется это нужно.

**Comment by monochromer** [comment]
Понятно, что хочется экранировать только часть фразы, но я бы обернул весь атрибут:

```yaml
# <!-- yaspeller ignore:start -->
alt: ''
#<!-- yaspeller ignore:end -->
```

Анализировать атрибуты можно не только при сборке, но и при создании индекса, например, и нужно во всех таких местах добавлять поддержку служебных комментариев.

**Comment by pepelsbey** [comment]
То есть лучше закрыть ишью и следить глазами?

**Comment by furtivite** [comment]
Могу забивать общий словарь исключениями, которые больше нигде не используются. Потому что спеллер ругается. Я отчего-то был уверен, что так выделять нормальная практика.

**Comment by pepelsbey** [comment]
> Могу забивать общий словарь исключениями, которые больше нигде не используются. Потому что спеллер ругается. Я отчего-то был уверен, что так выделять нормальная практика.

Я бы лучше старался делать описания, которые не вываливаются из словаря :)

**Comment by furtivite** [comment]
> > Могу забивать общий словарь исключениями, которые больше нигде не используются. Потому что спеллер ругается. Я отчего-то был уверен, что так выделять нормальная практика.
> 
> Я бы лучше старался делать описания, которые не вываливаются из словаря :)

Давай я поправлю все описания в ближайший понедельник? И заберу issue себе тогда?

**Comment by monochromer** [comment]
>  То есть лучше закрыть ишью и следить глазами?

Вместо html-комментариев нужно использовать yaml-комментарии:
```html
<!-- yaspeller ignore:start -->
```

```yaml
# yaspeller ignore:start
```

Проблема в том, что у yaml нет инлайновых комментариев.

**Comment by furtivite** [comment]
Может проверим тогда работу `# yaspeller ignore:start` и если такой способ окажется примемлемым, опишем его в документации?

**Comment by monochromer** [comment]
> Может проверим тогда работу `# yaspeller ignore:start` и если такой способ окажется примемлемым, опишем его в документации?

yaml-комментарии будут скорее всего добавлять весь alt в игнорирование, но других способов я не знаю.

Вижу, alt'ы поправили. Закрываем?

**Comment by solarrust** [comment]
Решили не обрабатывать автоматически
