### ISSUE TITLE
Элемент <code> раздвигает высоту строки

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#838]
B итоге строка отваливается от абзаца и возникает ощущение, как будто она отделена. Наверное можно компенсировать высоту булочки с кодом с помощью отрицательных отступов. Или может быть нарисовать скругление с помощью outline или box-shadow, что не будет влиять на размеры?

Эмоджи в примере ниже тоже, кстати, раздвигает. Но совсем чуть-чуть.

![image](https://user-images.githubusercontent.com/105274/147243853-e8fff61a-7b3c-4f5a-ab80-6357ee7f7918.png)

**Comment by monochromer** [comment]
Проблема в разных line-height

**Comment by furtivite** [comment]
<img width="430" alt="Screenshot 2021-12-24 at 14 07 10" src="https://user-images.githubusercontent.com/50330458/147347751-d33f6061-dfa8-411a-96bf-20b506c9b08f.png">

@monochromer, кажется, на главной проблема сохраняется

**Comment by monochromer** [comment]
> на главной проблема сохраняется

никто ничего ещё и не правил

**Comment by monochromer** [comment]
> Проблема в разных line-height

...ну в размерах шрифта
