### ISSUE TITLE
Не работает отправка оценки полезности статьи

### ISSUE THREAD

**Issue by vitalybaev** [doka-guide/platform#841]
Не знаю, куда писать, оставлю здесь.

<img width="502" alt="CleanShot 2021-12-24 at 22 59 39@2x" src="https://user-images.githubusercontent.com/724423/147370915-f3ed5abd-df4a-4486-ac34-f2de009c6574.png">

Ошибка при запросе `OPTIONS https://api.doka.guide/form`

**Comment by vitalybaev** [comment]
Все уже работает

**Comment by furtivite** [comment]
@monochromer, @igsekor форма снова сломалась.

**Comment by igsekor** [comment]
> @monochromer, @igsekor форма снова сломалась.

Да работает всё вроде

**Comment by vitalybaev** [comment]
Вообще, очень похоже, что [вот это](https://github.com/doka-guide/content/runs/4624710988?check_suite_focus=true) связано.

**Comment by igsekor** [comment]
> Вообще, очень похоже, что [вот это](https://github.com/doka-guide/content/runs/4624710988?check_suite_focus=true) связано.

Ну это совсем разные механизмы. А ошибку, которая возникла, починим. Обнаружились тонкости реализации инфраструктуры.
