### ISSUE TITLE
Разное междустрочное расстояние в `aside` с инлайн кодом и без

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#854]
Допускаю, что это иллюзия, но кажется, что строки с инлайновым кодом и без имеют разные высоты. Из-за этого скачет межстрочное расстояние в блоках:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1469636/147761020-bf51f41a-da99-4308-8ecc-a782a9e2d367.png">

**Comment by monochromer** [comment]
Дубликат #838
