### ISSUE TITLE
Попап об использовании cookie на мобильном

### ISSUE THREAD

**Issue by Spearance** [doka-guide/platform#855]
Если сразу перейти в статью и пролистать вниз, то нельзя согласиться с использованием кук, потому что вместо этого выскакивает меню, хотя оно под попапом. Похоже с z-index проблема

**Comment by pepelsbey** [comment]
Если не сложно, добавьте подробностей про браузер, устройство. Лучше со скриншотом, а идеально — с видео. В текст на Гитхабе можно кидать и виде, и картинки — они загрузятся и вставятся. Спасибо!

**Comment by Spearance** [comment]
Android, FireFox 94.1.2
![1641446355777](https://user-images.githubusercontent.com/5271553/148332561-0dad56f2-a0f0-482d-be4e-eb652a205fb8.jpg)
На скрине видно, я нажал «хорошо» а открылось меню и повторный клик ситуацию не меняет. Но если отмотать вверх, где картинка, то куки принимаются нормально.
На всякий, открывал статью про <input>

**Comment by monochromer** [comment]
@Spearance проверьте - [здесь](https://doka-guide-platform-pr-860.surge.sh/) должно быть без проблем.

**Comment by Spearance** [comment]
@monochromer  нет, также

**Comment by monochromer** [comment]
Поисследовал вопрос - нашёл [такой баг для мобильного Firefox](https://github.com/mozilla-mobile/fenix/issues/19217). Поэтому быстрый фикс - вернуть `position: fixed` вместо `position: sticky`. От него, правда, [хотели уйти](https://github.com/doka-guide/platform/issues/516).
