### ISSUE TITLE
Поиск выдаёт две ссылки на статью про PixelPerfect

### ISSUE THREAD

**Issue by cergmin** [doka-guide/platform#856]
Если вбить в поисковой строке PixelPerfect, то мы получим две ссылки на одну и ту же статью. Та, которая ссылается на раздел html – некоректная.
![image](https://user-images.githubusercontent.com/21996065/147873562-335a7635-3e7c-445a-a10c-697dad9458b8.png)

**Comment by pepelsbey** [comment]
Спасибо! Залипло содержимое индекса — мы перемещали статью между разделами.

**Comment by monochromer** [comment]
Дубликат удалён.
