### ISSUE TITLE
Возврат назад к якорю всегда возвращает скролл к нему

### ISSUE THREAD

**Issue by vitalybaev** [doka-guide/platform#859]
**Для воспроизведения:**

1. Открыть любой URL с якорем
2. Проскролить в любое другое место до какой-нибудь ссылки на другую страницу
3. Перейти по этой ссылке на другую страницу
4. Вернуться назад

**Фактический результат:**

Несмотря на то, что я ушел от якоря достаточно далеко и уходил со страницы в другой позиции скролла, скролл восстановится к якорю.

**Ожидаемый результат:**

Меня вернёт в то место, в котором я уходил со страницы

Видео:

https://user-images.githubusercontent.com/724423/148350828-53333d75-3ba7-4317-9de1-3ec040d084ab.mp4

**Comment by pepelsbey** [comment]
В Chrome и Safari возврат по истории назад на страницу с якорем не триггерит прокрутку к якорю. Так работает только в Firefox. Насколько я понимаю, это особенности работы браузера и мы тут ничего не делаем дополнительноого. Правда, @monochromer?

**Comment by monochromer** [comment]
У нас программно скролится.

**Comment by monochromer** [comment]
Попробуйте отключить все расширения в Firefox, кроме блокировщика рекламы, и проведите тест. Повторяется?

**Comment by vitalybaev** [comment]
Да, попробовал абсолютно чистый Firefox Nightly, в том числе - результат тот же

**Comment by monochromer** [comment]
> Да, попробовал абсолютно чистый Firefox Nightly, в том числе - результат тот же

С **включенным** блокировщиком рекламы? (на видео, как понимаю, был UBlockOrigin)

**Comment by vitalybaev** [comment]
На видео - да. Но только что попробовал чистый Firefox Nightly без единого расширения. Все равно результат тот же

**Comment by monochromer** [comment]
> без единого расширения

Давайте ещё раз - попробуйте отключить все расширения в Firefox, **кроме блокировщика рекламы**.

**Comment by vitalybaev** [comment]
Бинго - если оставить только uBlock Origin, то все работает как нужно 🤔

**Comment by edbond88** [comment]
Я проверял на чистом ФФ  и у меня при нажатии на кнопку "назад", **не** скроллит к якорю.

FF: 96.0.1 (64-bit)
![image](https://user-images.githubusercontent.com/1949927/149641022-e3579f0c-5776-4863-8685-082b4864dff3.png)

**Comment by monochromer** [comment]
> Я проверял на чистом ФФ и у меня при нажатии на кнопку "назад", **не** скроллит к якорю.
> 
> FF: 96.0.1 (64-bit) ![image](https://user-images.githubusercontent.com/1949927/149641022-e3579f0c-5776-4863-8685-082b4864dff3.png)

А не стоит ли повышенная защита от отслеживания? Не блокируются ли запросы аналитики?

**Comment by edbond88** [comment]
Все дефолтные настройки. Какая-то аналитика блочится

![image](https://user-images.githubusercontent.com/1949927/149655453-1721dda3-f087-4344-b822-7a5be55630f8.png)
![image](https://user-images.githubusercontent.com/1949927/149655460-0876fd22-50ec-43a5-8d45-993e30507fcc.png)
![image](https://user-images.githubusercontent.com/1949927/149655464-d421eb4d-2fcb-4e9b-b926-00d8177fe22e.png)
![image](https://user-images.githubusercontent.com/1949927/149655486-119dc12f-c60c-496b-a1a0-8e8c8028115e.png)
![image](https://user-images.githubusercontent.com/1949927/149655516-f3a29124-e650-4610-ba56-932bf3b5826e.png)
