### ISSUE TITLE
Показывать превью цвета рядом с кодом в тексте

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#895]
Задачка из разряда Just for fun! 🙌

Было бы прикольно выводить превью цвета рядом с кодом в тексте статей. 
Есть несколько визуальных решений (подсмотрено в редакторах):
- Окрашивать весь код цвета в этот самый цвет ([пример](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fraw.githubusercontent.com%2Fap%2Fvim-css-color%2F5377c65022ee6d660b898bad954aeea73fa613b8%2Fscreenshot.png&f=1&nofb=1))
- Показывать маленький квадратик рядом с кодом цвета ([пример](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcode.visualstudio.com%2Fassets%2Fupdates%2F1_16%2Fcolor-picker-html.png&f=1&nofb=1))

Вижу потенциальную сложность в необходимости парсить текст и выискивать там цвета. При этом не хочется добавлять какие-то дополнительные пометки в сам текст чтобы не усложнять работу авторов и редакторов.

Но это довольно прикольная штука =)

**Comment by TatianaFokina** [comment]
Превью есть для всех цветов, кроме `rgb`. Этот вопрос пока остаётся открытым.
