### ISSUE TITLE
Проблема с переходом в поле поиска

### ISSUE THREAD

**Issue by igsekor** [doka-guide/platform#901]
При загрузке главной страницы нельзя поставить мышкой курсор в поле поиска. Клавиатура при этом работает.

**Comment by monochromer** [comment]
Не могу воспроизвести ни в одном из трёх браузеров. Может, есть более подробные условия?

**Comment by igsekor** [comment]
> Не могу воспроизвести ни в одном из трёх браузеров. Может, есть более подробные условия?

Забыл написать, это был актуальный Safari.

**Comment by monochromer** [comment]
@pepelsbey @furtivite @nlopin у кого-то ещё повторяется? Если да, то какая ОС?

**Comment by furtivite** [comment]
macOS 12.2.1 с актуальными версиями сафари, хрома и firefox проблемы не увидел.

**Comment by edbond88** [comment]
@igsekor пробовал в инкогнито режиме? Может аддон какой-то блочит?

ps: тоже не смог смоделировать

**Comment by igsekor** [comment]
Да нет аддонов вообще никаких. Буду искать причины у себя. Я сам удивлён, что это не работает.

**Comment by igsekor** [comment]
Эта проблема оказалась у моего Safari. Извините)
