### ISSUE TITLE
При скролле страницы вниз, заголовки вида h3 так-же скроллятся вниз.

### ISSUE THREAD

**Issue by SlavaLysjuk** [doka-guide/platform#905]
**Шаги**

1. Открыть любой раздел doka.guide, например https://doka.guide/html/ или https://doka.guide/tools/
2. Скролить вниз по странице.

**Ожидаемый результат:**
Заголовки вида h3, не скролляться вниз по странице

**Фактичский результат:**
Заголовки вида h3, скролляться вниз по странице.

**Окружение:**
Linux Ubuntu 20.04.3 LTS
Chrome Версия 96.0.4664.110 (Официальная сборка), (64 бит)

https://user-images.githubusercontent.com/30052608/154842458-943af2ee-65c6-4bb8-aeb1-46223f9e07a6.mp4

https://user-images.githubusercontent.com/30052608/154842462-e02314b5-c302-43f8-989b-5723fc68ba90.mp4

**Comment by vovaklimov** [comment]
Я думаю, существующее поведение как раз является ожидаемым. Эти подзаголовки нужны чтобы показать к какой теме относится та или иная статья в списке.

**Comment by igsekor** [comment]
Большое спасибо за вопрос и обсуждение. Мы долго пытались понять, как будет лучше, и пришли к текущему варианту. Так удобнее осуществлять навигацию нашим читателям.
