### ISSUE TITLE
Невозможно отправить обратную связь под статьей

### ISSUE THREAD

**Issue by totfront** [doka-guide/platform#906]
При отправке лайка / дизлайка статьи происходит ошибка. Возможно, обратная связь и отправляется, но интерфейс сообщает обратное.

![image](https://user-images.githubusercontent.com/42805085/155326898-2b49e092-622c-4306-ab4a-cdb98dfdbb4d.png)

Протестировано:
1. Chrome (98.0.4758.102 (64 бит))
2. Firefox (97.0.1 (64-bit))

**Comment by igsekor** [comment]
Большое спасибо! Как раз работали над этим. Теперь всё работает!

**Comment by totfront** [comment]
На текущий момент не работает:
![image](https://user-images.githubusercontent.com/42805085/155343596-ed6416c4-6b2a-4c10-860b-b8baff125966.png)

Возможно, в staging (или аналогичном) репозитории.

Если расскажете (или покажете коммит), как поправили - буду очень признателен. Хотел законтрибьютить, но запутался в корс-запросах.

**Comment by totfront** [comment]
Ясно, спасибо.

Сейчас всё работает 👌
