### ISSUE TITLE
Появляется вертикальная прокрутка у блока с кодом

### ISSUE THREAD

**Issue by cergmin** [doka-guide/platform#907]
В Chrome на андроид появляется вертикальная микропрокрутка у блоков с кодом, хотя это не должно происходить, потому что они не ограничены по высоте.

https://user-images.githubusercontent.com/21996065/155454441-7e1c95c4-ad92-4660-a287-612e74928404.mp4

**Comment by cergmin** [comment]
Нет, сейчас ничего такого больше не наблюдается

**Comment by TatianaFokina** [comment]
> Сейчас ничего такого больше не наблюдается

Тогда закрываем ишью или исследуем эту проблему дальше?
