### ISSUE TITLE
Не работает ссылка на github в футере

### ISSUE THREAD

**Issue by atnartur** [doka-guide/platform#915]
На странице https://doka.guide/ в футере не открывается ссылка на github. При нажатии идет переход на https://doka.guide/DOKA_ORG.

Скорее всего связано с https://github.com/doka-guide/platform/commit/d52dc3352958ce1e5f1ac54630cbf60fdd17342b

**Comment by furtivite** [comment]
@atnartur спасибо, да, ошибка, действительно есть. Пришлёте пиар, который поправит?

**Comment by atnartur** [comment]
Есть два способа решения:
1. указать значение по умолчанию в конфиге https://github.com/doka-guide/platform/blob/main/config/constants.js#L9 (могу прислать PR)
2. указать значение в переменных окружения в настройках деплоя в github actions (доступно только администраторам репозитория)

Подойдет первый вариант решения?

**Comment by furtivite** [comment]
@atnartur, смогу вернуться с решением через некоторое время.

**Comment by atnartur** [comment]
<img width="1440" alt="изображение" src="https://user-images.githubusercontent.com/5189110/159258384-99a8b48a-0491-4399-8383-9e3720f5bc5b.png">

Речь шла о ссылке в футере. Видимо последний [деплой](https://github.com/doka-guide/platform/actions/runs/2004142697) все поправил, сейчас все хорошо.

**Comment by furtivite** [comment]
До меня, видимо, апдейт не докатился ещё. Пока работает так, как в issue
