### ISSUE TITLE
Ссылки на социальные сети

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#920]
У нас на сайте Доки нет ссылок на наши социальные сети. Это, кажется, не ОК. Давайте добавим?

1. «Стандартный» вариант: иконки в подвале или где-то ещё.
2. На странице [«О проекте»](https://doka.guide/about/) в раздел «Ваш ход» или другой, добавить текст, «А ещё на нас можно подписаться в контакте, твиттере ~~и на фейсбуке~~»

**Comment by TatianaFokina** [comment]
Обсуждали это и есть мнение, что ссылки на соцсети в футере будут его «засорять».

Но вот идея с добавлением такого раздела со списком ссылок на соцсети на странице про проект мне нравится. Есть какие-то аргументы против этой идеи?
