### ISSUE TITLE
В боковом меню не форматируется текст заголовка

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#932]
В статье [ООП](https://doka.guide/js/oop/#nasledovanie-kompoziciya) есть заголовок «~Наследование~ Композиция». В боковом меню слово Наследование не зачёркивается и заложенный автором эффект пропадает. Нужно ли нам реализовать форматирование заголовков в боковом меню или перебор?

@nlopin @igsekor @bespoyasov @pepelsbey @tachisis приглашаю к обсуждению.

**Comment by pepelsbey** [comment]
Идеально было бы пойти навстречу автору и попытаться внедрить такое форматирование. Но кажется дискуссия шире: а если там ссылка, курсив, жирный текст, что-то ещё? Лучше разрешить только некоторые теги, например, только зачёркивание.

Если внедрение окажется слишком сложным, то можно попросить автора упростить. Но я бы сначала попытался.

**Comment by bespoyasov** [comment]
Да, в общем-то, можно и словами это обыграть, если есть ограничения. Как вариант:

> Не наследование, а композиция ☝️

**Comment by solarrust** [comment]
@nlopin @igsekor @tachisis выскажитесь, пожалуйста

**Comment by tachisis** [comment]
Я бы избегала зачеркиваний и прочего такого в заголовках. Заголовок не только несет смысл, но еще и работает как визуальный разделитель, а в оглавлении — как адресный указатель. Он должен быть четким, ясным. Поэтому такие вещи я бы исправляла на этапе редактуры. Вот Саша предложил хорошую замену (только эмодзи тоже лишний)))

**Comment by TatianaFokina** [comment]
Думаю, что можно закрыть ишью. Это лучше решать на уровне редактуры, да и такие ситуации с зачёркиванием в боковой навигации редко возникают.
