### ISSUE TITLE
Картинки для шеринга в социальных сетях

### ISSUE THREAD

**Issue by skorobaeus** [doka-guide/platform#938]
На созвоне сочли вариант с повёрнутой на 45° и увеличенной иллюстрацией самым перспективным:

![tilt2](https://user-images.githubusercontent.com/29401439/172136213-fbec193c-be3d-42d1-adf3-1b65300edde0.png)

Алёна предложила сверкнуть брендом. Я попробовала разные варианты, и самым хорошо считываемым визуально мне кажется вариант просто со словом Дока: 

![tilt2name](https://user-images.githubusercontent.com/29401439/172136727-62cd5777-c4d2-4fc4-aaff-88f70c0edac1.png)

Также нужен вариант для статей, у которых пока нет иллюстрации. Кира предложила нарисовать несколько иллюстраций. Пока же есть вариант с булочкой и Докой. Минусы: однообразно. Плюсы: тренирует у читателей связку булочка=дока.

![заглушка для статей без иллюстрации](https://user-images.githubusercontent.com/29401439/172137297-540c9d11-1ee0-419d-8203-60e910e8d921.png)

Посмотреть процесс и промежуточные варианты можно в фигме: https://www.figma.com/file/o41lYEhfZwsvQt6PkshmxH/?node-id=822%3A334

**Comment by solarrust** [comment]
Можно на заглушках использовать разные состояния Булочки. В сочетании с разными цветами разделов будет создавать разнообразие.

**Comment by solarrust** [comment]
Попробую описать принцип генерации картинки в соц.сети для отдельного материала:
1. Если есть обложка:
  - Берём обложку. **Надо проверить**: лучше брать мобильную или десктопную обложку.
  - Увеличиваем на х1.5 / х2 (тут надо поэкспериментировать).
  - Поворачиваем на 45 / -45 градусов (можно чередовать для разных разделов).
  - Добавляем в левый нижний угол слово «Дока». Кажется, тут лучше сделать на подложке, чтобы исключить случаи когда в этом месте на обложке есть элементы, затрудняющие чтение. Можно использовать чёрный (возможно, с прозрачностью 0.8-0.7) овал как у Булочки.
2. Если нет обложки:
  - Берём цвет раздела
  - Из набора заготовленных Булочек рандомно выбираем любую.
  - Добавляем слово «Дока».
  - Ставим это всё в ряд по центру картинки.

@skorobaeus поправь, пожалуйста, если я где-то неверно описала логику.

@nlopin @pepelsbey @pa7lux @igsekor @igsekor посмотрите и давайте обсудим ОК или не ОК такой принцип генерации.

**Comment by pa7lux** [comment]
Привет, 

сначала хочется сказать, что картинки в примерах невероятно красивые. Я это как опытный медоед говорю 🍯

По вопросу такие мысли.

В текущем состоянии превью иллюстрация забирает на себя очень много внимания. Превьюха устроена так, что «медовый» вижуал отнял весь фокус от надписей «переменные const, let и var». Представляю сценарий, когда мне скидывают эту ссылку где-то в мессенджере или вижу это в ленте. Из этой превьюхи я получаю информацию о том, что мне скинули, со второго взгляда, а не с первого. 

Проблему немного решает размещение слова «Дока» на обложке. Если сделать её однозначно заметной (Алёна предлагает чёрную подложку со скруглёнными углами), я пойму, что мне скинули ссылку на некоторую документацию, потому что обывательски я знаю слово «Дока» не как имя проекта, а как ласковое сокращение для любой документации.

Скорее всего нам хочется, чтобы простраивалась связь между обложкой и нашим проектом. Чтобы пользователь понимал, что за подобного рода контентом нужно идти на doka.guide и что слово «Дока» в данном контексте привязано именно к проекту с дружелюбной документацией по веб-платформе. Увы, в превью нет ни демонстрации url, ни формулировки, привязывающей статью к её источнику.

Я бы предложил всё же покрутить вариант с добавлением бОльшей смысловой нагрузки в изображение. Например, написав как-то аккуратно  

```
Дока
дружелюбный гид по веб-платформе
```

...или eщё какой-то важный для нас слоган. Так бы мы в первом касании создадим ассоциацию, что проект Дока — это вот именно такой проект и в нём вот такая полезная статья, как по клику. 

Если при этом где-то написать не менее аккуратно "doka.guide", в первом фокусе появится ещё и мотивация к запоминанию адреса, куда надо ходить за подобным контентом. Тогда, даже если пользователь не откроет ссылку, он все равно подсознательно запомнит эти посылы.

Я понимаю, что предлагаю много текста на картинке, это может оказаться сложным в плане дизайна. Поэтому дважды написал «аккуратно». может оказаться, что аккуратно такое не получится, и тогда надо выбросить эти идеи

**Comment by furtivite** [comment]
Я бы не писал слово «Дока» на картинке потому, что Дока у нас есть в `title`, которое состоит из названия статьи + раздел + Дока (на примере с мёдом это просто не указано). А то получается Артур, Артур, Артур... 

Могу согласиться с Сашей, что если бы мне скинули ссылку на статью про переменные, я бы уже потом понял, что это за статья из документации, с другой стороны, я слишком много пользуюсь Докой и уже привык к визуальному стилю и могу определить что это. 

К тому же, разве обычно в переписках люди не добавляют описание того, что они скидывают? «Хай, глянь статью про переменные ты искал: ТЫЦ», «Нашел статью в Доке на тему, глянь: БАМС». 

Если говорить про то, что в описании сразу идёт description, то можно сделать автоматом для внешних ссылок добавление в начале: «doka.guide: Тег для создания...» — а на главной странице это самое добавление не выводить совсем.

**Comment by pa7lux** [comment]
Вот очень некрасивый набросок. Несмотря на то, что все дублируется в тайтле, кажется показывать логотип — круто

При этом может хорошо работать связка, когда к тайтлу внимание подводится дополнительным акцентом с объяснением, про что эта статья, например про JS. 

Формируется связка Дока —> рассказывает про JS —> мне кидают ссылку про переменные

<img width="440" alt="image" src="https://user-images.githubusercontent.com/6544403/173068410-058f2b49-581b-472f-847a-c30a85feb87b.png">

**Comment by solarrust** [comment]
Если пытаться поместить на картинку так много инфы, то лучше смотреть в сторону превью GH:

<img width="440" alt="CleanShot 2022-06-14 at 11 07 36@2x" src="https://user-images.githubusercontent.com/13676514/173515247-eca73bc2-d42c-4a9c-a375-2127c920f85e.png">

Но у них много воздуха, чистый фон. Обложка при таком количестве доп.информации тут никак не вписывается.

**Comment by skorobaeus** [comment]
Саша, Егор, Алёна, спасибо за комментарии по UX и за примеры. Я принесла ещё пару вариантов, в которых:

- добавляется Дока и / или doka.guide;
- добавляется "твой гид по...";
- сохраняется обложка.

Краткий дисклеймер почему я решила не добавлять надписи поверх картинки:

![v2-why-not](https://user-images.githubusercontent.com/29401439/173566205-d32cdce2-4d90-41bf-9d2a-c8ac8ea5d2ac.png)

При автоматической генерации подложки будут случайно соприкасаться с линиями на картинке, создавая неприятные глазу углы. Подложка со скруглёнными краями воспринимается как часть изображения, т.к. Кира активно использует похожую форму в иллюстрациях.

Поэтому я поставила элементы рядом:

![v2-link](https://user-images.githubusercontent.com/29401439/173567270-7008efd9-b217-4e09-8e08-0eed7c1c02dd.png)

![v2-doka](https://user-images.githubusercontent.com/29401439/173567289-333e6d6d-ef14-4f8a-990c-246fbec27553.png)

Наконец-то пригодился уголок! :D Мне кажется, он очень устойчивый и тяжелый, и срабатывает как указатель: читать вот здесь 👇

Прожала эту мысль, запрокинула обложку ещё сильнее, добавила линк:

![v2-push-it](https://user-images.githubusercontent.com/29401439/173567548-899a4dce-b55a-4c19-92ba-5a6c301e1a60.png)

Весь текст поместился и картинка дерзит. Но видна только нижняя часть иллюстрации, сюжет не считывается и иллюстрация становится абстрактной. Особенно хорошо это показывает голубой пример выше — мало кто догадается, но на самом деле там [медведь](https://doka.guide/css/display/).

---

И спокойный вариант, обыгрывающий квадратную форму мобильной версии обложки:

![squares2](https://user-images.githubusercontent.com/29401439/173568883-20b2e74d-1b24-430f-a5d8-ce77281ce771.png)

![squares](https://user-images.githubusercontent.com/29401439/173568880-5e9b2e3d-3d69-4c85-8280-5b603d349121.png)

Здесь черный квадрат направляет внимание.

**Comment by solarrust** [comment]
Выскажу личное мнение:
1. Мне нравится лэйаут с квадратом.
2. Много чёрного сперва смущало, но после довода @furtivite я соглашусь, что это наименее болезненный для глаз пользователя вариант.
3. Надо понять, как пристроить «твой гит по» к разделам рецептов и инструментов.
4. Каааажется, что можно пристроить мордашку Булочки очень аккуратно, без обводки куда-нибудь в верхний левый угол. Типа пасхалочки. Будто бездна смотрит в душу 😄
Но это предположение. Надо смотреть по дизайну =)

**Comment by pa7lux** [comment]
Ваш гид по HTML/CSS/JavaScript
Гид по инструментам/рецептам веб-разработки

слово гид помогает запомнить домен

**Comment by skorobaeus** [comment]
Останавливаемся на квадратном варианте?

Мордашку в уголок пристроить можно:

![squares-fin](https://user-images.githubusercontent.com/29401439/176204558-760d73f3-3c99-4626-863e-432074852a97.png)

Но я бы, думаю, не стала, т.к. у неё будет шанс примелькаться на превью статей без обложки:

![squares-тщту-fin](https://user-images.githubusercontent.com/29401439/176204690-5adbf487-bf8d-4146-880a-923cd7a3de01.png)

Сашины формулировки очень нравятся.

**Comment by igsekor** [comment]
Картинки внедрены 😇
