### ISSUE TITLE
Ведение ченджлога

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#946]
Если вам удобнее аудио/видео, [рассказываю о том же в Loom](https://www.loom.com/share/01e7c38877a0483c94f67c7a6b6d8185).

@solarrust подняла вопрос о том, что было бы неплохо вести ченджлог изменений, чтобы иметь возможность быстро понять, что мы разработали в последнее время.

Правила хорошего ченджлога (https://keepachangelog.com/):
- написан для людей
- отражены только значимые изменения
- однотипные изменения сгруппированы
- есть версионирование

У нас есть два основных варианта — вести ченджлог вручную, либо автоматически

## Ручной ченджлог

Простое решение — вести ченджлог руками. У нас нет большого количества пул реквестов и внесение изменений руками не составит проблем.

Плюсы: 
- полный контроль над тем, что и как мы пишем в ченджлоге
- просто начать

Минусы:
- легко забыть (нужен чеклист)
- не масштабируется

## Автоматический ченджлог

Автоматический ченджлог создаётся с помощью внешней библиотеки. 

Я попробовал собрать ченджлог с помощью [`auto-changelog`](https://github.com/CookPete/auto-changelog) так как он гибко настраивается. Результат из коробки:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1469636/175649840-e6ad1614-dcec-4025-a5fa-e38d63488935.png">

☝️ Нам придётся создать ряд договорённостей, чтобы этот способ заработал. Все библиотеки, которые я видел, делают как минимум одно из двух предположений:
- приложение версионируется
- при разработке используются [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) для подписи комитов

Оба допущения не верны в нашем случае. В результате мы получаем картинку выше, либо чуть улучшенные её версии с группировкой.

Чтобы этот способ заработал, нужно будет __как минимум__ начать версионировать платформу.

Плюсы:
- всё делается за нас, если соблюдаются соглашения

Минусы:
- нужно придумать, как версионировать платформу
- нужно придумать договорённости к заголовкам коммитов
- нужно итегрировать инструмент и написать шаблоны

## 🍍 Самим написать генератор time-based changelog

Не очень понятно, зачем нам нужны версии, когда мы публикуемся по каждому смёрженному пул реквесту.

Идея: собирать ченджлог по времени, аналогично тому, как мы делаем руками [в контенте](https://github.com/doka-guide/content/blob/main/CHANGELOG.md).

Теоретически, это сводится к публикации новой версии каждый месяц и пункту выше, но технически этот вариант кажется простым:
1. получить список коммитов от определённой даты
2. отфильтровать неподходящие коммиты
3. нарезать на месяцы
4. сгруппировать, если нужно

Плюсы:
- простой инструмент, которым можно поделиться
- все работает само

Минусы:
- нужны договорённости к заголовкам коммитов, если хотим группировать
- нужно написать код

**Comment by pepelsbey** [comment]
Думаю лучше всего будет получать список автоматикой и дальше уже руками по документации делать для человеков. Зачем платформе версии вида семвера — не понимаю. Кажется, что версии вида хэша коммита более чем достаточно.

Кстати, начал бы я с версионирования контента, там это кажется нужнее и сейчас делается полностью руками. Ну, чтобы отладить метод.

**Comment by nlopin** [comment]
Обсуждение утихло и кажется ченджлог пока не требуется.
