### ISSUE TITLE
Добавить поддержку svg для юзерпиков

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#952]
На странице участников можно загрузить свою фотографию или картинку в качестве юзерпика. В данный момент не поддерживается формат SVG — такая картинка просто не отображается. Было бы круто это внедрить. Потому что svg уж очень хорош со всех сторон 😍

**Comment by furtivite** [comment]
@solarrust, привет. Кажется, [у Киры уже установлен SVG](https://doka.guide/people/kirakusto/), и issue уже неактуально. Можешь проверить не возникает ли проблем?

**Comment by nlopin** [comment]
Проверил, показывает Киру как надо
