### ISSUE TITLE
Не удается получить доступ к сайту

### ISSUE THREAD

**Issue by pobirsky** [doka-guide/platform#957]
Сайт https://doka.guide/ недоступен
![Снимок экрана 2022-07-13 в 11 29 20](https://user-images.githubusercontent.com/81918419/178688018-abff6203-d1cd-49ad-842d-e5fab16703e8.png)
.

**Comment by igsekor** [comment]
> Сайт https://doka.guide/ недоступен
> 

Большое спасибо за быструю реакцию! 🙏 Были работы на стороне сервера. Сейчас всё в порядке 😊
