### ISSUE TITLE
Починить переадресацию на материалах

### ISSUE THREAD

**Issue by furtivite** [doka-guide/platform#959]
При запросе в яндексе в индекс попали старые страницы, которые поменяли URL. Надо сделать переадресацию:

Приме
<img width="765" alt="Screenshot 2022-07-21 at 11 54 12" src="https://user-images.githubusercontent.com/50330458/180173539-840bcff6-ffd3-4485-a625-cd279449741e.png">
р:

Было: https://doka.guide/js/doka/prompt/
Стало: https://doka.guide/js/prompt/

**Comment by igsekor** [comment]
Ок!

**Comment by igsekor** [comment]
Исполнено
