### ISSUE TITLE
Не удается отправить оценку статьи

### ISSUE THREAD

**Issue by solarrust** [doka-guide/platform#962]
### Discussed in https://github.com/doka-guide/platform/discussions/961

<div type='discussions-op-text'>

<sup>Originally posted by **RoNUII** July 22, 2022</sup>
При нажатии кнопок для оценки **какой-либо** статьи:
![image](https://user-images.githubusercontent.com/49837634/180307530-4527a586-f36e-4f33-b889-b4f1a4f41273.png)

Консоль:
`POST https://api.doka.guide/form 401`
`Response {type: 'cors', url: 'https://api.doka.guide/form', redirected: false, status: 401, ok: false, …}`

Почему так, как быть и у одного меня ли такая ситуация?</div>

**Comment by igsekor** [comment]
Починил 😇

**Comment by RoNUII** [comment]
> Починил 😇

@igsekor После оценки статьи и обновлении страницы ожидал увидеть уже выбранную оценку, но увы, оценку можно выбрать вновь (баг или фича?), а с повторным выбором и такую же ошибку...  _видимо предыдущий раз я нажимал уже на оцененные статьи_ 🤭

**Comment by RoNUII** [comment]
Упс, у меня вновь такую ошибку выдает при оценке любой статьи и видимо это моя локальная проблема... Прошу прощения за беспокойство

**Comment by igsekor** [comment]
> > Починил 😇
> 
> @igsekor После оценки статьи и обновлении страницы ожидал увидеть уже выбранную оценку, но увы, оценку можно выбрать вновь (баг или фича?), а с повторным выбором и такую же ошибку... _видимо предыдущий раз я нажимал уже на оцененные статьи_ 🤭

У нас это не проверялось. Хорошая мысль, надо доработать поведение 🙃

**Comment by igsekor** [comment]
> Упс, у меня вновь такую ошибку выдает при оценке любой статьи и видимо это моя локальная проблема... Прошу прощения за беспокойство

Может быть, но может быть и нет) Проверю)
