### ISSUE TITLE
На темной теме не видно текста

### ISSUE THREAD

**Issue by senji84** [doka-guide/platform#963]
![Screen Shot 2022-07-27 at 7 34 37 PM](https://user-images.githubusercontent.com/99401799/181302126-ab768b9c-b2b3-4281-b42a-a3bd8f4fefd7.png)

**Comment by senji84** [comment]
https://user-images.githubusercontent.com/99401799/181509083-2a019dd6-fb95-4bab-abc2-2adb98a6698c.mov

**Comment by senji84** [comment]
[Запись с экрана.zip](https://github.com/doka-guide/platform/files/92097
[Запись консоли.mov.zip](https://github.com/doka-guide/platform/files/9209743/mov.zip)
27/default.zip)

Про сайт только узнал, поэтому раньше не видел. Но заметил что на некоторых сайтах тоже такая проблема есть. Не знаю с чем связано.

**Comment by senji84** [comment]
[Screen recording.mov.zip](https://github.com/doka-guide/platform/files/9213781/Screen.recording.mov.zip)

Зашел почитать и обнаружил, что и на остальных страницах также. Видео приложил.

**Comment by solarrust** [comment]
Если подобная проблема встречается не только на Доке, то, возможно, она связана с браузером. Пробовал отключать расширения, открывать сайт в другом браузере или в режиме Инкогнито?

**Comment by senji84** [comment]
Хм, попробую.

**Comment by senji84** [comment]
Так. Я удалил расширение - https://chrome.google.com/webstore/detail/flash-playlist/nddmmcpmdbkooddfjcohmlcfclhllgeh/related и все заработало нормально. В других браузерах все ок, только firefox stable пожаловался что сайт небезопасный.
