### ISSUE TITLE
Длинный текст не влазит в карточку рекомендаций

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#965]
Пример [статьи Функция](https://doka.guide/js/function/):

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/1469636/183393307-cd7870d0-9f36-4a3a-a3e8-49f2c0e18757.png">

Мне кажется тут нет правильного варианта, как это обрабатывать, но я бы попробовал переносить на следующую строку буквы, которые не влазят

**Comment by solarrust** [comment]
Я бы обрезала троеточием. С переносами могут возникнуть проблемы на русском, плюс нужно будет «впихнуть» тире.

**Comment by solarrust** [comment]
Докину пример с очень высокими карточками и с невлезающим заголовком 
<img width="1116" alt="CleanShot 2022-08-08 at 14 21 21@2x" src="https://user-images.githubusercontent.com/13676514/183396850-beffe233-c32c-4304-ac56-3ae34e785e92.png">
