### ISSUE TITLE
В активных кнопках-фильтрах поиска видны артефакты

### ISSUE THREAD

**Issue by Inventoris** [doka-guide/platform#971]
Заметил, что в кнопках-фильтрах поиска при нажатии и при изменении масштаба начинают возникать артефакты. 

Пруф:
![doka_bag-issue](https://user-images.githubusercontent.com/106589280/186242396-4bd11dc1-1010-45a7-b938-916c83dfff7c.png)

Выглядит так, что в `<span class="tag-filter__text">` между границей блока и бордером возникает какой-то участок без краски, из-за чего виден бэкграунд.

Здесь убрал скругление и увеличил бордер, особенно видно артефакт:

![doka_bag-issue_wtbr](https://user-images.githubusercontent.com/106589280/186244464-b1e811fd-bae6-4270-a865-b1719df30ad1.png)

**Comment by solarrust** [comment]
Привет тут!
А можешь, пожалуйста, уточнить, в каком браузере и на какой системе видишь этот артефакт?
У меня на macOS Monterey в браузерах Safari, Chrome и FireFox не воспроизводится =(

**Comment by alexeyten** [comment]
Я в Firefox на Ubuntu вижу, хотя и не так ярко выраженно.
![Screenshot from 2022-08-24 11-34-07](https://user-images.githubusercontent.com/44377/186370974-c330a27f-0838-4115-8635-0bcbed662378.png)

**Comment by Inventoris** [comment]
Привет! :)

Windows 10 Pro, версия 21H2, сборка 19044.1889.

Браузеры:

![bag_screenshot](https://user-images.githubusercontent.com/106589280/186390738-a4fa7c15-2a09-40eb-b89e-ba08eee2666f.png)

В FireFox лучше всего, хуже всего в Эдже и Яндексе.
