### ISSUE TITLE
Срезанные фокусы у списков статей на главной

### ISSUE THREAD

**Issue by Inventoris** [doka-guide/platform#978]
FireFox:

![before-firefox](https://user-images.githubusercontent.com/106589280/188891179-a6b94d59-5360-4f12-871c-2ced6086a59c.png)

Хром:

![beforе-google](https://user-images.githubusercontent.com/106589280/188891214-002d2b6d-35e3-4162-908c-7a8ee5b31570.png)

Яндекс:

![image](https://user-images.githubusercontent.com/106589280/188892140-7e59a620-ad0f-4a7a-b818-132d67c25da0.png)

У меня также воспроизводится в других браузерах.

Может просто добавить чуть-чуть padding`а? К примеру:

<pre>
.article-indexes-list__item {
  padding: 5px 0 var(--column-offset) 5px;
}
</pre>

Выглядит везде хорошо:

FireFox:

![after-firefox](https://user-images.githubusercontent.com/106589280/188891899-e3edce09-4d3c-46a3-8716-44570a0d8a5c.png)

![after-firefox-2](https://user-images.githubusercontent.com/106589280/188891913-6635d68b-3435-46e5-a068-94ee102ecc21.png)

Хром:

![after-google](https://user-images.githubusercontent.com/106589280/188891964-30144b40-02a1-4443-afd2-1d0ba1043d70.png)

**Comment by solarrust** [comment]
Привет! На первый взгляд неплохое решение. Можешь, пожалуйста, прислать пиар? Так удобнее будет протестировать =)
