### ISSUE TITLE
Выдвигающийся хедер на сайте отвлекает от чтения

### ISSUE THREAD

**Issue by saint777** [doka-guide/platform#979]
При чтении/скроллинге.
Может возможно сделать настройку фиксации хедера или вообще убрать функцию движения хедера?
IMHO.

**Comment by slavkapiyavka** [comment]
Дополню пожелание: сделайте появление шапки только при скролле вверх на некоторое количество пикселей, например на 100. Потому что нынешнее выпадение шапки только раздражает и мешается - что на тачпаде, что на телефоне.
И хочется более быструю анимацию, потому что по ощущениям прячется оно быстрее, чем появляется. 125 милисекунд было бы достаточно.

@solarrust я могу взять это в работу, если пожелаете.

**Comment by TatianaFokina** [comment]
> @solarrust я могу взять это в работу, если не против.

Привет, отвечу за всех! Бери, конечно, эту задачку. С юзабилити меню есть очевидные проблемы, которые очень хотелось бы исправить.

**Comment by TatianaFokina** [comment]
Комментарий от @denisputnov:

> Привет, у .header есть переменная --header-animation-time: 0.6s;
> Не совсем понятно, откуда взялось это время
> Пользуясь сайтом, часто замечал, что с хедером что-то не то, ощущается заторможенным
Изменил время на 0.3s, выглядит лучше
> Решил погуглить best practice о UX анимаций, выяснил следующее:
> Оптмальным временем является диапазон от 100 до 400мс, где 400 - это уже очень долго
> Так вот, почему 600 стоит? Может имеет смысл поменять? Не думаю, что я единственный, кого такая длинная анимация раздржает)

**Comment by codimario** [comment]
Да, постоянно всплывающий хедер при скроллинге - это боль( При чтении очень часто приходится проматывать вверх чтобы перечитать предыдущие предложения, и постоянное всплытие очень напрягает, прям видос заскринил с этим
file:///home/user/Videos/Screencasts/Screencast%20from%2025-08-23%2016:19:19.webm
