### ISSUE TITLE
Анимация шапки на главной вызывает удивление

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#985]
- Она привлекает слишком много внимания
- Двигается очень медленно и в странное время
- Есть положение, при котором её просто не видно и зияет большое белое
- Если нажать Esc, то шапка вообще закрывается

https://user-images.githubusercontent.com/105274/191234960-6fab4382-c9f7-4619-bd82-9e02596f9054.mp4

**Comment by pepelsbey** [comment]
Видимо, так и надо #956 🤔

**Comment by pepelsbey** [comment]
![5x89XRx3sBZFC](https://user-images.githubusercontent.com/105274/197189463-4eb89ef2-6db4-4a34-b919-0609c6e37bcf.gif)

**Comment by skorobaeus** [comment]
Привет! Мы посовещались и решили, что шапка будет закрываться только по желанию пользователя. Зарелизим после всех горящих апдейтов, запланированных на ближайшее время ✌
