### ISSUE TITLE
Заголовок в виде кода слипается с описанием статьи при наличии изображения

### ISSUE THREAD

**Issue by rakleed** [doka-guide/platform#990]
`.article__title-code` практически не имеет отступа от `.article__description`, если есть `.article-image__content`. Пример: https://doka.guide/html/head/

![Screenshot 2022-10-01 at 22 59 42](https://user-images.githubusercontent.com/19418601/193426297-e9987e10-be35-4d6a-ae06-873f39ef42e5.png)

При этом если заголовок в виде обычного текста, то с отступом всё в порядке. Пример: https://doka.guide/html/flow/

**Comment by TatianaFokina** [comment]
А не подскажешь, в каком браузере и на какой операционной системе поймал этот баг?

**Comment by rakleed** [comment]
Похоже, проблема из-за блокировщика рекламы AdGuard: https://github.com/AdguardTeam/AdguardFilters/issues/131310
