### ISSUE TITLE
При переносе имени метода на следующую строку, на предыдущей остаётся точка

### ISSUE THREAD

**Issue by nlopin** [doka-guide/platform#992]
![image](https://user-images.githubusercontent.com/1469636/193659043-ce852020-9095-42f4-83e8-b6378a26a4fc.png)

Кажется решением будет просто перестать разбивать слова в коде по точкам. Но нужно убедиться, что это не повлияет на остальные разделы

**Comment by mantevian** [comment]
может, саму точку переносить на новую строку? насколько я понимаю, в https://github.com/doka-guide/platform/blob/main/src/transforms/code-breakify-transform.js можно `symbols` разделить на символы, до которых ставится переход на новую строку, и символы, после которых он ставится
